/*
This file is automatically generated
Ft_Esd_Primitives__h
Simulation wrapper
*/

/* Simulation wrapper for 'Ft_Esd_Render_Bitmap' */


/* Simulation wrapper for 'Ft_Esd_Render_BitmapScaled' */


/* Simulation wrapper for 'Ft_Esd_Render_Line' */


/* Simulation wrapper for 'Ft_Esd_Render_LineF' */


/* Simulation wrapper for 'Ft_Esd_Render_Rectangle' */


/* Simulation wrapper for 'Ft_Esd_Render_RectangleF' */


/* Simulation wrapper for 'Ft_Esd_Render_RectangleF_Gradient' */


/* Simulation wrapper for 'Ft_Esd_Render_Rectangle_Gradient' */


/* end of file */
