/*
This file is automatically generated
Ft_Esd_CoCmd__h
Simulation wrapper
*/

/* Simulation wrapper for 'Ft_Gpu_CoCmd_Button' */


/* Simulation wrapper for 'Ft_Gpu_CoCmd_Clock' */


/* Simulation wrapper for 'Ft_Gpu_CoCmd_Dial' */


/* Simulation wrapper for 'Ft_Gpu_CoCmd_Gauge' */


/* Simulation wrapper for 'Ft_Gpu_CoCmd_Keys' */


/* Simulation wrapper for 'Ft_Gpu_CoCmd_Number' */


/* Simulation wrapper for 'Ft_Gpu_CoCmd_Progress' */


/* Simulation wrapper for 'Ft_Gpu_CoCmd_Scrollbar' */


/* Simulation wrapper for 'Ft_Gpu_CoCmd_Slider' */


/* Simulation wrapper for 'Ft_Gpu_CoCmd_Text' */


/* Simulation wrapper for 'Ft_Gpu_CoCmd_Text_Ex' */


/* Simulation wrapper for 'Ft_Gpu_CoCmd_Toggle' */


/* end of file */
