/*
This file is automatically generated
DO NOT MODIFY BY HAND
AppScreen
Header
*/

#ifndef AppScreen__H
#define AppScreen__H

#include "Esd_Base.h"
#include "Ft_Esd.h"
#include "Ft_Esd_Layout_Fixed.h"
#include "Ft_Esd_Layout_Switch.h"
#include "Ft_Esd_Widget.h"
#include "Usr_AirConPage.h"
#include "Usr_BedroomLightPage.h"
#include "Usr_CeilingLightPage.h"
#include "Usr_Cool_Page.h"
#include "Usr_CurtainAdjustPage.h"
#include "Usr_CurtainMorePages.h"
#include "Usr_CurtainPage.h"
#include "Usr_CurtainTimingPage.h"
#include "Usr_Fan_Page.h"
#include "Usr_FloorHeatingOnPage.h"
#include "Usr_FloorHeatingPage.h"
#include "Usr_FramePage.h"
#include "Usr_HeatSettingPage.h"
#include "Usr_Heat_Page.h"
#include "Usr_HomePage.h"
#include "Usr_Humid_Page.h"
#include "Usr_LightPage.h"
#include "Usr_LivingroomLightPage.h"
#include "Usr_PowerPage.h"
#include "Usr_Time_Actor.h"
#include "Usr_WarmLightPage.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define AppScreen_CLASSID 0x87BF3D92
ESD_SYMBOL(AppScreen_CLASSID, Type = esd_classid_t)

ESD_WIDGET(AppScreen, Include = "AppScreen.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	int Increment__Value;
	int Decrement__Value;
	ESD_VARIABLE(CurrentPageIndex, Type = int8_t, Private)
	int8_t CurrentPageIndex;
	Usr_Time_Actor Usr_Time_Actor;
	Ft_Esd_Layout_Fixed Fixed_Positioning;
	Ft_Esd_Layout_Switch Switch_Page;
	Usr_HomePage *Usr_HomePage;
	Usr_LightPage *Usr_LightPage;
	Usr_FloorHeatingPage *Usr_FloorHeatingPage;
	Usr_CurtainPage *Usr_CurtainPage;
	Usr_AirConPage *Usr_AirConPage;
	Usr_Heat_Page *Usr_Heat_Page;
	Usr_WarmLightPage *Usr_WarmLightPage;
	Usr_Fan_Page *Usr_Fan_Page;
	Usr_Humid_Page *Usr_Humid_Page;
	Usr_LivingroomLightPage *Usr_LivingroomLightPage;
	Usr_CeilingLightPage *Usr_CeilingLightPage;
	Usr_BedroomLightPage *Usr_BedroomLightPage;
	Usr_CurtainAdjustPage *Usr_CurtainAdjustPage;
	Usr_Cool_Page *Usr_Cool_Page;
	Usr_CurtainMorePages *Usr_CurtainMorePages;
	Usr_CurtainTimingPage *Usr_CurtainTimingPage;
	Usr_FloorHeatingOnPage *Usr_FloorHeatingOnPage;
	Usr_HeatSettingPage *Usr_HeatSettingPage;
	Usr_PowerPage *Usr_PowerPage;
	Usr_FramePage *Usr_FramePage;
} AppScreen;

void AppScreen__Initializer(AppScreen *context);

ESD_SLOT(Start)
void AppScreen_Start(AppScreen *context);

ESD_SLOT(End)
void AppScreen_End(AppScreen *context);

ESD_SLOT(Update)
void AppScreen_Update(AppScreen *context);

ESD_SLOT(Right)
void AppScreen_Right(AppScreen *context);

ESD_SLOT(Push)
void AppScreen_Push(AppScreen *context);

ESD_SLOT(Left)
void AppScreen_Left(AppScreen *context);

#endif /* AppScreen__H */

/* end of file */
