/*
This file is automatically generated
back_white_icon
Header
*/

#ifndef back_white_icon__H
#define back_white_icon__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell back_white_icon(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo back_white_icon__Info;

ESD_FUNCTION(back_white_icon_0, Type = Ft_Esd_BitmapCell, DisplayName = "back_white_icon", Include = "back_white_icon.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define back_white_icon_0() ((Ft_Esd_BitmapCell){ .Info = &back_white_icon__Info, .Cell = 0 })

#endif /* back_white_icon__H */

/* end of file */
