/*
This file is automatically generated
CeilingLightWire1
C Source
*/

#include "CeilingLightWire1.h"

#include "Ft_Gpu.h"
#include "CeilingLightWire1_progmem.h"

Ft_Esd_BitmapInfo CeilingLightWire1__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 8,
	.Height = 53,
	.Format = L4,
	.Stride = 4,
	.Size = 212,
	.ProgMem = CeilingLightWire1_bin,
	.StorageSize = ((83 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell CeilingLightWire1(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &CeilingLightWire1__Info, 
		.Cell = cell 
	};
}


/* end of file */
