/*
This file is automatically generated
CeilingLigehtCase2
C Source
*/

#include "CeilingLigehtCase2.h"

#include "Ft_Gpu.h"
#include "CeilingLigehtCase2_progmem.h"

Ft_Esd_BitmapInfo CeilingLigehtCase2__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 164,
	.Height = 65,
	.Format = L4,
	.Stride = 82,
	.Size = 5330,
	.ProgMem = CeilingLigehtCase2_bin,
	.StorageSize = ((1850 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell CeilingLigehtCase2(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &CeilingLigehtCase2__Info, 
		.Cell = cell 
	};
}


/* end of file */
