/*
This file is automatically generated
CeilingLightWire1
Header
*/

#ifndef CeilingLightWire1__H
#define CeilingLightWire1__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell CeilingLightWire1(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo CeilingLightWire1__Info;

ESD_FUNCTION(CeilingLightWire1_0, Type = Ft_Esd_BitmapCell, DisplayName = "CeilingLightWire1", Include = "CeilingLightWire1.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define CeilingLightWire1_0() ((Ft_Esd_BitmapCell){ .Info = &CeilingLightWire1__Info, .Cell = 0 })

#endif /* CeilingLightWire1__H */

/* end of file */
