/*
This file is automatically generated
CeilingLigehtCase2
Header
*/

#ifndef CeilingLigehtCase2__H
#define CeilingLigehtCase2__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell CeilingLigehtCase2(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo CeilingLigehtCase2__Info;

ESD_FUNCTION(CeilingLigehtCase2_0, Type = Ft_Esd_BitmapCell, DisplayName = "CeilingLigehtCase2", Include = "CeilingLigehtCase2.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define CeilingLigehtCase2_0() ((Ft_Esd_BitmapCell){ .Info = &CeilingLigehtCase2__Info, .Cell = 0 })

#endif /* CeilingLigehtCase2__H */

/* end of file */
