/*
This file is automatically generated
CelingLight1
Header
*/

#ifndef CelingLight1__H
#define CelingLight1__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell CelingLight1(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo CelingLight1__Info;

ESD_FUNCTION(CelingLight1_0, Type = Ft_Esd_BitmapCell, DisplayName = "CelingLight1", Include = "CelingLight1.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define CelingLight1_0() ((Ft_Esd_BitmapCell){ .Info = &CelingLight1__Info, .Cell = 0 })

#endif /* CelingLight1__H */

/* end of file */
