/*
This file is automatically generated
curtain_close1
Header
*/

#ifndef curtain_close1__H
#define curtain_close1__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell curtain_close1(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo curtain_close1__Info;

ESD_FUNCTION(curtain_close1_0, Type = Ft_Esd_BitmapCell, DisplayName = "curtain_close1", Include = "curtain_close1.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define curtain_close1_0() ((Ft_Esd_BitmapCell){ .Info = &curtain_close1__Info, .Cell = 0 })

#endif /* curtain_close1__H */

/* end of file */
