/*
This file is automatically generated
curtain3
Header
*/

#ifndef curtain3__H
#define curtain3__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell curtain3(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo curtain3__Info;

ESD_FUNCTION(curtain3_0, Type = Ft_Esd_BitmapCell, DisplayName = "curtain3", Include = "curtain3.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define curtain3_0() ((Ft_Esd_BitmapCell){ .Info = &curtain3__Info, .Cell = 0 })

#endif /* curtain3__H */

/* end of file */
