/*
This file is automatically generated
DefaultTheme
C Source
*/

#include "DefaultTheme.h"

static Ft_Esd_Theme DefaultTheme__Instance = {
	.ClearColor = 0xff000000,
	.BackColor = 0xff000000,
	.TextColor = 0xffffffff,
	.ButtonTextColor = 0xffffffff,
	.DefaultColor = 0xff6b6b6b,
	.PrimaryColor = 0xff5bce65,
};

Ft_Esd_Theme *DefaultTheme()
{
	return &DefaultTheme__Instance;
}

/* end of file */
