/*
This file is automatically generated
fan4
C Source
*/

#include "fan4.h"

#include "Ft_Gpu.h"
#include "fan4_progmem.h"

Ft_Esd_BitmapInfo fan4__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 128,
	.Height = 128,
	.Format = L4,
	.Stride = 64,
	.Size = 8192,
	.ProgMem = fan4_bin,
	.StorageSize = ((1087 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell fan4(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &fan4__Info, 
		.Cell = cell 
	};
}


/* end of file */
