/*
This file is automatically generated
fan_icon
Header
*/

#ifndef fan_icon__H
#define fan_icon__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell fan_icon(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo fan_icon__Info;

ESD_FUNCTION(fan_icon_0, Type = Ft_Esd_BitmapCell, DisplayName = "fan_icon", Include = "fan_icon.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define fan_icon_0() ((Ft_Esd_BitmapCell){ .Info = &fan_icon__Info, .Cell = 0 })

#endif /* fan_icon__H */

/* end of file */
