/*
This file is automatically generated
FloorHeatOff
Header
*/

#ifndef FloorHeatOff__H
#define FloorHeatOff__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell FloorHeatOff(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo FloorHeatOff__Info;

ESD_FUNCTION(FloorHeatOff_0, Type = Ft_Esd_BitmapCell, DisplayName = "FloorHeatOff", Include = "FloorHeatOff.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define FloorHeatOff_0() ((Ft_Esd_BitmapCell){ .Info = &FloorHeatOff__Info, .Cell = 0 })

#endif /* FloorHeatOff__H */

/* end of file */
