/*
This file is automatically generated
floor_heating3
Header
*/

#ifndef floor_heating3__H
#define floor_heating3__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell floor_heating3(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo floor_heating3__Info;

ESD_FUNCTION(floor_heating3_0, Type = Ft_Esd_BitmapCell, DisplayName = "floor_heating3", Include = "floor_heating3.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define floor_heating3_0() ((Ft_Esd_BitmapCell){ .Info = &floor_heating3__Info, .Cell = 0 })

#endif /* floor_heating3__H */

/* end of file */
