/*
This file is automatically generated
FloorHeatOn
C Source
*/

#include "FloorHeatOn.h"

#include "Ft_Gpu.h"
#include "FloorHeatOn_progmem.h"

Ft_Esd_BitmapInfo FloorHeatOn__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 83, /* Padded to 84, REPEAT will not work as expected */
	.Height = 52,
	.Format = L4,
	.Stride = 42,
	.Size = 2184,
	.ProgMem = FloorHeatOn_bin,
	.StorageSize = ((902 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell FloorHeatOn(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &FloorHeatOn__Info, 
		.Cell = cell 
	};
}


/* end of file */
