/*
This file is automatically generated
floor_heating3
C Source
*/

#include "floor_heating3.h"

#include "Ft_Gpu.h"
#include "floor_heating3_progmem.h"

Ft_Esd_BitmapInfo floor_heating3__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 58,
	.Height = 38,
	.Format = L4,
	.Stride = 29,
	.Size = 1102,
	.ProgMem = floor_heating3_bin,
	.StorageSize = ((681 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell floor_heating3(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &floor_heating3__Info, 
		.Cell = cell 
	};
}


/* end of file */
