/*
This file is automatically generated
funtion_icon
C Source
*/

#include "funtion_icon.h"

#include "Ft_Gpu.h"
#include "funtion_icon_progmem.h"

Ft_Esd_BitmapInfo funtion_icon__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 64,
	.Height = 65,
	.Format = L4,
	.Stride = 32,
	.Size = 2080,
	.ProgMem = funtion_icon_bin,
	.StorageSize = ((646 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell funtion_icon(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &funtion_icon__Info, 
		.Cell = cell 
	};
}


/* end of file */
