/*
This file is automatically generated
funtion_icon
Header
*/

#ifndef funtion_icon__H
#define funtion_icon__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell funtion_icon(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo funtion_icon__Info;

ESD_FUNCTION(funtion_icon_0, Type = Ft_Esd_BitmapCell, DisplayName = "funtion_icon", Include = "funtion_icon.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define funtion_icon_0() ((Ft_Esd_BitmapCell){ .Info = &funtion_icon__Info, .Cell = 0 })

#endif /* funtion_icon__H */

/* end of file */
