/*
This file is automatically generated
heat_white_icon
Header
*/

#ifndef heat_white_icon__H
#define heat_white_icon__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell heat_white_icon(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo heat_white_icon__Info;

ESD_FUNCTION(heat_white_icon_0, Type = Ft_Esd_BitmapCell, DisplayName = "heat_white_icon", Include = "heat_white_icon.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define heat_white_icon_0() ((Ft_Esd_BitmapCell){ .Info = &heat_white_icon__Info, .Cell = 0 })

#endif /* heat_white_icon__H */

/* end of file */
