/*
This file is automatically generated
LampNeck
Header
*/

#ifndef LampNeck__H
#define LampNeck__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell LampNeck(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo LampNeck__Info;

ESD_FUNCTION(LampNeck_0, Type = Ft_Esd_BitmapCell, DisplayName = "LampNeck", Include = "LampNeck.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define LampNeck_0() ((Ft_Esd_BitmapCell){ .Info = &LampNeck__Info, .Cell = 0 })

#endif /* LampNeck__H */

/* end of file */
