/*
This file is automatically generated
LampChasis1
Header
*/

#ifndef LampChasis1__H
#define LampChasis1__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell LampChasis1(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo LampChasis1__Info;

ESD_FUNCTION(LampChasis1_0, Type = Ft_Esd_BitmapCell, DisplayName = "LampChasis1", Include = "LampChasis1.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define LampChasis1_0() ((Ft_Esd_BitmapCell){ .Info = &LampChasis1__Info, .Cell = 0 })

#endif /* LampChasis1__H */

/* end of file */
