/*
This file is automatically generated
LampNeck
C Source
*/

#include "LampNeck.h"

#include "Ft_Gpu.h"
#include "LampNeck_progmem.h"

Ft_Esd_BitmapInfo LampNeck__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 36,
	.Height = 29,
	.Format = L4,
	.Stride = 18,
	.Size = 522,
	.ProgMem = LampNeck_bin,
	.StorageSize = ((289 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell LampNeck(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &LampNeck__Info, 
		.Cell = cell 
	};
}


/* end of file */
