/*
This file is automatically generated
Lamp
Header
*/

#ifndef Lamp__H
#define Lamp__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell Lamp(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo Lamp__Info;

ESD_FUNCTION(Lamp_0, Type = Ft_Esd_BitmapCell, DisplayName = "Lamp", Include = "Lamp.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define Lamp_0() ((Ft_Esd_BitmapCell){ .Info = &Lamp__Info, .Cell = 0 })

#endif /* Lamp__H */

/* end of file */
