/*
This file is automatically generated
LampChasis2
C Source
*/

#include "LampChasis2.h"

#include "Ft_Gpu.h"
#include "LampChasis2_progmem.h"

Ft_Esd_BitmapInfo LampChasis2__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 97, /* Padded to 98, REPEAT will not work as expected */
	.Height = 11,
	.Format = L4,
	.Stride = 49,
	.Size = 539,
	.ProgMem = LampChasis2_bin,
	.StorageSize = ((199 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell LampChasis2(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &LampChasis2__Info, 
		.Cell = cell 
	};
}


/* end of file */
