/*
This file is automatically generated
light_page_on
Header
*/

#ifndef light_page_on__H
#define light_page_on__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell light_page_on(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo light_page_on__Info;

ESD_FUNCTION(light_page_on_0, Type = Ft_Esd_BitmapCell, DisplayName = "light_page_on", Include = "light_page_on.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define light_page_on_0() ((Ft_Esd_BitmapCell){ .Info = &light_page_on__Info, .Cell = 0 })

#endif /* light_page_on__H */

/* end of file */
