/*
This file is automatically generated
LightOn
Header
*/

#ifndef LightOn__H
#define LightOn__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell LightOn(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo LightOn__Info;

ESD_FUNCTION(LightOn_0, Type = Ft_Esd_BitmapCell, DisplayName = "LightOn", Include = "LightOn.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define LightOn_0() ((Ft_Esd_BitmapCell){ .Info = &LightOn__Info, .Cell = 0 })

#endif /* LightOn__H */

/* end of file */
