/*
This file is automatically generated
LightCase
Header
*/

#ifndef LightCase__H
#define LightCase__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell LightCase(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo LightCase__Info;

ESD_FUNCTION(LightCase_0, Type = Ft_Esd_BitmapCell, DisplayName = "LightCase", Include = "LightCase.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define LightCase_0() ((Ft_Esd_BitmapCell){ .Info = &LightCase__Info, .Cell = 0 })

#endif /* LightCase__H */

/* end of file */
