/*
This file is automatically generated
LightCase
C Source
*/

#include "LightCase.h"

#include "Ft_Gpu.h"
#include "LightCase_progmem.h"

Ft_Esd_BitmapInfo LightCase__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 77, /* Padded to 78, REPEAT will not work as expected */
	.Height = 43,
	.Format = L4,
	.Stride = 39,
	.Size = 1677,
	.ProgMem = LightCase_bin,
	.StorageSize = ((358 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell LightCase(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &LightCase__Info, 
		.Cell = cell 
	};
}


/* end of file */
