/*
This file is automatically generated
light_on_38
Header
*/

#ifndef light_on_38__H
#define light_on_38__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell light_on_38(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo light_on_38__Info;

ESD_FUNCTION(light_on_38_0, Type = Ft_Esd_BitmapCell, DisplayName = "light_on_38", Include = "light_on_38.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define light_on_38_0() ((Ft_Esd_BitmapCell){ .Info = &light_on_38__Info, .Cell = 0 })

#endif /* light_on_38__H */

/* end of file */
