/*
This file is automatically generated
light_page_on
C Source
*/

#include "light_page_on.h"

#include "Ft_Gpu.h"
#include "light_page_on_progmem.h"

Ft_Esd_BitmapInfo light_page_on__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 45, /* Padded to 46, REPEAT will not work as expected */
	.Height = 35,
	.Format = L4,
	.Stride = 23,
	.Size = 805,
	.ProgMem = light_page_on_bin,
	.StorageSize = ((308 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell light_page_on(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &light_page_on__Info, 
		.Cell = cell 
	};
}


/* end of file */
