/*
This file is automatically generated
linkable
Header
*/

#ifndef linkable__H
#define linkable__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell linkable(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo linkable__Info;

ESD_FUNCTION(linkable_0, Type = Ft_Esd_BitmapCell, DisplayName = "linkable", Include = "linkable.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define linkable_0() ((Ft_Esd_BitmapCell){ .Info = &linkable__Info, .Cell = 0 })

#endif /* linkable__H */

/* end of file */
