/*
This file is automatically generated
linkable
C Source
*/

#include "linkable.h"

#include "Ft_Gpu.h"
#include "linkable_progmem.h"

Ft_Esd_BitmapInfo linkable__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 40,
	.Height = 40,
	.Format = L4,
	.Stride = 20,
	.Size = 800,
	.ProgMem = linkable_bin,
	.StorageSize = ((425 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell linkable(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &linkable__Info, 
		.Cell = cell 
	};
}


/* end of file */
