/*
This file is automatically generated
livingroom_light_case
C Source
*/

#include "livingroom_light_case.h"

#include "Ft_Gpu.h"
#include "livingroom_light_case_progmem.h"

Ft_Esd_BitmapInfo livingroom_light_case__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 164,
	.Height = 105,
	.Format = L4,
	.Stride = 82,
	.Size = 8610,
	.ProgMem = livingroom_light_case_bin,
	.StorageSize = ((757 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell livingroom_light_case(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &livingroom_light_case__Info, 
		.Cell = cell 
	};
}


/* end of file */
