/*
This file is automatically generated
livingroom_light_case
Header
*/

#ifndef livingroom_light_case__H
#define livingroom_light_case__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell livingroom_light_case(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo livingroom_light_case__Info;

ESD_FUNCTION(livingroom_light_case_0, Type = Ft_Esd_BitmapCell, DisplayName = "livingroom_light_case", Include = "livingroom_light_case.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define livingroom_light_case_0() ((Ft_Esd_BitmapCell){ .Info = &livingroom_light_case__Info, .Cell = 0 })

#endif /* livingroom_light_case__H */

/* end of file */
