/*
This file is automatically generated
DO NOT MODIFY BY HAND
newImageScale
C Source
*/

#include "newImageScale.h"

#include "Esd_Context.h"
#include "Ft_Esd_Primitives.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
Ft_Esd_BitmapCell newImageScale_BitmapCell__Default(void *context) { return (Ft_Esd_BitmapCell){ 0 }; }
ft_int32_f16_t newImageScale_XScale__Default(void *context) { return 0L; }


static Ft_Esd_WidgetSlots s_newImageScale__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))newImageScale_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Widget_End,
};


void newImageScale__Initializer(newImageScale *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = newImageScale_CLASSID;
	context->Widget.Slots = &s_newImageScale__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->BitmapCell = newImageScale_BitmapCell__Default;
	context->XScale = newImageScale_XScale__Default;
}


void newImageScale_Render(newImageScale *context)
{
	void *owner = context->Owner;
	ft_int16_t x = context->Widget.GlobalX;
	ft_int16_t y = context->Widget.GlobalY;
	Ft_Esd_BitmapCell bitmapCell = context->BitmapCell(owner);
	ft_argb32_t c_1 = 0xff02a6ffUL;
	ft_int32_f16_t xscale = context->XScale(owner);
	ft_int32_f16_t yscale = (1L * (1L << 16) + 0x9999L);
	ft_int32_f16_t xoffset = 0L;
	ft_int32_f16_t yoffset = 0L;
	ft_int16_t width = context->Widget.GlobalWidth;
	ft_int16_t height = context->Widget.GlobalHeight;
	Ft_Esd_Render_BitmapScaled(x, y, bitmapCell, c_1, xscale, yscale, xoffset, yoffset, width, height);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context);
}


/* end of file */
