/*
This file is automatically generated
open_curtain
Header
*/

#ifndef open_curtain__H
#define open_curtain__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell open_curtain(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo open_curtain__Info;

ESD_FUNCTION(open_curtain_0, Type = Ft_Esd_BitmapCell, DisplayName = "open_curtain", Include = "open_curtain.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define open_curtain_0() ((Ft_Esd_BitmapCell){ .Info = &open_curtain__Info, .Cell = 0 })

#endif /* open_curtain__H */

/* end of file */
