/*
This file is automatically generated
power
Header
*/

#ifndef power__H
#define power__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell power(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo power__Info;

ESD_FUNCTION(power_0, Type = Ft_Esd_BitmapCell, DisplayName = "power", Include = "power.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define power_0() ((Ft_Esd_BitmapCell){ .Info = &power__Info, .Cell = 0 })

#endif /* power__H */

/* end of file */
