/*
This file is automatically generated
power
C Source
*/

#include "power.h"

#include "Ft_Gpu.h"
#include "power_progmem.h"

Ft_Esd_BitmapInfo power__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 64,
	.Height = 54,
	.Format = L4,
	.Stride = 32,
	.Size = 1728,
	.ProgMem = power_bin,
	.StorageSize = ((413 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell power(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &power__Info, 
		.Cell = cell 
	};
}


/* end of file */
