/*
This file is automatically generated
return_circle_64
Header
*/

#ifndef return_circle_64__H
#define return_circle_64__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell return_circle_64(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo return_circle_64__Info;

ESD_FUNCTION(return_circle_64_0, Type = Ft_Esd_BitmapCell, DisplayName = "return_circle_64", Include = "return_circle_64.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define return_circle_64_0() ((Ft_Esd_BitmapCell){ .Info = &return_circle_64__Info, .Cell = 0 })

#endif /* return_circle_64__H */

/* end of file */
