/*
This file is automatically generated
right_curtain
Header
*/

#ifndef right_curtain__H
#define right_curtain__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell right_curtain(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo right_curtain__Info;

ESD_FUNCTION(right_curtain_0, Type = Ft_Esd_BitmapCell, DisplayName = "right_curtain", Include = "right_curtain.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define right_curtain_0() ((Ft_Esd_BitmapCell){ .Info = &right_curtain__Info, .Cell = 0 })

#endif /* right_curtain__H */

/* end of file */
