/*
This file is automatically generated
right_curtain
C Source
*/

#include "right_curtain.h"

#include "Ft_Gpu.h"
#include "right_curtain_progmem.h"

Ft_Esd_BitmapInfo right_curtain__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 80,
	.Height = 100,
	.Format = L4,
	.Stride = 40,
	.Size = 4000,
	.ProgMem = right_curtain_bin,
	.StorageSize = ((978 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell right_curtain(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &right_curtain__Info, 
		.Cell = cell 
	};
}


/* end of file */
