/*
This file is automatically generated
setting
C Source
*/

#include "setting.h"

#include "Ft_Gpu.h"
#include "setting_progmem.h"

Ft_Esd_BitmapInfo setting__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 64,
	.Height = 64,
	.Format = L4,
	.Stride = 32,
	.Size = 2048,
	.ProgMem = setting_bin,
	.StorageSize = ((843 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell setting(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &setting__Info, 
		.Cell = cell 
	};
}


/* end of file */
