/*
This file is automatically generated
setting
Header
*/

#ifndef setting__H
#define setting__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell setting(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo setting__Info;

ESD_FUNCTION(setting_0, Type = Ft_Esd_BitmapCell, DisplayName = "setting", Include = "setting.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define setting_0() ((Ft_Esd_BitmapCell){ .Info = &setting__Info, .Cell = 0 })

#endif /* setting__H */

/* end of file */
