/*
This file is automatically generated
snow_white_icon
C Source
*/

#include "snow_white_icon.h"

#include "Ft_Gpu.h"
#include "snow_white_icon_progmem.h"

Ft_Esd_BitmapInfo snow_white_icon__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 32,
	.Height = 32,
	.Format = L4,
	.Stride = 16,
	.Size = 512,
	.ProgMem = snow_white_icon_bin,
	.StorageSize = ((110 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell snow_white_icon(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &snow_white_icon__Info, 
		.Cell = cell 
	};
}


/* end of file */
