/*
This file is automatically generated
snow_icon
Header
*/

#ifndef snow_icon__H
#define snow_icon__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell snow_icon(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo snow_icon__Info;

ESD_FUNCTION(snow_icon_0, Type = Ft_Esd_BitmapCell, DisplayName = "snow_icon", Include = "snow_icon.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define snow_icon_0() ((Ft_Esd_BitmapCell){ .Info = &snow_icon__Info, .Cell = 0 })

#endif /* snow_icon__H */

/* end of file */
