/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_CurtainTimingPage
C Source
*/

#include "Usr_CurtainTimingPage.h"

#include "Esd_Context.h"
#include "Usr_GlobalVariables.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);

static uint8_t Usr_CurtainTimingPage_ESD_Label_2_1_1_Font__Property(void *context) { return 28; }
static const char * Usr_CurtainTimingPage_ESD_Label_2_1_1_Text__Property(void *context) { return "Close curtains"; }
static uint8_t Usr_CurtainTimingPage_ESD_Label_2_1_Font__Property(void *context) { return 28; }
static const char * Usr_CurtainTimingPage_ESD_Label_2_1_Text__Property(void *context) { return "Open curtains"; }
static uint8_t Usr_CurtainTimingPage_ESD_Label_2_Font__Property(void *context) { return 28; }
static const char * Usr_CurtainTimingPage_ESD_Label_2_Text__Property(void *context) { return "Open curtains"; }
static ft_uint8_t Usr_CurtainTimingPage_ESD_Image_Button_MinAlpha__Property(void *context) { return 0; }
static Ft_Esd_BitmapCell Usr_CurtainTimingPage_ESD_Image_Button_BitmapNormal__Property(void *context) { return return_circle_64_0(); }
static Ft_Esd_Theme * Usr_CurtainTimingPage_ESD_Toggle_1_1_1_Theme__Property(void *context) { return Usr_Toogle_Theme(); }
static const char * Usr_CurtainTimingPage_ESD_Toggle_1_1_1_Text__Property(void *context) { return ""; }
static uint8_t Usr_CurtainTimingPage_ESD_Toggle_1_1_1_Font__Property(void *context) { return 22; }
static Ft_Esd_Theme * Usr_CurtainTimingPage_ESD_Toggle_1_1_Theme__Property(void *context) { return Usr_Toogle_Theme(); }
static const char * Usr_CurtainTimingPage_ESD_Toggle_1_1_Text__Property(void *context) { return ""; }
static uint8_t Usr_CurtainTimingPage_ESD_Toggle_1_1_Font__Property(void *context) { return 22; }
static Ft_Esd_Theme * Usr_CurtainTimingPage_ESD_Toggle_1_Theme__Property(void *context) { return Usr_Toogle_Theme(); }
static const char * Usr_CurtainTimingPage_ESD_Toggle_1_Text__Property(void *context) { return ""; }
static uint8_t Usr_CurtainTimingPage_ESD_Toggle_1_Font__Property(void *context) { return 22; }
static uint8_t Usr_CurtainTimingPage_ESD_Label_1_2_1_Font__Property(void *context) { return 30; }
static const char * Usr_CurtainTimingPage_ESD_Label_1_2_1_Text__Property(void *context) { return "15:30"; }
static ft_uint16_t Usr_CurtainTimingPage_ESD_Label_1_2_1_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static uint8_t Usr_CurtainTimingPage_ESD_Label_1_2_Font__Property(void *context) { return 30; }
static const char * Usr_CurtainTimingPage_ESD_Label_1_2_Text__Property(void *context) { return "21:20"; }
static ft_uint16_t Usr_CurtainTimingPage_ESD_Label_1_2_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static uint8_t Usr_CurtainTimingPage_ESD_Label_1_Font__Property(void *context) { return 30; }
static const char * Usr_CurtainTimingPage_ESD_Label_1_Text__Property(void *context) { return "08:30"; }
static ft_uint16_t Usr_CurtainTimingPage_ESD_Label_1_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_int32_t Usr_CurtainTimingPage_Rectangle_Light_2_Radius__Property(void *context) { return 10L; }
static ft_argb32_t Usr_CurtainTimingPage_Rectangle_Light_2_Color__Property(void *context) { return 0x3ae8f1f9UL; }
static ft_int32_t Usr_CurtainTimingPage_Rectangle_Light_1_Radius__Property(void *context) { return 10L; }
static ft_argb32_t Usr_CurtainTimingPage_Rectangle_Light_1_Color__Property(void *context) { return 0x3ae8f1f9UL; }
static ft_int32_t Usr_CurtainTimingPage_Rectangle_Light_Radius__Property(void *context) { return 10L; }
static ft_argb32_t Usr_CurtainTimingPage_Rectangle_Light_Color__Property(void *context) { return 0x3ae8f1f9UL; }
static uint8_t Usr_CurtainTimingPage_ESD_Label_Font__Property(void *context) { return 29; }
static const char * Usr_CurtainTimingPage_ESD_Label_Text__Property(void *context) { return "Curtain timing"; }
static ft_uint16_t Usr_CurtainTimingPage_ESD_Label_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_int32_t Usr_CurtainTimingPage_ESD_Rectangle_Widget_4_Radius__Property(void *context) { return 24L; }
static ft_argb32_t Usr_CurtainTimingPage_ESD_Rectangle_Widget_4_Color__Property(void *context) { return 0x59000000UL; }

static Ft_Esd_WidgetSlots s_Usr_CurtainTimingPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Usr_CurtainTimingPage_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_CurtainTimingPage_End,
};

static void Usr_CurtainTimingPage_ESD_Image_Button_Pushed__Signal(void *context);
static void Usr_CurtainTimingPage_ESD_Toggle_1_1_1_Toggled__Signal(void *context);
static void Usr_CurtainTimingPage_ESD_Toggle_1_1_Toggled__Signal(void *context);
static void Usr_CurtainTimingPage_ESD_Toggle_1_Toggled__Signal(void *context);

void Usr_CurtainTimingPage__Fixed_Position__Initializer(Usr_CurtainTimingPage *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_CurtainTimingPage__ESD_Label_2_1_1__Initializer(Usr_CurtainTimingPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2_1_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 99;
	object->Widget.LocalY = 230;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_CurtainTimingPage_ESD_Label_2_1_1_Font__Property;
	object->Text = Usr_CurtainTimingPage_ESD_Label_2_1_1_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainTimingPage__ESD_Label_2_1__Initializer(Usr_CurtainTimingPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 98;
	object->Widget.LocalY = 312;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_CurtainTimingPage_ESD_Label_2_1_Font__Property;
	object->Text = Usr_CurtainTimingPage_ESD_Label_2_1_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainTimingPage__ESD_Label_2__Initializer(Usr_CurtainTimingPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 98;
	object->Widget.LocalY = 151;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_CurtainTimingPage_ESD_Label_2_Font__Property;
	object->Text = Usr_CurtainTimingPage_ESD_Label_2_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainTimingPage__ESD_Image_Button__Initializer(Usr_CurtainTimingPage *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 216;
	object->Widget.LocalY = 379;
	object->Widget.LocalWidth = 64;
	object->Widget.LocalHeight = 64;
	object->MinAlpha = Usr_CurtainTimingPage_ESD_Image_Button_MinAlpha__Property;
	object->BitmapNormal = Usr_CurtainTimingPage_ESD_Image_Button_BitmapNormal__Property;
	object->Pushed = Usr_CurtainTimingPage_ESD_Image_Button_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainTimingPage__ESD_Toggle_1_1_1__Initializer(Usr_CurtainTimingPage *context)
{
	Ft_Esd_Toggle *object = (Ft_Esd_Toggle *)&context->ESD_Toggle_1_1_1;
	Ft_Esd_Toggle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 340;
	object->Widget.LocalY = 313;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 14;
	object->Theme = Usr_CurtainTimingPage_ESD_Toggle_1_1_1_Theme__Property;
	object->Text = Usr_CurtainTimingPage_ESD_Toggle_1_1_1_Text__Property;
	object->State = 1;
	object->Font = Usr_CurtainTimingPage_ESD_Toggle_1_1_1_Font__Property;
	object->Style = ESD_OPT_FLAT;
	object->Toggled = Usr_CurtainTimingPage_ESD_Toggle_1_1_1_Toggled__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainTimingPage__ESD_Toggle_1_1__Initializer(Usr_CurtainTimingPage *context)
{
	Ft_Esd_Toggle *object = (Ft_Esd_Toggle *)&context->ESD_Toggle_1_1;
	Ft_Esd_Toggle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 340;
	object->Widget.LocalY = 235;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 14;
	object->Theme = Usr_CurtainTimingPage_ESD_Toggle_1_1_Theme__Property;
	object->Text = Usr_CurtainTimingPage_ESD_Toggle_1_1_Text__Property;
	object->State = 1;
	object->Font = Usr_CurtainTimingPage_ESD_Toggle_1_1_Font__Property;
	object->Style = ESD_OPT_FLAT;
	object->Toggled = Usr_CurtainTimingPage_ESD_Toggle_1_1_Toggled__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainTimingPage__ESD_Toggle_1__Initializer(Usr_CurtainTimingPage *context)
{
	Ft_Esd_Toggle *object = (Ft_Esd_Toggle *)&context->ESD_Toggle_1;
	Ft_Esd_Toggle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 340;
	object->Widget.LocalY = 152;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 14;
	object->Theme = Usr_CurtainTimingPage_ESD_Toggle_1_Theme__Property;
	object->Text = Usr_CurtainTimingPage_ESD_Toggle_1_Text__Property;
	object->State = 1;
	object->Font = Usr_CurtainTimingPage_ESD_Toggle_1_Font__Property;
	object->Style = ESD_OPT_FLAT;
	object->Toggled = Usr_CurtainTimingPage_ESD_Toggle_1_Toggled__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainTimingPage__ESD_Label_1_2_1__Initializer(Usr_CurtainTimingPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_1_2_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 244;
	object->Widget.LocalY = 308;
	object->Widget.LocalWidth = 84;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_CurtainTimingPage_ESD_Label_1_2_1_Font__Property;
	object->Text = Usr_CurtainTimingPage_ESD_Label_1_2_1_Text__Property;
	object->AlignX = Usr_CurtainTimingPage_ESD_Label_1_2_1_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainTimingPage__ESD_Label_1_2__Initializer(Usr_CurtainTimingPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_1_2;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 245;
	object->Widget.LocalY = 225;
	object->Widget.LocalWidth = 84;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_CurtainTimingPage_ESD_Label_1_2_Font__Property;
	object->Text = Usr_CurtainTimingPage_ESD_Label_1_2_Text__Property;
	object->AlignX = Usr_CurtainTimingPage_ESD_Label_1_2_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainTimingPage__ESD_Label_1__Initializer(Usr_CurtainTimingPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 244;
	object->Widget.LocalY = 148;
	object->Widget.LocalWidth = 84;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_CurtainTimingPage_ESD_Label_1_Font__Property;
	object->Text = Usr_CurtainTimingPage_ESD_Label_1_Text__Property;
	object->AlignX = Usr_CurtainTimingPage_ESD_Label_1_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainTimingPage__Rectangle_Light_2__Initializer(Usr_CurtainTimingPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->Rectangle_Light_2;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 80;
	object->Widget.LocalY = 299;
	object->Widget.LocalWidth = 320;
	object->Widget.LocalHeight = 54;
	object->Radius = Usr_CurtainTimingPage_Rectangle_Light_2_Radius__Property;
	object->Color = Usr_CurtainTimingPage_Rectangle_Light_2_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainTimingPage__Rectangle_Light_1__Initializer(Usr_CurtainTimingPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->Rectangle_Light_1;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 80;
	object->Widget.LocalY = 217;
	object->Widget.LocalWidth = 320;
	object->Widget.LocalHeight = 54;
	object->Radius = Usr_CurtainTimingPage_Rectangle_Light_1_Radius__Property;
	object->Color = Usr_CurtainTimingPage_Rectangle_Light_1_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainTimingPage__Rectangle_Light__Initializer(Usr_CurtainTimingPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->Rectangle_Light;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 80;
	object->Widget.LocalY = 138;
	object->Widget.LocalWidth = 320;
	object->Widget.LocalHeight = 54;
	object->Radius = Usr_CurtainTimingPage_Rectangle_Light_Radius__Property;
	object->Color = Usr_CurtainTimingPage_Rectangle_Light_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainTimingPage__ESD_Label__Initializer(Usr_CurtainTimingPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 124;
	object->Widget.LocalY = 69;
	object->Widget.LocalWidth = 230;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_CurtainTimingPage_ESD_Label_Font__Property;
	object->Text = Usr_CurtainTimingPage_ESD_Label_Text__Property;
	object->AlignX = Usr_CurtainTimingPage_ESD_Label_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainTimingPage__ESD_Rectangle_Widget_4__Initializer(Usr_CurtainTimingPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget_4;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 123;
	object->Widget.LocalY = 61;
	object->Widget.LocalWidth = 234;
	object->Widget.LocalHeight = 48;
	object->Radius = Usr_CurtainTimingPage_ESD_Rectangle_Widget_4_Radius__Property;
	object->Color = Usr_CurtainTimingPage_ESD_Rectangle_Widget_4_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainTimingPage__Initializer(Usr_CurtainTimingPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_CurtainTimingPage_CLASSID;
	context->Widget.Slots = &s_Usr_CurtainTimingPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->BackPushed = Esd_Noop;
	Usr_CurtainTimingPage__Fixed_Position__Initializer(context);
	Usr_CurtainTimingPage__ESD_Label_2_1_1__Initializer(context);
	Usr_CurtainTimingPage__ESD_Label_2_1__Initializer(context);
	Usr_CurtainTimingPage__ESD_Label_2__Initializer(context);
	Usr_CurtainTimingPage__ESD_Image_Button__Initializer(context);
	Usr_CurtainTimingPage__ESD_Toggle_1_1_1__Initializer(context);
	Usr_CurtainTimingPage__ESD_Toggle_1_1__Initializer(context);
	Usr_CurtainTimingPage__ESD_Toggle_1__Initializer(context);
	Usr_CurtainTimingPage__ESD_Label_1_2_1__Initializer(context);
	Usr_CurtainTimingPage__ESD_Label_1_2__Initializer(context);
	Usr_CurtainTimingPage__ESD_Label_1__Initializer(context);
	Usr_CurtainTimingPage__Rectangle_Light_2__Initializer(context);
	Usr_CurtainTimingPage__Rectangle_Light_1__Initializer(context);
	Usr_CurtainTimingPage__Rectangle_Light__Initializer(context);
	Usr_CurtainTimingPage__ESD_Label__Initializer(context);
	Usr_CurtainTimingPage__ESD_Rectangle_Widget_4__Initializer(context);
}

extern int g_TimingCurtain3;
extern int g_TimingCurtain1;
extern int g_TimingCurtain2;

void Usr_CurtainTimingPage_End(Usr_CurtainTimingPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Toggle_1_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Toggle_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Toggle_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_1_2_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_1_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Rectangle_Light_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Rectangle_Light_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Rectangle_Light); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget_4); 
}

void Usr_CurtainTimingPage_Start(Usr_CurtainTimingPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context); 
	ft_bool_t left = context->ESD_Toggle_1_1_1.State;
	int right = g_TimingCurtain3;
	int if_1 = left != right;
	if (if_1)
	{
		Ft_Esd_Toggle_Toggle(&context->ESD_Toggle_1_1_1);
	}
	else
	{
	}
	ft_bool_t left_1 = context->ESD_Toggle_1.State;
	int right_1 = g_TimingCurtain1;
	int if_2 = left_1 != right_1;
	if (if_2)
	{
		Ft_Esd_Toggle_Toggle(&context->ESD_Toggle_1);
	}
	else
	{
	}
	ft_bool_t left_2 = context->ESD_Toggle_1_1.State;
	int right_2 = g_TimingCurtain2;
	int if_3 = left_2 != right_2;
	if (if_3)
	{
		Ft_Esd_Toggle_Toggle(&context->ESD_Toggle_1_1);
	}
	else
	{
	}
}

void Usr_CurtainTimingPage_ESD_Image_Button_Pushed__Signal(void *c)
{
	Usr_CurtainTimingPage *context = (Usr_CurtainTimingPage *)c;
	void *owner = context->Owner;
	context->BackPushed(owner);
}

void Usr_CurtainTimingPage_ESD_Toggle_1_1_1_Toggled__Signal(void *c)
{
	Usr_CurtainTimingPage *context = (Usr_CurtainTimingPage *)c;
	void *owner = context->Owner;
	ft_bool_t set_variable_2_1_1_1 = context->ESD_Toggle_1_1_1.State;
	g_TimingCurtain3 = set_variable_2_1_1_1;
}

void Usr_CurtainTimingPage_ESD_Toggle_1_1_Toggled__Signal(void *c)
{
	Usr_CurtainTimingPage *context = (Usr_CurtainTimingPage *)c;
	void *owner = context->Owner;
	ft_bool_t set_variable_2_1_1 = context->ESD_Toggle_1_1.State;
	g_TimingCurtain2 = set_variable_2_1_1;
}

void Usr_CurtainTimingPage_ESD_Toggle_1_Toggled__Signal(void *c)
{
	Usr_CurtainTimingPage *context = (Usr_CurtainTimingPage *)c;
	void *owner = context->Owner;
	ft_bool_t set_variable_2_1 = context->ESD_Toggle_1.State;
	g_TimingCurtain1 = set_variable_2_1;
}


/* end of file */
