/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_AirConWidget
C Source
*/

#include "Usr_AirConWidget.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);

static int Usr_AirConWidget_ESD_Line_Widget_1_2_linewidth__Property(void *context);
static ft_argb32_t Usr_AirConWidget_ESD_Line_Widget_1_2_color__Property(void *context) { return 0xff00aaffUL; }
static int Usr_AirConWidget_ESD_Line_Widget_1_1_linewidth__Property(void *context);
static ft_argb32_t Usr_AirConWidget_ESD_Line_Widget_1_1_color__Property(void *context) { return 0xff00aaffUL; }
static int Usr_AirConWidget_ESD_Line_Widget_1_linewidth__Property(void *context);
static ft_argb32_t Usr_AirConWidget_ESD_Line_Widget_1_color__Property(void *context) { return 0xff00aaffUL; }
static int Usr_AirConWidget_ESD_Line_Widget_linewidth__Property(void *context);
static ft_argb32_t Usr_AirConWidget_ESD_Line_Widget_color__Property(void *context) { return 0xff00aaffUL; }
static ft_int32_t Usr_AirConWidget_ESD_Rectangle_Widget_2_Radius__Property(void *context);
static ft_argb32_t Usr_AirConWidget_ESD_Rectangle_Widget_2_Color__Property(void *context) { return 0xffd1e3ebUL; }
static ft_int32_t Usr_AirConWidget_AirConCase_Radius__Property(void *context);

static Ft_Esd_WidgetSlots s_Usr_AirConWidget__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Usr_AirConWidget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_AirConWidget_End,
};


void Usr_AirConWidget__Fixed_Positioning__Initializer(Usr_AirConWidget *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Positioning;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_AirConWidget__ESD_Line_Widget_1_2__Initializer(Usr_AirConWidget *context)
{
	Ft_Esd_Line *object = (Ft_Esd_Line *)&context->ESD_Line_Widget_1_2;
	Ft_Esd_Line__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 74;
	object->Widget.LocalY = 54;
	object->Widget.LocalWidth = -7;
	object->Widget.LocalHeight = 18;
	object->linewidth = Usr_AirConWidget_ESD_Line_Widget_1_2_linewidth__Property;
	object->color = Usr_AirConWidget_ESD_Line_Widget_1_2_color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void Usr_AirConWidget__ESD_Line_Widget_1_1__Initializer(Usr_AirConWidget *context)
{
	Ft_Esd_Line *object = (Ft_Esd_Line *)&context->ESD_Line_Widget_1_1;
	Ft_Esd_Line__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 56;
	object->Widget.LocalY = 54;
	object->Widget.LocalWidth = -7;
	object->Widget.LocalHeight = 18;
	object->linewidth = Usr_AirConWidget_ESD_Line_Widget_1_1_linewidth__Property;
	object->color = Usr_AirConWidget_ESD_Line_Widget_1_1_color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void Usr_AirConWidget__ESD_Line_Widget_1__Initializer(Usr_AirConWidget *context)
{
	Ft_Esd_Line *object = (Ft_Esd_Line *)&context->ESD_Line_Widget_1;
	Ft_Esd_Line__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 40;
	object->Widget.LocalY = 54;
	object->Widget.LocalWidth = -7;
	object->Widget.LocalHeight = 18;
	object->linewidth = Usr_AirConWidget_ESD_Line_Widget_1_linewidth__Property;
	object->color = Usr_AirConWidget_ESD_Line_Widget_1_color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void Usr_AirConWidget__ESD_Line_Widget__Initializer(Usr_AirConWidget *context)
{
	Ft_Esd_Line *object = (Ft_Esd_Line *)&context->ESD_Line_Widget;
	Ft_Esd_Line__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 23;
	object->Widget.LocalY = 53;
	object->Widget.LocalWidth = -7;
	object->Widget.LocalHeight = 18;
	object->linewidth = Usr_AirConWidget_ESD_Line_Widget_linewidth__Property;
	object->color = Usr_AirConWidget_ESD_Line_Widget_color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void Usr_AirConWidget__ESD_Rectangle_Widget_2__Initializer(Usr_AirConWidget *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget_2;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 15;
	object->Widget.LocalY = 31;
	object->Widget.LocalWidth = 64;
	object->Widget.LocalHeight = 17;
	object->Radius = Usr_AirConWidget_ESD_Rectangle_Widget_2_Radius__Property;
	object->Color = Usr_AirConWidget_ESD_Rectangle_Widget_2_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void Usr_AirConWidget__ESD_Circle__1__Initializer(Usr_AirConWidget *context)
{
	Ft_Esd_Circle *object = (Ft_Esd_Circle *)&context->ESD_Circle__1;
	Ft_Esd_Circle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 41;
	object->Widget.LocalY = 15;
	object->Widget.LocalWidth = 10;
	object->Widget.LocalHeight = 10;
	object->Color = 0xffd1e3ebUL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void Usr_AirConWidget__ESD_Circle___Initializer(Usr_AirConWidget *context)
{
	Ft_Esd_Circle *object = (Ft_Esd_Circle *)&context->ESD_Circle_;
	Ft_Esd_Circle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 22;
	object->Widget.LocalY = 15;
	object->Widget.LocalWidth = 10;
	object->Widget.LocalHeight = 10;
	object->Color = 0xffd1e3ebUL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void Usr_AirConWidget__AirConCase__Initializer(Usr_AirConWidget *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->AirConCase;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 95;
	object->Widget.LocalHeight = 48;
	object->Radius = Usr_AirConWidget_AirConCase_Radius__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void Usr_AirConWidget__Initializer(Usr_AirConWidget *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_AirConWidget_CLASSID;
	context->Widget.Slots = &s_Usr_AirConWidget__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 1;
	context->Widget.LocalWidth = 107;
	context->Widget.LocalHeight = 84;
	context->On = 1;
	Usr_AirConWidget__Fixed_Positioning__Initializer(context);
	Usr_AirConWidget__ESD_Line_Widget_1_2__Initializer(context);
	Usr_AirConWidget__ESD_Line_Widget_1_1__Initializer(context);
	Usr_AirConWidget__ESD_Line_Widget_1__Initializer(context);
	Usr_AirConWidget__ESD_Line_Widget__Initializer(context);
	Usr_AirConWidget__ESD_Rectangle_Widget_2__Initializer(context);
	Usr_AirConWidget__ESD_Circle__1__Initializer(context);
	Usr_AirConWidget__ESD_Circle___Initializer(context);
	Usr_AirConWidget__AirConCase__Initializer(context);
}

void Usr_AirConWidget_Update(Usr_AirConWidget *context)
{
	void *owner = context->Owner;
	bool update_variable = context->On;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ESD_Line_Widget_1_2, update_variable);
	ft_int16_t left_4 = context->Widget.GlobalWidth;
	ft_int16_t left_6 = context->Widget.GlobalWidth;
	int right_1 = 2L;
	int left_5 = left_6 * right_1;
	int right_2 = 3L;
	int right = left_5 / right_2;
	int left_3 = left_4 - right;
	int right_3 = 2L;
	int left_2 = left_3 / right_3;
	ft_int16_t left_9 = context->Widget.GlobalWidth;
	int right_5 = 2L;
	int left_8 = left_9 * right_5;
	int right_6 = 3L;
	int left_7 = left_8 / right_6;
	int right_7 = 3L;
	int right_4 = left_7 / right_7;
	int left_1 = left_2 + right_4;
	ft_int16_t left_12 = context->Widget.GlobalWidth;
	int right_9 = 2L;
	int left_11 = left_12 * right_9;
	int right_10 = 3L;
	int left_10 = left_11 / right_10;
	int right_11 = 3L;
	int right_8 = left_10 / right_11;
	int left = left_1 + right_8;
	ft_int16_t left_15 = context->Widget.GlobalWidth;
	int right_13 = 2L;
	int left_14 = left_15 * right_13;
	int right_14 = 3L;
	int left_13 = left_14 / right_14;
	int right_15 = 3L;
	int right_12 = left_13 / right_15;
	int update_variable_1 = left + right_12;
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ESD_Line_Widget_1_2, update_variable_1);
	ft_int16_t left_16 = context->Widget.GlobalHeight;
	int right_16 = 4L;
	int update_variable_2 = left_16 + right_16;
	Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->ESD_Line_Widget_1_2, update_variable_2);
	ft_int16_t left_17 = context->Widget.GlobalHeight;
	int right_17 = 4L;
	int update_variable_3 = left_17 / right_17;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->ESD_Line_Widget_1_2, update_variable_3);
	bool update_variable_4 = context->On;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ESD_Line_Widget_1_1, update_variable_4);
	ft_int16_t left_21 = context->Widget.GlobalWidth;
	ft_int16_t left_23 = context->Widget.GlobalWidth;
	int right_19 = 2L;
	int left_22 = left_23 * right_19;
	int right_20 = 3L;
	int right_18 = left_22 / right_20;
	int left_20 = left_21 - right_18;
	int right_21 = 2L;
	int left_19 = left_20 / right_21;
	ft_int16_t left_26 = context->Widget.GlobalWidth;
	int right_23 = 2L;
	int left_25 = left_26 * right_23;
	int right_24 = 3L;
	int left_24 = left_25 / right_24;
	int right_25 = 3L;
	int right_22 = left_24 / right_25;
	int left_18 = left_19 + right_22;
	ft_int16_t left_29 = context->Widget.GlobalWidth;
	int right_27 = 2L;
	int left_28 = left_29 * right_27;
	int right_28 = 3L;
	int left_27 = left_28 / right_28;
	int right_29 = 3L;
	int right_26 = left_27 / right_29;
	int update_variable_5 = left_18 + right_26;
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ESD_Line_Widget_1_1, update_variable_5);
	ft_int16_t left_30 = context->Widget.GlobalHeight;
	int right_30 = 4L;
	int update_variable_6 = left_30 + right_30;
	Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->ESD_Line_Widget_1_1, update_variable_6);
	ft_int16_t left_31 = context->Widget.GlobalHeight;
	int right_31 = 4L;
	int update_variable_7 = left_31 / right_31;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->ESD_Line_Widget_1_1, update_variable_7);
	bool update_variable_8 = context->On;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ESD_Line_Widget_1, update_variable_8);
	ft_int16_t left_34 = context->Widget.GlobalWidth;
	ft_int16_t left_36 = context->Widget.GlobalWidth;
	int right_33 = 2L;
	int left_35 = left_36 * right_33;
	int right_34 = 3L;
	int right_32 = left_35 / right_34;
	int left_33 = left_34 - right_32;
	int right_35 = 2L;
	int left_32 = left_33 / right_35;
	ft_int16_t left_39 = context->Widget.GlobalWidth;
	int right_37 = 2L;
	int left_38 = left_39 * right_37;
	int right_38 = 3L;
	int left_37 = left_38 / right_38;
	int right_39 = 3L;
	int right_36 = left_37 / right_39;
	int update_variable_9 = left_32 + right_36;
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ESD_Line_Widget_1, update_variable_9);
	ft_int16_t left_40 = context->Widget.GlobalHeight;
	int right_40 = 4L;
	int update_variable_10 = left_40 + right_40;
	Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->ESD_Line_Widget_1, update_variable_10);
	ft_int16_t left_41 = context->Widget.GlobalHeight;
	int right_41 = 4L;
	int update_variable_11 = left_41 / right_41;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->ESD_Line_Widget_1, update_variable_11);
	bool update_variable_12 = context->On;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ESD_Line_Widget, update_variable_12);
	ft_int16_t left_43 = context->Widget.GlobalWidth;
	ft_int16_t left_45 = context->Widget.GlobalWidth;
	int right_43 = 2L;
	int left_44 = left_45 * right_43;
	int right_44 = 3L;
	int right_42 = left_44 / right_44;
	int left_42 = left_43 - right_42;
	int right_45 = 2L;
	int update_variable_13 = left_42 / right_45;
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ESD_Line_Widget, update_variable_13);
	ft_int16_t left_46 = context->Widget.GlobalHeight;
	int right_46 = 4L;
	int update_variable_14 = left_46 + right_46;
	Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->ESD_Line_Widget, update_variable_14);
	ft_int16_t left_47 = context->Widget.GlobalHeight;
	int right_47 = 4L;
	int update_variable_15 = left_47 / right_47;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->ESD_Line_Widget, update_variable_15);
	ft_int16_t left_49 = context->Widget.GlobalWidth;
	ft_int16_t left_51 = context->Widget.GlobalWidth;
	int right_49 = 2L;
	int left_50 = left_51 * right_49;
	int right_50 = 3L;
	int right_48 = left_50 / right_50;
	int left_48 = left_49 - right_48;
	int right_51 = 2L;
	int update_variable_16 = left_48 / right_51;
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget_2, update_variable_16);
	ft_int16_t left_52 = context->Widget.GlobalHeight;
	ft_int16_t left_53 = context->Widget.GlobalHeight;
	int right_53 = 3L;
	int right_52 = left_53 / right_53;
	int update_variable_17 = left_52 - right_52;
	Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget_2, update_variable_17);
	ft_int16_t left_55 = context->Widget.GlobalWidth;
	int right_54 = 2L;
	int left_54 = left_55 * right_54;
	int right_55 = 3L;
	int update_variable_18 = left_54 / right_55;
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget_2, update_variable_18);
	ft_int16_t left_56 = context->Widget.GlobalHeight;
	int right_56 = 3L;
	int update_variable_19 = left_56 / right_56;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget_2, update_variable_19);
	ft_int16_t left_59 = context->Widget.GlobalWidth;
	ft_int16_t left_61 = context->Widget.GlobalWidth;
	int right_58 = 2L;
	int left_60 = left_61 * right_58;
	int right_59 = 3L;
	int right_57 = left_60 / right_59;
	int left_58 = left_59 - right_57;
	int right_60 = 2L;
	int left_57 = left_58 / right_60;
	ft_int16_t left_63 = context->Widget.GlobalHeight;
	int right_62 = 5L;
	int left_62 = left_63 / right_62;
	int right_63 = 2L;
	int right_61 = left_62 * right_63;
	int update_variable_20 = left_57 + right_61;
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ESD_Circle__1, update_variable_20);
	ft_int16_t left_64 = context->Widget.GlobalHeight;
	int right_64 = 5L;
	int update_variable_21 = left_64 / right_64;
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->ESD_Circle__1, update_variable_21);
	ft_int16_t left_65 = context->Widget.GlobalHeight;
	int right_65 = 5L;
	int update_variable_22 = left_65 / right_65;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->ESD_Circle__1, update_variable_22);
	ft_int16_t left_67 = context->Widget.GlobalWidth;
	ft_int16_t left_69 = context->Widget.GlobalWidth;
	int right_67 = 2L;
	int left_68 = left_69 * right_67;
	int right_68 = 3L;
	int right_66 = left_68 / right_68;
	int left_66 = left_67 - right_66;
	int right_69 = 2L;
	int update_variable_23 = left_66 / right_69;
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ESD_Circle_, update_variable_23);
	ft_int16_t left_70 = context->Widget.GlobalHeight;
	int right_70 = 5L;
	int update_variable_24 = left_70 / right_70;
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->ESD_Circle_, update_variable_24);
	ft_int16_t left_71 = context->Widget.GlobalHeight;
	int right_71 = 5L;
	int update_variable_25 = left_71 / right_71;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->ESD_Circle_, update_variable_25);
	ft_int16_t update_variable_26 = context->Widget.GlobalWidth;
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->AirConCase, update_variable_26);
	ft_int16_t update_variable_27 = context->Widget.GlobalHeight;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->AirConCase, update_variable_27);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Usr_AirConWidget_End(Usr_AirConWidget *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Positioning); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Line_Widget_1_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Line_Widget_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Line_Widget_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Line_Widget); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Circle__1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Circle_); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->AirConCase); 
}

int Usr_AirConWidget_ESD_Line_Widget_1_2_linewidth__Property(void *c)
{
	Usr_AirConWidget *context = (Usr_AirConWidget *)c;
	void *owner = context->Owner;
	ft_int16_t left_73 = context->Widget.GlobalHeight;
	int right_72 = 5L;
	int left_72 = left_73 / right_72;
	int right_73 = 3L;
	return left_72 / right_73;
}

int Usr_AirConWidget_ESD_Line_Widget_1_1_linewidth__Property(void *c)
{
	Usr_AirConWidget *context = (Usr_AirConWidget *)c;
	void *owner = context->Owner;
	ft_int16_t left_75 = context->Widget.GlobalHeight;
	int right_74 = 5L;
	int left_74 = left_75 / right_74;
	int right_75 = 3L;
	return left_74 / right_75;
}

int Usr_AirConWidget_ESD_Line_Widget_1_linewidth__Property(void *c)
{
	Usr_AirConWidget *context = (Usr_AirConWidget *)c;
	void *owner = context->Owner;
	ft_int16_t left_77 = context->Widget.GlobalHeight;
	int right_76 = 5L;
	int left_76 = left_77 / right_76;
	int right_77 = 3L;
	return left_76 / right_77;
}

int Usr_AirConWidget_ESD_Line_Widget_linewidth__Property(void *c)
{
	Usr_AirConWidget *context = (Usr_AirConWidget *)c;
	void *owner = context->Owner;
	ft_int16_t left_79 = context->Widget.GlobalHeight;
	int right_78 = 5L;
	int left_78 = left_79 / right_78;
	int right_79 = 3L;
	return left_78 / right_79;
}

ft_int32_t Usr_AirConWidget_ESD_Rectangle_Widget_2_Radius__Property(void *c)
{
	Usr_AirConWidget *context = (Usr_AirConWidget *)c;
	void *owner = context->Owner;
	ft_int16_t left_81 = context->Widget.GlobalHeight;
	int right_80 = 3L;
	int left_80 = left_81 / right_80;
	int right_81 = 5L;
	return left_80 / right_81;
}

ft_int32_t Usr_AirConWidget_AirConCase_Radius__Property(void *c)
{
	Usr_AirConWidget *context = (Usr_AirConWidget *)c;
	void *owner = context->Owner;
	ft_int16_t left_82 = context->Widget.GlobalHeight;
	int right_82 = 5L;
	return left_82 / right_82;
}


/* end of file */
