/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_LightPage
C Source
*/

#include "Usr_LightPage.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);

static ft_argb32_t Usr_LightPage_ESD_Touch_Panel_1_1_1_Color__Property(void *context) { return 0x181818UL; }
static int Usr_LightPage_ESD_Touch_Panel_1_1_1_Radius__Property(void *context) { return 10L; }
static ft_argb32_t Usr_LightPage_ESD_Touch_Panel_1_1_Color__Property(void *context) { return 0x181818UL; }
static int Usr_LightPage_ESD_Touch_Panel_1_1_Radius__Property(void *context) { return 10L; }
static ft_argb32_t Usr_LightPage_ESD_Touch_Panel_1_Color__Property(void *context) { return 0x181818UL; }
static int Usr_LightPage_ESD_Touch_Panel_1_Radius__Property(void *context) { return 10L; }
static ft_argb32_t Usr_LightPage_ESD_Touch_Panel_Color__Property(void *context) { return 0x181818UL; }
static int Usr_LightPage_ESD_Touch_Panel_Radius__Property(void *context) { return 10L; }
static Ft_Esd_BitmapCell Usr_LightPage_ESD_Image_2_1_1_1_1_BitmapCell__Property(void *context) { return light_page_on_0(); }
static Ft_Esd_BitmapCell Usr_LightPage_ESD_Image_2_1_1_1_BitmapCell__Property(void *context) { return light_page_on_0(); }
static Ft_Esd_BitmapCell Usr_LightPage_ESD_Image_2_2_1_1_BitmapCell__Property(void *context) { return light_case_level1_0(); }
static Ft_Esd_BitmapCell Usr_LightPage_ESD_Image_2_1_1_BitmapCell__Property(void *context) { return light_page_on_0(); }
static Ft_Esd_BitmapCell Usr_LightPage_ESD_Image_2_2_1_BitmapCell__Property(void *context) { return light_case_level1_0(); }
static Ft_Esd_BitmapCell Usr_LightPage_ESD_Image_2_1_BitmapCell__Property(void *context) { return light_page_on_0(); }
static Ft_Esd_BitmapCell Usr_LightPage_ESD_Image_2_2_BitmapCell__Property(void *context) { return light_case_level1_0(); }
static Ft_Esd_BitmapCell Usr_LightPage_ESD_Image_2_BitmapCell__Property(void *context) { return light_case_level1_0(); }
static uint8_t Usr_LightPage_ESD_Label_1_1_1_Font__Property(void *context) { return 28; }
static const char * Usr_LightPage_ESD_Label_1_1_1_Text__Property(void *context) { return "Warm"; }
static ft_uint16_t Usr_LightPage_ESD_Label_1_1_1_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static uint8_t Usr_LightPage_ESD_Label_1_1_Font__Property(void *context) { return 28; }
static const char * Usr_LightPage_ESD_Label_1_1_Text__Property(void *context) { return "Celing"; }
static ft_uint16_t Usr_LightPage_ESD_Label_1_1_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static uint8_t Usr_LightPage_ESD_Label_1_Font__Property(void *context) { return 28; }
static const char * Usr_LightPage_ESD_Label_1_Text__Property(void *context) { return "Livingroom"; }
static ft_uint16_t Usr_LightPage_ESD_Label_1_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static uint8_t Usr_LightPage_ESD_Label_Font__Property(void *context) { return 28; }
static const char * Usr_LightPage_ESD_Label_Text__Property(void *context) { return "Bedroom"; }
static ft_uint16_t Usr_LightPage_ESD_Label_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static Ft_Esd_BitmapCell Usr_LightPage_ESD_Image_Button_1_1_1_BitmapNormal__Property(void *context) { return power_white_icon_0(); }
static Ft_Esd_BitmapCell Usr_LightPage_ESD_Image_Button_1_1_BitmapNormal__Property(void *context) { return power_white_icon_0(); }
static Ft_Esd_BitmapCell Usr_LightPage_ESD_Image_Button_1_BitmapNormal__Property(void *context) { return power_white_icon_0(); }
static Ft_Esd_BitmapCell Usr_LightPage_ESD_Image_Button_BitmapNormal__Property(void *context) { return power_white_icon_0(); }
static ft_int32_t Usr_LightPage_Rectangle_Light_3_Radius__Property(void *context) { return 10L; }
static ft_argb32_t Usr_LightPage_Rectangle_Light_3_Color__Property(void *context) { return 0x82feb300UL; }
static ft_int32_t Usr_LightPage_Rectangle_Light_2_Radius__Property(void *context) { return 10L; }
static ft_argb32_t Usr_LightPage_Rectangle_Light_2_Color__Property(void *context) { return 0x3ae8f1f9UL; }
static ft_int32_t Usr_LightPage_Rectangle_Light_1_Radius__Property(void *context) { return 10L; }
static ft_argb32_t Usr_LightPage_Rectangle_Light_1_Color__Property(void *context) { return 0x3ae8f1f9UL; }
static ft_int32_t Usr_LightPage_Rectangle_Light_Radius__Property(void *context) { return 10L; }
static ft_argb32_t Usr_LightPage_Rectangle_Light_Color__Property(void *context) { return 0x3ae8f1f9UL; }
static uint8_t Usr_LightPage_Light_Control_Label_Font__Property(void *context) { return 30; }
static const char * Usr_LightPage_Light_Control_Label_Text__Property(void *context) { return "Light Control"; }
static ft_uint16_t Usr_LightPage_Light_Control_Label_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_int32_t Usr_LightPage_ESD_Rectangle_Widget_4_Radius__Property(void *context) { return 24L; }
static ft_argb32_t Usr_LightPage_ESD_Rectangle_Widget_4_Color__Property(void *context) { return 0x59000000UL; }

static Ft_Esd_WidgetSlots s_Usr_LightPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_LightPage_End,
};

static void Usr_LightPage_ESD_Touch_Panel_1_1_1_Tap__Signal(void *context);
static void Usr_LightPage_ESD_Touch_Panel_1_1_Tap__Signal(void *context);
static void Usr_LightPage_ESD_Touch_Panel_1_Tap__Signal(void *context);
static void Usr_LightPage_ESD_Touch_Panel_Tap__Signal(void *context);

void Usr_LightPage__Fixed_Position__Initializer(Usr_LightPage *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_LightPage__ESD_Touch_Panel_1_1_1__Initializer(Usr_LightPage *context)
{
	Ft_Esd_TouchPanel *object = (Ft_Esd_TouchPanel *)&context->ESD_Touch_Panel_1_1_1;
	Ft_Esd_TouchPanel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 93;
	object->Widget.LocalY = 338;
	object->Widget.LocalWidth = 294;
	object->Widget.LocalHeight = 56;
	object->Color = Usr_LightPage_ESD_Touch_Panel_1_1_1_Color__Property;
	object->Radius = Usr_LightPage_ESD_Touch_Panel_1_1_1_Radius__Property;
	object->Tap = Usr_LightPage_ESD_Touch_Panel_1_1_1_Tap__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__ESD_Touch_Panel_1_1__Initializer(Usr_LightPage *context)
{
	Ft_Esd_TouchPanel *object = (Ft_Esd_TouchPanel *)&context->ESD_Touch_Panel_1_1;
	Ft_Esd_TouchPanel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 92;
	object->Widget.LocalY = 262;
	object->Widget.LocalWidth = 294;
	object->Widget.LocalHeight = 56;
	object->Color = Usr_LightPage_ESD_Touch_Panel_1_1_Color__Property;
	object->Radius = Usr_LightPage_ESD_Touch_Panel_1_1_Radius__Property;
	object->Tap = Usr_LightPage_ESD_Touch_Panel_1_1_Tap__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__ESD_Touch_Panel_1__Initializer(Usr_LightPage *context)
{
	Ft_Esd_TouchPanel *object = (Ft_Esd_TouchPanel *)&context->ESD_Touch_Panel_1;
	Ft_Esd_TouchPanel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 94;
	object->Widget.LocalY = 188;
	object->Widget.LocalWidth = 294;
	object->Widget.LocalHeight = 56;
	object->Color = Usr_LightPage_ESD_Touch_Panel_1_Color__Property;
	object->Radius = Usr_LightPage_ESD_Touch_Panel_1_Radius__Property;
	object->Tap = Usr_LightPage_ESD_Touch_Panel_1_Tap__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__ESD_Touch_Panel__Initializer(Usr_LightPage *context)
{
	Ft_Esd_TouchPanel *object = (Ft_Esd_TouchPanel *)&context->ESD_Touch_Panel;
	Ft_Esd_TouchPanel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 93;
	object->Widget.LocalY = 116;
	object->Widget.LocalWidth = 294;
	object->Widget.LocalHeight = 56;
	object->Color = Usr_LightPage_ESD_Touch_Panel_Color__Property;
	object->Radius = Usr_LightPage_ESD_Touch_Panel_Radius__Property;
	object->Tap = Usr_LightPage_ESD_Touch_Panel_Tap__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__ESD_Image_2_1_1_1_1__Initializer(Usr_LightPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_2_1_1_1_1;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 116;
	object->Widget.LocalY = 368;
	object->Widget.LocalWidth = 51;
	object->Widget.LocalHeight = 51;
	object->Color = 0xffffff00UL;
	object->BitmapCell = Usr_LightPage_ESD_Image_2_1_1_1_1_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__ESD_Image_2_1_1_1__Initializer(Usr_LightPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_2_1_1_1;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 116;
	object->Widget.LocalY = 292;
	object->Widget.LocalWidth = 51;
	object->Widget.LocalHeight = 51;
	object->Color = 0xffffff00UL;
	object->BitmapCell = Usr_LightPage_ESD_Image_2_1_1_1_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__ESD_Image_2_2_1_1__Initializer(Usr_LightPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_2_2_1_1;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 110;
	object->Widget.LocalY = 345;
	object->Widget.LocalWidth = 51;
	object->Widget.LocalHeight = 51;
	object->BitmapCell = Usr_LightPage_ESD_Image_2_2_1_1_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__ESD_Image_2_1_1__Initializer(Usr_LightPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_2_1_1;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 116;
	object->Widget.LocalY = 211;
	object->Widget.LocalWidth = 51;
	object->Widget.LocalHeight = 51;
	object->Color = 0xffffff00UL;
	object->BitmapCell = Usr_LightPage_ESD_Image_2_1_1_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__ESD_Image_2_2_1__Initializer(Usr_LightPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_2_2_1;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 110;
	object->Widget.LocalY = 269;
	object->Widget.LocalWidth = 51;
	object->Widget.LocalHeight = 51;
	object->BitmapCell = Usr_LightPage_ESD_Image_2_2_1_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__ESD_Image_2_1__Initializer(Usr_LightPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_2_1;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 113;
	object->Widget.LocalY = 139;
	object->Widget.LocalWidth = 51;
	object->Widget.LocalHeight = 51;
	object->Color = 0xffffff00UL;
	object->BitmapCell = Usr_LightPage_ESD_Image_2_1_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__ESD_Image_2_2__Initializer(Usr_LightPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_2_2;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 110;
	object->Widget.LocalY = 188;
	object->Widget.LocalWidth = 51;
	object->Widget.LocalHeight = 51;
	object->BitmapCell = Usr_LightPage_ESD_Image_2_2_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__ESD_Image_2__Initializer(Usr_LightPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_2;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 107;
	object->Widget.LocalY = 116;
	object->Widget.LocalWidth = 51;
	object->Widget.LocalHeight = 51;
	object->BitmapCell = Usr_LightPage_ESD_Image_2_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__ESD_Label_1_1_1__Initializer(Usr_LightPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_1_1_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 150;
	object->Widget.LocalY = 353;
	object->Widget.LocalWidth = 180;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_LightPage_ESD_Label_1_1_1_Font__Property;
	object->Text = Usr_LightPage_ESD_Label_1_1_1_Text__Property;
	object->AlignX = Usr_LightPage_ESD_Label_1_1_1_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__ESD_Label_1_1__Initializer(Usr_LightPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_1_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 150;
	object->Widget.LocalY = 277;
	object->Widget.LocalWidth = 180;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_LightPage_ESD_Label_1_1_Font__Property;
	object->Text = Usr_LightPage_ESD_Label_1_1_Text__Property;
	object->AlignX = Usr_LightPage_ESD_Label_1_1_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__ESD_Label_1__Initializer(Usr_LightPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 150;
	object->Widget.LocalY = 200;
	object->Widget.LocalWidth = 180;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_LightPage_ESD_Label_1_Font__Property;
	object->Text = Usr_LightPage_ESD_Label_1_Text__Property;
	object->AlignX = Usr_LightPage_ESD_Label_1_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__ESD_Label__Initializer(Usr_LightPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 150;
	object->Widget.LocalY = 131;
	object->Widget.LocalWidth = 180;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_LightPage_ESD_Label_Font__Property;
	object->Text = Usr_LightPage_ESD_Label_Text__Property;
	object->AlignX = Usr_LightPage_ESD_Label_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__ESD_Image_Button_1_1_1__Initializer(Usr_LightPage *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button_1_1_1;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 327;
	object->Widget.LocalY = 345;
	object->Widget.LocalWidth = 48;
	object->Widget.LocalHeight = 48;
	object->BitmapNormal = Usr_LightPage_ESD_Image_Button_1_1_1_BitmapNormal__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__ESD_Image_Button_1_1__Initializer(Usr_LightPage *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button_1_1;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 327;
	object->Widget.LocalY = 270;
	object->Widget.LocalWidth = 48;
	object->Widget.LocalHeight = 48;
	object->BitmapNormal = Usr_LightPage_ESD_Image_Button_1_1_BitmapNormal__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__ESD_Image_Button_1__Initializer(Usr_LightPage *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button_1;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 327;
	object->Widget.LocalY = 190;
	object->Widget.LocalWidth = 48;
	object->Widget.LocalHeight = 48;
	object->BitmapNormal = Usr_LightPage_ESD_Image_Button_1_BitmapNormal__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__ESD_Image_Button__Initializer(Usr_LightPage *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 326;
	object->Widget.LocalY = 119;
	object->Widget.LocalWidth = 48;
	object->Widget.LocalHeight = 48;
	object->BitmapNormal = Usr_LightPage_ESD_Image_Button_BitmapNormal__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__Rectangle_Light_3__Initializer(Usr_LightPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->Rectangle_Light_3;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 93;
	object->Widget.LocalY = 340;
	object->Widget.LocalWidth = 294;
	object->Widget.LocalHeight = 54;
	object->Radius = Usr_LightPage_Rectangle_Light_3_Radius__Property;
	object->Color = Usr_LightPage_Rectangle_Light_3_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__Rectangle_Light_2__Initializer(Usr_LightPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->Rectangle_Light_2;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 93;
	object->Widget.LocalY = 266;
	object->Widget.LocalWidth = 294;
	object->Widget.LocalHeight = 54;
	object->Radius = Usr_LightPage_Rectangle_Light_2_Radius__Property;
	object->Color = Usr_LightPage_Rectangle_Light_2_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__Rectangle_Light_1__Initializer(Usr_LightPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->Rectangle_Light_1;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 93;
	object->Widget.LocalY = 190;
	object->Widget.LocalWidth = 294;
	object->Widget.LocalHeight = 54;
	object->Radius = Usr_LightPage_Rectangle_Light_1_Radius__Property;
	object->Color = Usr_LightPage_Rectangle_Light_1_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__Rectangle_Light__Initializer(Usr_LightPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->Rectangle_Light;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 93;
	object->Widget.LocalY = 116;
	object->Widget.LocalWidth = 294;
	object->Widget.LocalHeight = 54;
	object->Radius = Usr_LightPage_Rectangle_Light_Radius__Property;
	object->Color = Usr_LightPage_Rectangle_Light_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__Light_Control_Label__Initializer(Usr_LightPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Light_Control_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 125;
	object->Widget.LocalY = 50;
	object->Widget.LocalWidth = 234;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_LightPage_Light_Control_Label_Font__Property;
	object->Text = Usr_LightPage_Light_Control_Label_Text__Property;
	object->AlignX = Usr_LightPage_Light_Control_Label_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__ESD_Rectangle_Widget_4__Initializer(Usr_LightPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget_4;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 123;
	object->Widget.LocalY = 45;
	object->Widget.LocalWidth = 234;
	object->Widget.LocalHeight = 48;
	object->Radius = Usr_LightPage_ESD_Rectangle_Widget_4_Radius__Property;
	object->Color = Usr_LightPage_ESD_Rectangle_Widget_4_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LightPage__Initializer(Usr_LightPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_LightPage_CLASSID;
	context->Widget.Slots = &s_Usr_LightPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->ButtonPushed = Esd_Noop;
	context->SubPage = 0L;
	Usr_LightPage__Fixed_Position__Initializer(context);
	Usr_LightPage__ESD_Touch_Panel_1_1_1__Initializer(context);
	Usr_LightPage__ESD_Touch_Panel_1_1__Initializer(context);
	Usr_LightPage__ESD_Touch_Panel_1__Initializer(context);
	Usr_LightPage__ESD_Touch_Panel__Initializer(context);
	Usr_LightPage__ESD_Image_2_1_1_1_1__Initializer(context);
	Usr_LightPage__ESD_Image_2_1_1_1__Initializer(context);
	Usr_LightPage__ESD_Image_2_2_1_1__Initializer(context);
	Usr_LightPage__ESD_Image_2_1_1__Initializer(context);
	Usr_LightPage__ESD_Image_2_2_1__Initializer(context);
	Usr_LightPage__ESD_Image_2_1__Initializer(context);
	Usr_LightPage__ESD_Image_2_2__Initializer(context);
	Usr_LightPage__ESD_Image_2__Initializer(context);
	Usr_LightPage__ESD_Label_1_1_1__Initializer(context);
	Usr_LightPage__ESD_Label_1_1__Initializer(context);
	Usr_LightPage__ESD_Label_1__Initializer(context);
	Usr_LightPage__ESD_Label__Initializer(context);
	Usr_LightPage__ESD_Image_Button_1_1_1__Initializer(context);
	Usr_LightPage__ESD_Image_Button_1_1__Initializer(context);
	Usr_LightPage__ESD_Image_Button_1__Initializer(context);
	Usr_LightPage__ESD_Image_Button__Initializer(context);
	Usr_LightPage__Rectangle_Light_3__Initializer(context);
	Usr_LightPage__Rectangle_Light_2__Initializer(context);
	Usr_LightPage__Rectangle_Light_1__Initializer(context);
	Usr_LightPage__Rectangle_Light__Initializer(context);
	Usr_LightPage__Light_Control_Label__Initializer(context);
	Usr_LightPage__ESD_Rectangle_Widget_4__Initializer(context);
}

void Usr_LightPage_End(Usr_LightPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Touch_Panel_1_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Touch_Panel_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Touch_Panel_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Touch_Panel); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_2_1_1_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_2_1_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_2_2_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_2_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_2_2_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_2_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_2_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_1_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button_1_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Rectangle_Light_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Rectangle_Light_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Rectangle_Light_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Rectangle_Light); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Light_Control_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget_4); 
}

int Usr_LightPage_CurrentPage(Usr_LightPage *context)
{
	void *owner = context->Owner;
	return context->SubPage;
}

void Usr_LightPage_ESD_Touch_Panel_1_1_1_Tap__Signal(void *c)
{
	Usr_LightPage *context = (Usr_LightPage *)c;
	void *owner = context->Owner;
	int set_variable_1_1_1 = 14L;
	context->SubPage = set_variable_1_1_1;
	context->ButtonPushed(owner);
}

void Usr_LightPage_ESD_Touch_Panel_1_1_Tap__Signal(void *c)
{
	Usr_LightPage *context = (Usr_LightPage *)c;
	void *owner = context->Owner;
	int set_variable_1_1 = 13L;
	context->SubPage = set_variable_1_1;
	context->ButtonPushed(owner);
}

void Usr_LightPage_ESD_Touch_Panel_1_Tap__Signal(void *c)
{
	Usr_LightPage *context = (Usr_LightPage *)c;
	void *owner = context->Owner;
	int set_variable_1 = 12L;
	context->SubPage = set_variable_1;
	context->ButtonPushed(owner);
}

void Usr_LightPage_ESD_Touch_Panel_Tap__Signal(void *c)
{
	Usr_LightPage *context = (Usr_LightPage *)c;
	void *owner = context->Owner;
	int set_variable = 11L;
	context->SubPage = set_variable;
	context->ButtonPushed(owner);
}


/* end of file */
