/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_HeatSettingPage
C Source
*/

#include "Usr_HeatSettingPage.h"

#include "Esd_Context.h"
#include "Usr_GlobalVariables.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);

static uint8_t Usr_HeatSettingPage_ESD_Numeric_Label_Font__Property(void *context) { return 31; }
static ft_uint16_t Usr_HeatSettingPage_ESD_Numeric_Label_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_int32_t Usr_HeatSettingPage_ESD_Numeric_Label_Value__Property(void *context);
static uint8_t Usr_HeatSettingPage_ESD_Push_Button_1_1_Font__Property(void *context) { return 31; }
static const char * Usr_HeatSettingPage_ESD_Push_Button_1_1_Text__Property(void *context) { return "-"; }
static uint8_t Usr_HeatSettingPage_ESD_Push_Button_1_Font__Property(void *context) { return 31; }
static const char * Usr_HeatSettingPage_ESD_Push_Button_1_Text__Property(void *context) { return "+"; }
static ft_uint8_t Usr_HeatSettingPage_ESD_Image_Button_MinAlpha__Property(void *context) { return 0; }
static Ft_Esd_BitmapCell Usr_HeatSettingPage_ESD_Image_Button_BitmapNormal__Property(void *context) { return return_circle_64_0(); }
static uint8_t Usr_HeatSettingPage_ESD_Label_1_Font__Property(void *context) { return 29; }
static const char * Usr_HeatSettingPage_ESD_Label_1_Text__Property(void *context) { return "Set temprature:"; }
static uint8_t Usr_HeatSettingPage_ESD_Label_Font__Property(void *context) { return 29; }
static const char * Usr_HeatSettingPage_ESD_Label_Text__Property(void *context) { return "Indoor temprature:"; }
static uint8_t Usr_HeatSettingPage_ESD_Label_2_Font__Property(void *context) { return 31; }
static const char * Usr_HeatSettingPage_ESD_Label_2_Text__Property(void *context) { return "23"; }
static ft_int32_t Usr_HeatSettingPage_Rectangle_Light_Radius__Property(void *context) { return 10L; }
static ft_argb32_t Usr_HeatSettingPage_Rectangle_Light_Color__Property(void *context) { return 0x3ae8f1f9UL; }
static ft_int32_t Usr_HeatSettingPage_Rectangle_Light_1_Radius__Property(void *context) { return 10L; }
static ft_argb32_t Usr_HeatSettingPage_Rectangle_Light_1_Color__Property(void *context) { return 0x3ae8f1f9UL; }
static uint8_t Usr_HeatSettingPage_ESD_Label_2_1_Font__Property(void *context) { return 29; }
static const char * Usr_HeatSettingPage_ESD_Label_2_1_Text__Property(void *context) { return "Setting"; }
static ft_uint16_t Usr_HeatSettingPage_ESD_Label_2_1_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_int32_t Usr_HeatSettingPage_ESD_Rectangle_Widget_4_Radius__Property(void *context) { return 24L; }
static ft_argb32_t Usr_HeatSettingPage_ESD_Rectangle_Widget_4_Color__Property(void *context) { return 0x59000000UL; }
static ft_argb32_t Usr_HeatSettingPage_ESD_Rectangle_Widget_Color__Property(void *context) { return 0xff000000UL; }

static Ft_Esd_WidgetSlots s_Usr_HeatSettingPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_HeatSettingPage_End,
};

static void Usr_HeatSettingPage_ESD_Push_Button_1_1_Pushed__Signal(void *context);
static void Usr_HeatSettingPage_ESD_Push_Button_1_Pushed__Signal(void *context);
static void Usr_HeatSettingPage_ESD_Image_Button_Pushed__Signal(void *context);

void Usr_HeatSettingPage__Fixed_Position__Initializer(Usr_HeatSettingPage *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_HeatSettingPage__ESD_Numeric_Label__Initializer(Usr_HeatSettingPage *context)
{
	Ft_Esd_NumericLabel *object = (Ft_Esd_NumericLabel *)&context->ESD_Numeric_Label;
	Ft_Esd_NumericLabel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 182;
	object->Widget.LocalY = 287;
	object->Widget.LocalWidth = 106;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_HeatSettingPage_ESD_Numeric_Label_Font__Property;
	object->AlignX = Usr_HeatSettingPage_ESD_Numeric_Label_AlignX__Property;
	object->Value = Usr_HeatSettingPage_ESD_Numeric_Label_Value__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_HeatSettingPage__ESD_Push_Button_1_1__Initializer(Usr_HeatSettingPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->ESD_Push_Button_1_1;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 114;
	object->Widget.LocalY = 293;
	object->Widget.LocalWidth = 61;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_HeatSettingPage_ESD_Push_Button_1_1_Font__Property;
	object->Text = Usr_HeatSettingPage_ESD_Push_Button_1_1_Text__Property;
	object->Pushed = Usr_HeatSettingPage_ESD_Push_Button_1_1_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_HeatSettingPage__ESD_Push_Button_1__Initializer(Usr_HeatSettingPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->ESD_Push_Button_1;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 296;
	object->Widget.LocalY = 294;
	object->Widget.LocalWidth = 61;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_HeatSettingPage_ESD_Push_Button_1_Font__Property;
	object->Text = Usr_HeatSettingPage_ESD_Push_Button_1_Text__Property;
	object->Pushed = Usr_HeatSettingPage_ESD_Push_Button_1_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_HeatSettingPage__ESD_Image_Button__Initializer(Usr_HeatSettingPage *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 208;
	object->Widget.LocalY = 367;
	object->Widget.LocalWidth = 64;
	object->Widget.LocalHeight = 64;
	object->MinAlpha = Usr_HeatSettingPage_ESD_Image_Button_MinAlpha__Property;
	object->BitmapNormal = Usr_HeatSettingPage_ESD_Image_Button_BitmapNormal__Property;
	object->Pushed = Usr_HeatSettingPage_ESD_Image_Button_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_HeatSettingPage__ESD_Label_1__Initializer(Usr_HeatSettingPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 110;
	object->Widget.LocalY = 245;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_HeatSettingPage_ESD_Label_1_Font__Property;
	object->Text = Usr_HeatSettingPage_ESD_Label_1_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_HeatSettingPage__ESD_Label__Initializer(Usr_HeatSettingPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 110;
	object->Widget.LocalY = 125;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_HeatSettingPage_ESD_Label_Font__Property;
	object->Text = Usr_HeatSettingPage_ESD_Label_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_HeatSettingPage__ESD_Label_2__Initializer(Usr_HeatSettingPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 203;
	object->Widget.LocalY = 162;
	object->Widget.LocalWidth = 57;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_HeatSettingPage_ESD_Label_2_Font__Property;
	object->Text = Usr_HeatSettingPage_ESD_Label_2_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_HeatSettingPage__Rectangle_Light__Initializer(Usr_HeatSettingPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->Rectangle_Light;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 92;
	object->Widget.LocalY = 110;
	object->Widget.LocalWidth = 286;
	object->Widget.LocalHeight = 112;
	object->Radius = Usr_HeatSettingPage_Rectangle_Light_Radius__Property;
	object->Color = Usr_HeatSettingPage_Rectangle_Light_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_HeatSettingPage__Rectangle_Light_1__Initializer(Usr_HeatSettingPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->Rectangle_Light_1;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 92;
	object->Widget.LocalY = 237;
	object->Widget.LocalWidth = 285;
	object->Widget.LocalHeight = 116;
	object->Radius = Usr_HeatSettingPage_Rectangle_Light_1_Radius__Property;
	object->Color = Usr_HeatSettingPage_Rectangle_Light_1_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_HeatSettingPage__ESD_Label_2_1__Initializer(Usr_HeatSettingPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 140;
	object->Widget.LocalY = 53;
	object->Widget.LocalWidth = 200;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_HeatSettingPage_ESD_Label_2_1_Font__Property;
	object->Text = Usr_HeatSettingPage_ESD_Label_2_1_Text__Property;
	object->AlignX = Usr_HeatSettingPage_ESD_Label_2_1_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_HeatSettingPage__ESD_Rectangle_Widget_4__Initializer(Usr_HeatSettingPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget_4;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 108;
	object->Widget.LocalY = 41;
	object->Widget.LocalWidth = 260;
	object->Widget.LocalHeight = 48;
	object->Radius = Usr_HeatSettingPage_ESD_Rectangle_Widget_4_Radius__Property;
	object->Color = Usr_HeatSettingPage_ESD_Rectangle_Widget_4_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_HeatSettingPage__ESD_Image_1__Initializer(Usr_HeatSettingPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_1;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = -2;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_HeatSettingPage__ESD_Rectangle_Widget__Initializer(Usr_HeatSettingPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 480;
	object->Widget.LocalHeight = 480;
	object->Color = Usr_HeatSettingPage_ESD_Rectangle_Widget_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_HeatSettingPage__Initializer(Usr_HeatSettingPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_HeatSettingPage_CLASSID;
	context->Widget.Slots = &s_Usr_HeatSettingPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Local_Method__Value = 0;
	context->BackPushed = Esd_Noop;
	context->NewValue = 0L;
	Usr_HeatSettingPage__Fixed_Position__Initializer(context);
	Usr_HeatSettingPage__ESD_Numeric_Label__Initializer(context);
	Usr_HeatSettingPage__ESD_Push_Button_1_1__Initializer(context);
	Usr_HeatSettingPage__ESD_Push_Button_1__Initializer(context);
	Usr_HeatSettingPage__ESD_Image_Button__Initializer(context);
	Usr_HeatSettingPage__ESD_Label_1__Initializer(context);
	Usr_HeatSettingPage__ESD_Label__Initializer(context);
	Usr_HeatSettingPage__ESD_Label_2__Initializer(context);
	Usr_HeatSettingPage__Rectangle_Light__Initializer(context);
	Usr_HeatSettingPage__Rectangle_Light_1__Initializer(context);
	Usr_HeatSettingPage__ESD_Label_2_1__Initializer(context);
	Usr_HeatSettingPage__ESD_Rectangle_Widget_4__Initializer(context);
	Usr_HeatSettingPage__ESD_Image_1__Initializer(context);
	Usr_HeatSettingPage__ESD_Rectangle_Widget__Initializer(context);
}

extern int g_FloorHeatingSettingValue;

static int Usr_HeatSettingPage_Local_Method(Usr_HeatSettingPage *context, int value);
static void Usr_HeatSettingPage_Local_Method__Internal(Usr_HeatSettingPage *context);

void Usr_HeatSettingPage_End(Usr_HeatSettingPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Numeric_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Push_Button_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Push_Button_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Rectangle_Light); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Rectangle_Light_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget); 
}

void Usr_HeatSettingPage_Right(Usr_HeatSettingPage *context)
{
	void *owner = context->Owner;
	int left = g_FloorHeatingSettingValue;
	int right = 1L;
	int set_variable_2_1 = left + right;
	context->NewValue = set_variable_2_1;
	Usr_HeatSettingPage_Local_Method__Internal(context);
	int set_variable = context->Local_Method__Value;
	g_FloorHeatingSettingValue = set_variable;
}

void Usr_HeatSettingPage_Left(Usr_HeatSettingPage *context)
{
	void *owner = context->Owner;
	int left_1 = g_FloorHeatingSettingValue;
	int right_1 = 1L;
	int set_variable_3_1 = left_1 - right_1;
	context->NewValue = set_variable_3_1;
	Usr_HeatSettingPage_Local_Method__Internal(context);
	int set_variable_1 = context->Local_Method__Value;
	g_FloorHeatingSettingValue = set_variable_1;
}

static int Usr_HeatSettingPage_Local_Method(Usr_HeatSettingPage *context, int value)
{
	void *owner = context->Owner;
	if(value < 0) return 0;
	else if (value > 30) return 30;
	else return value;
}

static void Usr_HeatSettingPage_Local_Method__Internal(Usr_HeatSettingPage *context)
{
	void *owner = context->Owner;
	int value = context->NewValue;
	context->Local_Method__Value = Usr_HeatSettingPage_Local_Method(context, value);
}

ft_int32_t Usr_HeatSettingPage_ESD_Numeric_Label_Value__Property(void *c)
{
	Usr_HeatSettingPage *context = (Usr_HeatSettingPage *)c;
	void *owner = context->Owner;
	return g_FloorHeatingSettingValue;
}

void Usr_HeatSettingPage_ESD_Push_Button_1_1_Pushed__Signal(void *c)
{
	Usr_HeatSettingPage *context = (Usr_HeatSettingPage *)c;
	void *owner = context->Owner;
	int left_2 = g_FloorHeatingSettingValue;
	int right_2 = 1L;
	int set_variable_3 = left_2 - right_2;
	context->NewValue = set_variable_3;
	Usr_HeatSettingPage_Local_Method__Internal(context);
	int set_variable_2 = context->Local_Method__Value;
	g_FloorHeatingSettingValue = set_variable_2;
}

void Usr_HeatSettingPage_ESD_Push_Button_1_Pushed__Signal(void *c)
{
	Usr_HeatSettingPage *context = (Usr_HeatSettingPage *)c;
	void *owner = context->Owner;
	int left_3 = g_FloorHeatingSettingValue;
	int right_3 = 1L;
	int set_variable_2_2 = left_3 + right_3;
	context->NewValue = set_variable_2_2;
	Usr_HeatSettingPage_Local_Method__Internal(context);
	int set_variable_4 = context->Local_Method__Value;
	g_FloorHeatingSettingValue = set_variable_4;
}

void Usr_HeatSettingPage_ESD_Image_Button_Pushed__Signal(void *c)
{
	Usr_HeatSettingPage *context = (Usr_HeatSettingPage *)c;
	void *owner = context->Owner;
	context->BackPushed(owner);
}


/* end of file */
