/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_LightWidget
C Source
*/

#include "Usr_LightWidget.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);


static Ft_Esd_WidgetSlots s_Usr_LightWidget__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Usr_LightWidget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Usr_LightWidget_Update,
	(void(*)(void *))Usr_LightWidget_Render,
	(void(*)(void *))Usr_LightWidget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_LightWidget_End,
};


void Usr_LightWidget__Initializer(Usr_LightWidget *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_LightWidget_CLASSID;
	context->Widget.Slots = &s_Usr_LightWidget__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
}

void Usr_LightWidget_Render_Signal(Usr_LightWidget *context);

void Usr_LightWidget_Start(Usr_LightWidget *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context); 
}

void Usr_LightWidget_Update(Usr_LightWidget *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context); 
}

void Usr_LightWidget_Render(Usr_LightWidget *context)
{
	void *owner = context->Owner;
	Usr_LightWidget_Render_Signal(context);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

void Usr_LightWidget_Idle(Usr_LightWidget *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Idle((Ft_Esd_Widget *)context); 
}

void Usr_LightWidget_End(Usr_LightWidget *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context); 
}


/* end of file */
