/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_CurtainMorePages
Header
*/

#ifndef Usr_CurtainMorePages__H
#define Usr_CurtainMorePages__H

#include "Curtain_adjust.h"
#include "Curtain_hand_pull.h"
#include "Esd_Base.h"
#include "Esd_Core.h"
#include "Esd_FontInfo.h"
#include "Ft_Esd.h"
#include "Ft_Esd_BitmapInfo.h"
#include "Ft_Esd_Image.h"
#include "Ft_Esd_ImageButton.h"
#include "Ft_Esd_Label.h"
#include "Ft_Esd_Layout_Fixed.h"
#include "Ft_Esd_Rectangle.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_Widget.h"
#include "linkable.h"
#include "return_circle_64.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Usr_CurtainMorePages_CLASSID 0x2B0E0F69
ESD_SYMBOL(Usr_CurtainMorePages_CLASSID, Type = esd_classid_t)

ESD_WIDGET(Usr_CurtainMorePages, Include = "Usr_CurtainMorePages.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_SIGNAL(BackPushed)
	void(* BackPushed)(void *context);
	Ft_Esd_Layout_Fixed Fixed_Position;
	Ft_Esd_ImageButton ESD_Image_Button;
	Ft_Esd_Image ESD_Image_2_1_1_1;
	Ft_Esd_Image ESD_Image_2_2;
	Ft_Esd_Image ESD_Image_2;
	Ft_Esd_Label ESD_Label_1_1;
	Ft_Esd_Label ESD_Label_1_2;
	Ft_Esd_Label ESD_Label_1;
	Ft_Esd_Rectangle Rectangle_Light_2;
	Ft_Esd_Rectangle Rectangle_Light_1;
	Ft_Esd_Rectangle Rectangle_Light;
	Ft_Esd_Label ESD_Label;
	Ft_Esd_Rectangle ESD_Rectangle_Widget_4;
} Usr_CurtainMorePages;

void Usr_CurtainMorePages__Initializer(Usr_CurtainMorePages *context);

ESD_SLOT(End)
void Usr_CurtainMorePages_End(Usr_CurtainMorePages *context);

#endif /* Usr_CurtainMorePages__H */

/* end of file */
