/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_CurtainPage
C Source
*/

#include "Usr_CurtainPage.h"

#include "Esd_Context.h"
#include "Usr_GlobalVariables.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);

static ft_argb32_t Usr_CurtainPage_ESD_Touch_Panel_1_1_2_Color__Property(void *context) { return 0x181818UL; }
static int Usr_CurtainPage_ESD_Touch_Panel_1_1_2_Radius__Property(void *context) { return 40L; }
static ft_bool_t Usr_CurtainPage_ESD_Touch_Panel_1_1_2_ShowBorder__Property(void *context) { return 0; }
static ft_argb32_t Usr_CurtainPage_ESD_Touch_Panel_1_1_1_Color__Property(void *context) { return 0x181818UL; }
static int Usr_CurtainPage_ESD_Touch_Panel_1_1_1_Radius__Property(void *context) { return 40L; }
static ft_bool_t Usr_CurtainPage_ESD_Touch_Panel_1_1_1_ShowBorder__Property(void *context) { return 0; }
static ft_argb32_t Usr_CurtainPage_ESD_Touch_Panel_1_1_Color__Property(void *context) { return 0x181818UL; }
static int Usr_CurtainPage_ESD_Touch_Panel_1_1_Radius__Property(void *context) { return 40L; }
static ft_bool_t Usr_CurtainPage_ESD_Touch_Panel_1_1_ShowBorder__Property(void *context) { return 0; }
static ft_argb32_t Usr_CurtainPage_ESD_Touch_Panel_1_Color__Property(void *context) { return 0x181818UL; }
static int Usr_CurtainPage_ESD_Touch_Panel_1_Radius__Property(void *context) { return 40L; }
static ft_bool_t Usr_CurtainPage_ESD_Touch_Panel_1_ShowBorder__Property(void *context) { return 0; }
static ft_uint8_t Usr_CurtainPage_ESD_Image_Button_4_MinAlpha__Property(void *context) { return 0; }
static Ft_Esd_BitmapCell Usr_CurtainPage_ESD_Image_Button_4_BitmapNormal__Property(void *context) { return funtion_icon_0(); }
static ft_uint8_t Usr_CurtainPage_ESD_Image_Button_3_MinAlpha__Property(void *context) { return 0; }
static Ft_Esd_BitmapCell Usr_CurtainPage_ESD_Image_Button_3_BitmapNormal__Property(void *context) { return alarm_clock4_0(); }
static ft_uint8_t Usr_CurtainPage_ESD_Image_Button_2_MinAlpha__Property(void *context) { return 0; }
static Ft_Esd_BitmapCell Usr_CurtainPage_ESD_Image_Button_2_BitmapNormal__Property(void *context) { return curtain_close1_0(); }
static ft_uint8_t Usr_CurtainPage_ESD_Image_Button_MinAlpha__Property(void *context) { return 0; }
static Ft_Esd_BitmapCell Usr_CurtainPage_ESD_Image_Button_BitmapNormal__Property(void *context) { return curtain_open1_0(); }
static uint8_t Usr_CurtainPage_Label_Light_1_1_1_Font__Property(void *context) { return 28; }
static const char * Usr_CurtainPage_Label_Light_1_1_1_Text__Property(void *context) { return "Function"; }
static ft_uint16_t Usr_CurtainPage_Label_Light_1_1_1_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_uint16_t Usr_CurtainPage_Label_Light_1_1_1_AlignY__Property(void *context) { return OPT_ALIGN_CENTER; }
static uint8_t Usr_CurtainPage_Label_Light_1_1_Font__Property(void *context) { return 28; }
static const char * Usr_CurtainPage_Label_Light_1_1_Text__Property(void *context) { return "Timing"; }
static ft_uint16_t Usr_CurtainPage_Label_Light_1_1_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_uint16_t Usr_CurtainPage_Label_Light_1_1_AlignY__Property(void *context) { return OPT_ALIGN_CENTER; }
static uint8_t Usr_CurtainPage_Label_Light_1_Font__Property(void *context) { return 28; }
static const char * Usr_CurtainPage_Label_Light_1_Text__Property(void *context) { return "Curtain closed"; }
static ft_uint16_t Usr_CurtainPage_Label_Light_1_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_uint16_t Usr_CurtainPage_Label_Light_1_AlignY__Property(void *context) { return OPT_ALIGN_CENTER; }
static uint8_t Usr_CurtainPage_Label_Light_Font__Property(void *context) { return 28; }
static const char * Usr_CurtainPage_Label_Light_Text__Property(void *context) { return "Curtain open"; }
static ft_uint16_t Usr_CurtainPage_Label_Light_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_uint16_t Usr_CurtainPage_Label_Light_AlignY__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_int32_t Usr_CurtainPage_Rectangle_Heating_Radius__Property(void *context) { return 40L; }
static ft_argb32_t Usr_CurtainPage_Rectangle_Heating_Color__Property(void *context) { return 0x3ae8f1f9UL; }
static ft_int32_t Usr_CurtainPage_Rectangle_Curtain_Radius__Property(void *context) { return 40L; }
static ft_argb32_t Usr_CurtainPage_Rectangle_Curtain_Color__Property(void *context) { return 0x3ae8f1f9UL; }
static ft_int32_t Usr_CurtainPage_Rectangle_Air_Con_Radius__Property(void *context) { return 40L; }
static ft_argb32_t Usr_CurtainPage_Rectangle_Air_Con_Color__Property(void *context) { return 0x3ae8f1f9UL; }
static ft_int32_t Usr_CurtainPage_Rectangle_Light_Radius__Property(void *context) { return 40L; }
static ft_argb32_t Usr_CurtainPage_Rectangle_Light_Color__Property(void *context) { return 0x3ae8f1f9UL; }
static uint8_t Usr_CurtainPage_ESD_Label_Font__Property(void *context) { return 30; }
static const char * Usr_CurtainPage_ESD_Label_Text__Property(void *context) { return "Smart curtains"; }
static ft_uint16_t Usr_CurtainPage_ESD_Label_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_int32_t Usr_CurtainPage_ESD_Rectangle_Widget_4_Radius__Property(void *context) { return 24L; }
static ft_argb32_t Usr_CurtainPage_ESD_Rectangle_Widget_4_Color__Property(void *context) { return 0x59000000UL; }

static Ft_Esd_WidgetSlots s_Usr_CurtainPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_CurtainPage_End,
};

static void Usr_CurtainPage_ESD_Touch_Panel_1_1_2_Tap__Signal(void *context);
static void Usr_CurtainPage_ESD_Touch_Panel_1_1_1_Tap__Signal(void *context);
static void Usr_CurtainPage_ESD_Touch_Panel_1_1_Tap__Signal(void *context);
static void Usr_CurtainPage_ESD_Touch_Panel_1_Tap__Signal(void *context);

void Usr_CurtainPage__Fixed_Position__Initializer(Usr_CurtainPage *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_CurtainPage__ESD_Touch_Panel_1_1_2__Initializer(Usr_CurtainPage *context)
{
	Ft_Esd_TouchPanel *object = (Ft_Esd_TouchPanel *)&context->ESD_Touch_Panel_1_1_2;
	Ft_Esd_TouchPanel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 245;
	object->Widget.LocalY = 254;
	object->Widget.LocalWidth = 160;
	object->Widget.LocalHeight = 134;
	object->Color = Usr_CurtainPage_ESD_Touch_Panel_1_1_2_Color__Property;
	object->Radius = Usr_CurtainPage_ESD_Touch_Panel_1_1_2_Radius__Property;
	object->ShowBorder = Usr_CurtainPage_ESD_Touch_Panel_1_1_2_ShowBorder__Property;
	object->Tap = Usr_CurtainPage_ESD_Touch_Panel_1_1_2_Tap__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainPage__ESD_Touch_Panel_1_1_1__Initializer(Usr_CurtainPage *context)
{
	Ft_Esd_TouchPanel *object = (Ft_Esd_TouchPanel *)&context->ESD_Touch_Panel_1_1_1;
	Ft_Esd_TouchPanel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 73;
	object->Widget.LocalY = 252;
	object->Widget.LocalWidth = 160;
	object->Widget.LocalHeight = 134;
	object->Color = Usr_CurtainPage_ESD_Touch_Panel_1_1_1_Color__Property;
	object->Radius = Usr_CurtainPage_ESD_Touch_Panel_1_1_1_Radius__Property;
	object->ShowBorder = Usr_CurtainPage_ESD_Touch_Panel_1_1_1_ShowBorder__Property;
	object->Tap = Usr_CurtainPage_ESD_Touch_Panel_1_1_1_Tap__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainPage__ESD_Touch_Panel_1_1__Initializer(Usr_CurtainPage *context)
{
	Ft_Esd_TouchPanel *object = (Ft_Esd_TouchPanel *)&context->ESD_Touch_Panel_1_1;
	Ft_Esd_TouchPanel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 245;
	object->Widget.LocalY = 107;
	object->Widget.LocalWidth = 160;
	object->Widget.LocalHeight = 134;
	object->Color = Usr_CurtainPage_ESD_Touch_Panel_1_1_Color__Property;
	object->Radius = Usr_CurtainPage_ESD_Touch_Panel_1_1_Radius__Property;
	object->ShowBorder = Usr_CurtainPage_ESD_Touch_Panel_1_1_ShowBorder__Property;
	object->Tap = Usr_CurtainPage_ESD_Touch_Panel_1_1_Tap__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainPage__ESD_Touch_Panel_1__Initializer(Usr_CurtainPage *context)
{
	Ft_Esd_TouchPanel *object = (Ft_Esd_TouchPanel *)&context->ESD_Touch_Panel_1;
	Ft_Esd_TouchPanel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 74;
	object->Widget.LocalY = 110;
	object->Widget.LocalWidth = 160;
	object->Widget.LocalHeight = 134;
	object->Color = Usr_CurtainPage_ESD_Touch_Panel_1_Color__Property;
	object->Radius = Usr_CurtainPage_ESD_Touch_Panel_1_Radius__Property;
	object->ShowBorder = Usr_CurtainPage_ESD_Touch_Panel_1_ShowBorder__Property;
	object->Tap = Usr_CurtainPage_ESD_Touch_Panel_1_Tap__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainPage__ESD_Image_Button_4__Initializer(Usr_CurtainPage *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button_4;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 294;
	object->Widget.LocalY = 275;
	object->Widget.LocalWidth = 64;
	object->Widget.LocalHeight = 71;
	object->MinAlpha = Usr_CurtainPage_ESD_Image_Button_4_MinAlpha__Property;
	object->BitmapNormal = Usr_CurtainPage_ESD_Image_Button_4_BitmapNormal__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainPage__ESD_Image_Button_3__Initializer(Usr_CurtainPage *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button_3;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 122;
	object->Widget.LocalY = 276;
	object->Widget.LocalWidth = 68;
	object->Widget.LocalHeight = 72;
	object->MinAlpha = Usr_CurtainPage_ESD_Image_Button_3_MinAlpha__Property;
	object->BitmapNormal = Usr_CurtainPage_ESD_Image_Button_3_BitmapNormal__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainPage__ESD_Image_Button_2__Initializer(Usr_CurtainPage *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button_2;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 294;
	object->Widget.LocalY = 132;
	object->Widget.LocalWidth = 66;
	object->Widget.LocalHeight = 62;
	object->MinAlpha = Usr_CurtainPage_ESD_Image_Button_2_MinAlpha__Property;
	object->BitmapNormal = Usr_CurtainPage_ESD_Image_Button_2_BitmapNormal__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainPage__ESD_Image_Button__Initializer(Usr_CurtainPage *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 123;
	object->Widget.LocalY = 132;
	object->Widget.LocalWidth = 65;
	object->Widget.LocalHeight = 63;
	object->MinAlpha = Usr_CurtainPage_ESD_Image_Button_MinAlpha__Property;
	object->BitmapNormal = Usr_CurtainPage_ESD_Image_Button_BitmapNormal__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainPage__Label_Light_1_1_1__Initializer(Usr_CurtainPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Label_Light_1_1_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 246;
	object->Widget.LocalY = 353;
	object->Widget.LocalWidth = 160;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_CurtainPage_Label_Light_1_1_1_Font__Property;
	object->Text = Usr_CurtainPage_Label_Light_1_1_1_Text__Property;
	object->AlignX = Usr_CurtainPage_Label_Light_1_1_1_AlignX__Property;
	object->AlignY = Usr_CurtainPage_Label_Light_1_1_1_AlignY__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainPage__Label_Light_1_1__Initializer(Usr_CurtainPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Label_Light_1_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 74;
	object->Widget.LocalY = 354;
	object->Widget.LocalWidth = 160;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_CurtainPage_Label_Light_1_1_Font__Property;
	object->Text = Usr_CurtainPage_Label_Light_1_1_Text__Property;
	object->AlignX = Usr_CurtainPage_Label_Light_1_1_AlignX__Property;
	object->AlignY = Usr_CurtainPage_Label_Light_1_1_AlignY__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainPage__Label_Light_1__Initializer(Usr_CurtainPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Label_Light_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 246;
	object->Widget.LocalY = 203;
	object->Widget.LocalWidth = 160;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_CurtainPage_Label_Light_1_Font__Property;
	object->Text = Usr_CurtainPage_Label_Light_1_Text__Property;
	object->AlignX = Usr_CurtainPage_Label_Light_1_AlignX__Property;
	object->AlignY = Usr_CurtainPage_Label_Light_1_AlignY__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainPage__Label_Light__Initializer(Usr_CurtainPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Label_Light;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 74;
	object->Widget.LocalY = 206;
	object->Widget.LocalWidth = 160;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_CurtainPage_Label_Light_Font__Property;
	object->Text = Usr_CurtainPage_Label_Light_Text__Property;
	object->AlignX = Usr_CurtainPage_Label_Light_AlignX__Property;
	object->AlignY = Usr_CurtainPage_Label_Light_AlignY__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainPage__Rectangle_Heating__Initializer(Usr_CurtainPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->Rectangle_Heating;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 246;
	object->Widget.LocalY = 258;
	object->Widget.LocalWidth = 160;
	object->Widget.LocalHeight = 134;
	object->Radius = Usr_CurtainPage_Rectangle_Heating_Radius__Property;
	object->Color = Usr_CurtainPage_Rectangle_Heating_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainPage__Rectangle_Curtain__Initializer(Usr_CurtainPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->Rectangle_Curtain;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 74;
	object->Widget.LocalY = 258;
	object->Widget.LocalWidth = 160;
	object->Widget.LocalHeight = 134;
	object->Radius = Usr_CurtainPage_Rectangle_Curtain_Radius__Property;
	object->Color = Usr_CurtainPage_Rectangle_Curtain_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainPage__Rectangle_Air_Con__Initializer(Usr_CurtainPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->Rectangle_Air_Con;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 246;
	object->Widget.LocalY = 110;
	object->Widget.LocalWidth = 160;
	object->Widget.LocalHeight = 134;
	object->Radius = Usr_CurtainPage_Rectangle_Air_Con_Radius__Property;
	object->Color = Usr_CurtainPage_Rectangle_Air_Con_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainPage__Rectangle_Light__Initializer(Usr_CurtainPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->Rectangle_Light;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 74;
	object->Widget.LocalY = 110;
	object->Widget.LocalWidth = 160;
	object->Widget.LocalHeight = 134;
	object->Radius = Usr_CurtainPage_Rectangle_Light_Radius__Property;
	object->Color = Usr_CurtainPage_Rectangle_Light_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainPage__ESD_Label__Initializer(Usr_CurtainPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 116;
	object->Widget.LocalY = 50;
	object->Widget.LocalWidth = 248;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_CurtainPage_ESD_Label_Font__Property;
	object->Text = Usr_CurtainPage_ESD_Label_Text__Property;
	object->AlignX = Usr_CurtainPage_ESD_Label_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainPage__ESD_Rectangle_Widget_4__Initializer(Usr_CurtainPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget_4;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 116;
	object->Widget.LocalY = 45;
	object->Widget.LocalWidth = 248;
	object->Widget.LocalHeight = 48;
	object->Radius = Usr_CurtainPage_ESD_Rectangle_Widget_4_Radius__Property;
	object->Color = Usr_CurtainPage_ESD_Rectangle_Widget_4_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainPage__Initializer(Usr_CurtainPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_CurtainPage_CLASSID;
	context->Widget.Slots = &s_Usr_CurtainPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->ButtonPushed = Esd_Noop;
	context->SubPage = 0L;
	Usr_CurtainPage__Fixed_Position__Initializer(context);
	Usr_CurtainPage__ESD_Touch_Panel_1_1_2__Initializer(context);
	Usr_CurtainPage__ESD_Touch_Panel_1_1_1__Initializer(context);
	Usr_CurtainPage__ESD_Touch_Panel_1_1__Initializer(context);
	Usr_CurtainPage__ESD_Touch_Panel_1__Initializer(context);
	Usr_CurtainPage__ESD_Image_Button_4__Initializer(context);
	Usr_CurtainPage__ESD_Image_Button_3__Initializer(context);
	Usr_CurtainPage__ESD_Image_Button_2__Initializer(context);
	Usr_CurtainPage__ESD_Image_Button__Initializer(context);
	Usr_CurtainPage__Label_Light_1_1_1__Initializer(context);
	Usr_CurtainPage__Label_Light_1_1__Initializer(context);
	Usr_CurtainPage__Label_Light_1__Initializer(context);
	Usr_CurtainPage__Label_Light__Initializer(context);
	Usr_CurtainPage__Rectangle_Heating__Initializer(context);
	Usr_CurtainPage__Rectangle_Curtain__Initializer(context);
	Usr_CurtainPage__Rectangle_Air_Con__Initializer(context);
	Usr_CurtainPage__Rectangle_Light__Initializer(context);
	Usr_CurtainPage__ESD_Label__Initializer(context);
	Usr_CurtainPage__ESD_Rectangle_Widget_4__Initializer(context);
}

extern int g_CurtainOpenPercentage;
extern int g_CurtainOpenPrevPercentage;

void Usr_CurtainPage_End(Usr_CurtainPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Touch_Panel_1_1_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Touch_Panel_1_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Touch_Panel_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Touch_Panel_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Label_Light_1_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Label_Light_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Label_Light_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Label_Light); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Rectangle_Heating); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Rectangle_Curtain); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Rectangle_Air_Con); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Rectangle_Light); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget_4); 
}

int Usr_CurtainPage_CurrentPage(Usr_CurtainPage *context)
{
	void *owner = context->Owner;
	return context->SubPage;
}

void Usr_CurtainPage_ESD_Touch_Panel_1_1_2_Tap__Signal(void *c)
{
	Usr_CurtainPage *context = (Usr_CurtainPage *)c;
	void *owner = context->Owner;
	int set_variable_1_1_1 = 34L;
	context->SubPage = set_variable_1_1_1;
	context->ButtonPushed(owner);
}

void Usr_CurtainPage_ESD_Touch_Panel_1_1_1_Tap__Signal(void *c)
{
	Usr_CurtainPage *context = (Usr_CurtainPage *)c;
	void *owner = context->Owner;
	int set_variable_1_1 = 33L;
	context->SubPage = set_variable_1_1;
	context->ButtonPushed(owner);
}

void Usr_CurtainPage_ESD_Touch_Panel_1_1_Tap__Signal(void *c)
{
	Usr_CurtainPage *context = (Usr_CurtainPage *)c;
	void *owner = context->Owner;
	int set_variable_3_1 = g_CurtainOpenPercentage;
	g_CurtainOpenPrevPercentage = set_variable_3_1;
	int set_variable_3 = 100L;
	g_CurtainOpenPercentage = set_variable_3;
	int set_variable_1 = 32L;
	context->SubPage = set_variable_1;
	context->ButtonPushed(owner);
}

void Usr_CurtainPage_ESD_Touch_Panel_1_Tap__Signal(void *c)
{
	Usr_CurtainPage *context = (Usr_CurtainPage *)c;
	void *owner = context->Owner;
	int left = g_CurtainOpenPercentage;
	int right = 100L;
	int if_1 = left >= right;
	if (if_1)
	{
		int set_variable_2 = g_CurtainOpenPrevPercentage;
		g_CurtainOpenPercentage = set_variable_2;
		int set_variable = 31L;
		context->SubPage = set_variable;
		context->ButtonPushed(owner);
	}
	else
	{
		int set_variable_4 = 31L;
		context->SubPage = set_variable_4;
		context->ButtonPushed(owner);
	}
}


/* end of file */
