/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_LightPage
Header
*/

#ifndef Usr_LightPage__H
#define Usr_LightPage__H

#include "Esd_Base.h"
#include "Esd_Core.h"
#include "Esd_FontInfo.h"
#include "Ft_Esd.h"
#include "Ft_Esd_BitmapInfo.h"
#include "Ft_Esd_Image.h"
#include "Ft_Esd_ImageButton.h"
#include "Ft_Esd_Label.h"
#include "Ft_Esd_Layout_Fixed.h"
#include "Ft_Esd_Rectangle.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_TouchPanel.h"
#include "Ft_Esd_Widget.h"
#include "light_case_level1.h"
#include "light_page_on.h"
#include "power_white_icon.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Usr_LightPage_CLASSID 0xAAE9267A
ESD_SYMBOL(Usr_LightPage_CLASSID, Type = esd_classid_t)

ESD_WIDGET(Usr_LightPage, Include = "Usr_LightPage.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_SIGNAL(ButtonPushed)
	void(* ButtonPushed)(void *context);
	ESD_VARIABLE(SubPage, Type = int, Private)
	int SubPage;
	Ft_Esd_Layout_Fixed Fixed_Position;
	Ft_Esd_TouchPanel ESD_Touch_Panel_1_1_1;
	Ft_Esd_TouchPanel ESD_Touch_Panel_1_1;
	Ft_Esd_TouchPanel ESD_Touch_Panel_1;
	Ft_Esd_TouchPanel ESD_Touch_Panel;
	Ft_Esd_Image ESD_Image_2_1_1_1_1;
	Ft_Esd_Image ESD_Image_2_1_1_1;
	Ft_Esd_Image ESD_Image_2_2_1_1;
	Ft_Esd_Image ESD_Image_2_1_1;
	Ft_Esd_Image ESD_Image_2_2_1;
	Ft_Esd_Image ESD_Image_2_1;
	Ft_Esd_Image ESD_Image_2_2;
	Ft_Esd_Image ESD_Image_2;
	Ft_Esd_Label ESD_Label_1_1_1;
	Ft_Esd_Label ESD_Label_1_1;
	Ft_Esd_Label ESD_Label_1;
	Ft_Esd_Label ESD_Label;
	Ft_Esd_ImageButton ESD_Image_Button_1_1_1;
	Ft_Esd_ImageButton ESD_Image_Button_1_1;
	Ft_Esd_ImageButton ESD_Image_Button_1;
	Ft_Esd_ImageButton ESD_Image_Button;
	Ft_Esd_Rectangle Rectangle_Light_3;
	Ft_Esd_Rectangle Rectangle_Light_2;
	Ft_Esd_Rectangle Rectangle_Light_1;
	Ft_Esd_Rectangle Rectangle_Light;
	Ft_Esd_Label Light_Control_Label;
	Ft_Esd_Rectangle ESD_Rectangle_Widget_4;
} Usr_LightPage;

void Usr_LightPage__Initializer(Usr_LightPage *context);

ESD_SLOT(End)
void Usr_LightPage_End(Usr_LightPage *context);

ESD_OUTPUT(CurrentPage, Type = int)
int Usr_LightPage_CurrentPage(Usr_LightPage *context);

#endif /* Usr_LightPage__H */

/* end of file */
