/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_CeilingLightPage
C Source
*/

#include "Usr_CeilingLightPage.h"

#include "Esd_Context.h"
#include "Usr_GlobalVariables.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);

static Ft_Esd_BitmapCell Usr_CeilingLightPage_ESD_Image_4_BitmapCell__Property(void *context) { return CeilingLightWire1_0(); }
static Ft_Esd_BitmapCell Usr_CeilingLightPage_ESD_Image_3_BitmapCell__Property(void *context) { return CelingLight1_0(); }
static Ft_Esd_Theme * Usr_CeilingLightPage_ESD_RangeSlider_Theme__Property(void *context) { return Ft_Esd_Theme_DarkOrange(); }
static ft_int16_t Usr_CeilingLightPage_ESD_RangeSlider_Min__Property(void *context) { return 75; }
static ft_int16_t Usr_CeilingLightPage_ESD_RangeSlider_Max__Property(void *context) { return 255; }
static ft_int16_t Usr_CeilingLightPage_ESD_RangeSlider_Step__Property(void *context) { return 10; }
static ft_int16_t Usr_CeilingLightPage_ESD_RangeSlider_Value__Property(void *context);
static uint8_t Usr_CeilingLightPage_ESD_Label_Font__Property(void *context) { return 29; }
static const char * Usr_CeilingLightPage_ESD_Label_Text__Property(void *context) { return "Ceiling Light"; }
static ft_uint16_t Usr_CeilingLightPage_ESD_Label_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_uint8_t Usr_CeilingLightPage_ESD_Image_Button_2_MinAlpha__Property(void *context) { return 0; }
static Ft_Esd_BitmapCell Usr_CeilingLightPage_ESD_Image_Button_2_BitmapNormal__Property(void *context) { return power_circle_64_0(); }
static ft_uint8_t Usr_CeilingLightPage_ESD_Image_Button_MinAlpha__Property(void *context) { return 0; }
static Ft_Esd_BitmapCell Usr_CeilingLightPage_ESD_Image_Button_BitmapNormal__Property(void *context) { return return_circle_64_0(); }
static Ft_Esd_BitmapCell Usr_CeilingLightPage_ESD_Image_2_BitmapCell__Property(void *context) { return CeilingLigehtCase2_0(); }
static ft_int32_t Usr_CeilingLightPage_ESD_Rectangle_Widget_4_Radius__Property(void *context) { return 24L; }
static ft_argb32_t Usr_CeilingLightPage_ESD_Rectangle_Widget_4_Color__Property(void *context) { return 0x59000000UL; }
static ft_argb32_t Usr_CeilingLightPage_ESD_Gradient_Widget_color1__Property(void *context) { return 0xff414141UL; }
static ft_argb32_t Usr_CeilingLightPage_ESD_Gradient_Widget_color2__Property(void *context) { return 0xff010101UL; }
static bool Usr_CeilingLightPage_ESD_Gradient_Widget_Manual__Property(void *context) { return 1; }

static Ft_Esd_WidgetSlots s_Usr_CeilingLightPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Usr_CeilingLightPage_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Usr_CeilingLightPage_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_CeilingLightPage_End,
};

static void Usr_CeilingLightPage_ESD_Image_Button_2_Pushed__Signal(void *context);
static void Usr_CeilingLightPage_ESD_Image_Button_Pushed__Signal(void *context);

void Usr_CeilingLightPage__Fixed_Position__Initializer(Usr_CeilingLightPage *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_CeilingLightPage__ESD_Image_4__Initializer(Usr_CeilingLightPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_4;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 234;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 13;
	object->Widget.LocalHeight = 88;
	object->BitmapCell = Usr_CeilingLightPage_ESD_Image_4_BitmapCell__Property;
	object->Scaling = ESD_SCALING_FILL;
	object->AutoResize = ESD_AUTORESIZE_NONE;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CeilingLightPage__ESD_Image_3__Initializer(Usr_CeilingLightPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_3;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 157;
	object->Widget.LocalY = 145;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->Color = 0xffffaa00UL;
	object->BitmapCell = Usr_CeilingLightPage_ESD_Image_3_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CeilingLightPage__ESD_RangeSlider__Initializer(Usr_CeilingLightPage *context)
{
	Ft_Esd_RangeSlider *object = (Ft_Esd_RangeSlider *)&context->ESD_RangeSlider;
	Ft_Esd_RangeSlider__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 130;
	object->Widget.LocalY = 233;
	object->Widget.LocalWidth = 220;
	object->Widget.LocalHeight = 39;
	object->Theme = Usr_CeilingLightPage_ESD_RangeSlider_Theme__Property;
	object->Min = Usr_CeilingLightPage_ESD_RangeSlider_Min__Property;
	object->Max = Usr_CeilingLightPage_ESD_RangeSlider_Max__Property;
	object->Step = Usr_CeilingLightPage_ESD_RangeSlider_Step__Property;
	object->Value = Usr_CeilingLightPage_ESD_RangeSlider_Value__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CeilingLightPage__ESD_Label__Initializer(Usr_CeilingLightPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 150;
	object->Widget.LocalY = 407;
	object->Widget.LocalWidth = 180;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_CeilingLightPage_ESD_Label_Font__Property;
	object->Text = Usr_CeilingLightPage_ESD_Label_Text__Property;
	object->AlignX = Usr_CeilingLightPage_ESD_Label_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CeilingLightPage__ESD_Image_Button_2__Initializer(Usr_CeilingLightPage *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button_2;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 122;
	object->Widget.LocalY = 310;
	object->Widget.LocalWidth = 64;
	object->Widget.LocalHeight = 64;
	object->MinAlpha = Usr_CeilingLightPage_ESD_Image_Button_2_MinAlpha__Property;
	object->BitmapNormal = Usr_CeilingLightPage_ESD_Image_Button_2_BitmapNormal__Property;
	object->Pushed = Usr_CeilingLightPage_ESD_Image_Button_2_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CeilingLightPage__ESD_Image_Button__Initializer(Usr_CeilingLightPage *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 294;
	object->Widget.LocalY = 310;
	object->Widget.LocalWidth = 64;
	object->Widget.LocalHeight = 64;
	object->MinAlpha = Usr_CeilingLightPage_ESD_Image_Button_MinAlpha__Property;
	object->BitmapNormal = Usr_CeilingLightPage_ESD_Image_Button_BitmapNormal__Property;
	object->Pushed = Usr_CeilingLightPage_ESD_Image_Button_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CeilingLightPage__ESD_Image_2__Initializer(Usr_CeilingLightPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_2;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 158;
	object->Widget.LocalY = 89;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->BitmapCell = Usr_CeilingLightPage_ESD_Image_2_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CeilingLightPage__ESD_Rectangle_Widget_4__Initializer(Usr_CeilingLightPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget_4;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 136;
	object->Widget.LocalY = 398;
	object->Widget.LocalWidth = 208;
	object->Widget.LocalHeight = 48;
	object->Radius = Usr_CeilingLightPage_ESD_Rectangle_Widget_4_Radius__Property;
	object->Color = Usr_CeilingLightPage_ESD_Rectangle_Widget_4_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CeilingLightPage__ESD_Gradient_Widget__Initializer(Usr_CeilingLightPage *context)
{
	Ft_Esd_Gradient *object = (Ft_Esd_Gradient *)&context->ESD_Gradient_Widget;
	Ft_Esd_Gradient__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 1;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 480;
	object->Widget.LocalHeight = 480;
	object->color1 = Usr_CeilingLightPage_ESD_Gradient_Widget_color1__Property;
	object->color2 = Usr_CeilingLightPage_ESD_Gradient_Widget_color2__Property;
	object->Manual = Usr_CeilingLightPage_ESD_Gradient_Widget_Manual__Property;
	object->Point_1_X = 0L;
	object->Point_1_Y = 240L;
	object->Point_2_X = 480L;
	object->Point_2_Y = 240L;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CeilingLightPage__Initializer(Usr_CeilingLightPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_CeilingLightPage_CLASSID;
	context->Widget.Slots = &s_Usr_CeilingLightPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->SliderValue = 255L;
	context->LampColor = 0xffffaa00UL;
	context->On = 1;
	context->BackPushed = Esd_Noop;
	Usr_CeilingLightPage__Fixed_Position__Initializer(context);
	Usr_CeilingLightPage__ESD_Image_4__Initializer(context);
	Usr_CeilingLightPage__ESD_Image_3__Initializer(context);
	Usr_CeilingLightPage__ESD_RangeSlider__Initializer(context);
	Usr_CeilingLightPage__ESD_Label__Initializer(context);
	Usr_CeilingLightPage__ESD_Image_Button_2__Initializer(context);
	Usr_CeilingLightPage__ESD_Image_Button__Initializer(context);
	Usr_CeilingLightPage__ESD_Image_2__Initializer(context);
	Usr_CeilingLightPage__ESD_Rectangle_Widget_4__Initializer(context);
	Usr_CeilingLightPage__ESD_Gradient_Widget__Initializer(context);
}

extern int g_CeilingLightValue;
extern int g_CeilingLightIsOn;


void Usr_CeilingLightPage_Update(Usr_CeilingLightPage *context)
{
	void *owner = context->Owner;
	int update_variable = Ft_Esd_RangeSlider_Output(&context->ESD_RangeSlider);
	g_CeilingLightValue = update_variable;
	esd_argb32_t rgb = context->LampColor;
	int a = g_CeilingLightValue;
	esd_argb32_t update_variable_1 = ESD_COMPOSE_RGB_ALPHA(rgb, a);
	context->ESD_Image_3.Color = update_variable_1;
	bool if_1 = context->On;
	esd_argb32_t update_variable_2;
	if (if_1)
	{
		update_variable_2 = 0xff5bce65UL;
	}
	else
	{
		update_variable_2 = 0xffffffffUL;
	}
	context->ESD_Image_Button_2.Color = update_variable_2;
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Usr_CeilingLightPage_End(Usr_CeilingLightPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_RangeSlider); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Gradient_Widget); 
}

void Usr_CeilingLightPage_Start(Usr_CeilingLightPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context); 
	int set_variable_2 = g_CeilingLightValue;
	context->SliderValue = set_variable_2;
	int set_variable_3 = g_CeilingLightIsOn;
	context->On = (int)set_variable_3;
	bool if_2 = context->On;
	if (if_2)
	{
		esd_argb32_t set_variable_5 = 0xffffaa00UL;
		context->LampColor = set_variable_5;
	}
	else
	{
		esd_argb32_t set_variable_5_1 = 0xff969696UL;
		context->LampColor = set_variable_5_1;
	}
}

void Usr_CeilingLightPage_Right(Usr_CeilingLightPage *context)
{
	void *owner = context->Owner;
	int left = Ft_Esd_RangeSlider_Output(&context->ESD_RangeSlider);
	int right = 10L;
	int set_variable_2_1 = left + right;
	context->SliderValue = set_variable_2_1;
}

void Usr_CeilingLightPage_Left(Usr_CeilingLightPage *context)
{
	void *owner = context->Owner;
	int left_1 = Ft_Esd_RangeSlider_Output(&context->ESD_RangeSlider);
	int right_1 = 10L;
	int set_variable_3_1 = left_1 - right_1;
	context->SliderValue = set_variable_3_1;
}

ft_int16_t Usr_CeilingLightPage_ESD_RangeSlider_Value__Property(void *c)
{
	Usr_CeilingLightPage *context = (Usr_CeilingLightPage *)c;
	void *owner = context->Owner;
	return context->SliderValue;
}

void Usr_CeilingLightPage_ESD_Image_Button_2_Pushed__Signal(void *c)
{
	Usr_CeilingLightPage *context = (Usr_CeilingLightPage *)c;
	void *owner = context->Owner;
	bool value = context->On;
	int set_variable = !value;
	context->On = (int)set_variable;
	g_CeilingLightIsOn = set_variable;
	bool if_3 = context->On;
	if (if_3)
	{
		esd_argb32_t set_variable_5_2 = 0xffffaa00UL;
		context->LampColor = set_variable_5_2;
	}
	else
	{
		esd_argb32_t set_variable_5_1_1 = 0xff969696UL;
		context->LampColor = set_variable_5_1_1;
	}
}

void Usr_CeilingLightPage_ESD_Image_Button_Pushed__Signal(void *c)
{
	Usr_CeilingLightPage *context = (Usr_CeilingLightPage *)c;
	void *owner = context->Owner;
	context->BackPushed(owner);
}


/* end of file */
