/*
This file is automatically generated
Usr_Toogle_Theme
C Source
*/

#include "Usr_Toogle_Theme.h"

static Ft_Esd_Theme Usr_Toogle_Theme__Instance = {
	.ClearColor = 0xffffffff,
	.BackColor = 0xffffffff,
	.TextColor = 0xff000000,
	.ButtonTextColor = 0xff000000,
	.DefaultColor = 0xff6b6b6b,
	.PrimaryColor = 0xff5bce65,
};

Ft_Esd_Theme *Usr_Toogle_Theme()
{
	return &Usr_Toogle_Theme__Instance;
}

/* end of file */
