/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_HeatSettingPage
Header
*/

#ifndef Usr_HeatSettingPage__H
#define Usr_HeatSettingPage__H

#include "Esd_Base.h"
#include "Esd_Core.h"
#include "Esd_FontInfo.h"
#include "Ft_Esd.h"
#include "Ft_Esd_BitmapInfo.h"
#include "Ft_Esd_Image.h"
#include "Ft_Esd_ImageButton.h"
#include "Ft_Esd_Label.h"
#include "Ft_Esd_Layout_Fixed.h"
#include "Ft_Esd_NumericLabel.h"
#include "Ft_Esd_PushButton.h"
#include "Ft_Esd_Rectangle.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_Widget.h"
#include "return_circle_64.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Usr_HeatSettingPage_CLASSID 0x09C487F6
ESD_SYMBOL(Usr_HeatSettingPage_CLASSID, Type = esd_classid_t)

ESD_WIDGET(Usr_HeatSettingPage, Include = "Usr_HeatSettingPage.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	int Local_Method__Value;
	ESD_SIGNAL(BackPushed)
	void(* BackPushed)(void *context);
	ESD_VARIABLE(NewValue, Type = int, Private)
	int NewValue;
	Ft_Esd_Layout_Fixed Fixed_Position;
	Ft_Esd_NumericLabel ESD_Numeric_Label;
	Ft_Esd_PushButton ESD_Push_Button_1_1;
	Ft_Esd_PushButton ESD_Push_Button_1;
	Ft_Esd_ImageButton ESD_Image_Button;
	Ft_Esd_Label ESD_Label_1;
	Ft_Esd_Label ESD_Label;
	Ft_Esd_Label ESD_Label_2;
	Ft_Esd_Rectangle Rectangle_Light;
	Ft_Esd_Rectangle Rectangle_Light_1;
	Ft_Esd_Label ESD_Label_2_1;
	Ft_Esd_Rectangle ESD_Rectangle_Widget_4;
	Ft_Esd_Image ESD_Image_1;
	Ft_Esd_Rectangle ESD_Rectangle_Widget;
} Usr_HeatSettingPage;

void Usr_HeatSettingPage__Initializer(Usr_HeatSettingPage *context);

ESD_SLOT(End)
void Usr_HeatSettingPage_End(Usr_HeatSettingPage *context);

ESD_SLOT(Right)
void Usr_HeatSettingPage_Right(Usr_HeatSettingPage *context);

ESD_SLOT(Left)
void Usr_HeatSettingPage_Left(Usr_HeatSettingPage *context);

#endif /* Usr_HeatSettingPage__H */

/* end of file */
