/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_CurtainAdjustPage
C Source
*/

#include "Usr_CurtainAdjustPage.h"

#include "Esd_Context.h"
#include "Usr_GlobalVariables.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);

static int Usr_CurtainAdjustPage_Touch_Area_Width__Property(void *context) { return 320L; }
static int Usr_CurtainAdjustPage_Touch_Area_Height__Property(void *context) { return 480L; }
static uint8_t Usr_CurtainAdjustPage_ESD_Label_Font__Property(void *context) { return 29; }
static const char * Usr_CurtainAdjustPage_ESD_Label_Text__Property(void *context) { return "Curtain Adjustment"; }
static ft_uint16_t Usr_CurtainAdjustPage_ESD_Label_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_uint8_t Usr_CurtainAdjustPage_ESD_Image_Button_MinAlpha__Property(void *context) { return 0; }
static Ft_Esd_BitmapCell Usr_CurtainAdjustPage_ESD_Image_Button_BitmapNormal__Property(void *context) { return return_circle_64_0(); }
static int Usr_CurtainAdjustPage_Line_Widget_linewidth__Property(void *context) { return 10L; }
static ft_argb32_t Usr_CurtainAdjustPage_Line_Widget_color__Property(void *context) { return 0xff004666UL; }
static ft_argb32_t Usr_CurtainAdjustPage_ESD_Gradient_Widget_2_color1__Property(void *context) { return 0xff0f0f0fUL; }
static ft_argb32_t Usr_CurtainAdjustPage_ESD_Gradient_Widget_2_color2__Property(void *context) { return 0xff010101UL; }
static bool Usr_CurtainAdjustPage_ESD_Gradient_Widget_2_Manual__Property(void *context) { return 1; }
static Ft_Esd_BitmapCell Usr_CurtainAdjustPage_RightCurtain_BitmapCell__Property(void *context) { return right_curtain_0(); }
static int Usr_CurtainAdjustPage_Close_Button_PrimaryAlpha__Property(void *context) { return 0L; }
static int Usr_CurtainAdjustPage_Close_Button_Alpha__Property(void *context) { return 0L; }
static uint8_t Usr_CurtainAdjustPage_Percent_Label_Font__Property(void *context) { return 29; }
static const char * Usr_CurtainAdjustPage_Percent_Label_Text__Property(void *context);
static ft_uint16_t Usr_CurtainAdjustPage_Percent_Label_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_uint16_t Usr_CurtainAdjustPage_Percent_Label_AlignY__Property(void *context) { return OPT_ALIGN_CENTER; }
static int Usr_CurtainAdjustPage_Open_Button_PrimaryAlpha__Property(void *context) { return 0L; }
static int Usr_CurtainAdjustPage_Open_Button_Alpha__Property(void *context) { return 0L; }
static Ft_Esd_BitmapCell Usr_CurtainAdjustPage_Curtain_Close_BitmapCell__Property(void *context) { return close_curtain_0(); }
static Ft_Esd_BitmapCell Usr_CurtainAdjustPage_Curtain_Open_BitmapCell__Property(void *context) { return open_curtain_0(); }
static Ft_Esd_BitmapCell Usr_CurtainAdjustPage_newImageScale_BitmapCell__Property(void *context) { return left_curtain_0(); }
static ft_int32_f16_t Usr_CurtainAdjustPage_newImageScale_XScale__Property(void *context);
static ft_argb32_t Usr_CurtainAdjustPage_ESD_Rectangle_Widget_1_Color__Property(void *context) { return 0xffa9ddffUL; }
static ft_argb32_t Usr_CurtainAdjustPage_ESD_Rectangle_Widget_Color__Property(void *context) { return 0xffa9ddffUL; }
static Ft_Esd_BitmapCell Usr_CurtainAdjustPage_ESD_Image_BitmapCell__Property(void *context) { return window4_0(); }
static ft_argb32_t Usr_CurtainAdjustPage_ESD_Gradient_Widget_color1__Property(void *context) { return 0xff414141UL; }
static ft_argb32_t Usr_CurtainAdjustPage_ESD_Gradient_Widget_color2__Property(void *context) { return 0xff010101UL; }
static bool Usr_CurtainAdjustPage_ESD_Gradient_Widget_Manual__Property(void *context) { return 1; }
static ft_int32_t Usr_CurtainAdjustPage_ESD_Rectangle_Widget_4_Radius__Property(void *context) { return 24L; }
static ft_argb32_t Usr_CurtainAdjustPage_ESD_Rectangle_Widget_4_Color__Property(void *context) { return 0x3a47c5ffUL; }
static ft_argb32_t Usr_CurtainAdjustPage_ESD_Rectangle_Widget_2_Color__Property(void *context) { return 0xff171916UL; }

static Ft_Esd_WidgetSlots s_Usr_CurtainAdjustPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Usr_CurtainAdjustPage_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Usr_CurtainAdjustPage_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_CurtainAdjustPage_End,
};

static void Usr_CurtainAdjustPage_Curtain_Timer_Fired__Signal(void *context);
static void Usr_CurtainAdjustPage_LongTap_Timer_Fired__Signal(void *context);
static void Usr_CurtainAdjustPage_Touch_Area_Up__Signal(void *context);
static void Usr_CurtainAdjustPage_Touch_Area_Down__Signal(void *context);
static void Usr_CurtainAdjustPage_ESD_Timer_Fired__Signal(void *context);
static void Usr_CurtainAdjustPage_ScreenSaver_Timeout_Fired__Signal(void *context);
static void Usr_CurtainAdjustPage_ESD_Image_Button_Pushed__Signal(void *context);
static void Usr_CurtainAdjustPage_Close_Button_Down__Signal(void *context);
static void Usr_CurtainAdjustPage_Close_Button_Up__Signal(void *context);
static void Usr_CurtainAdjustPage_Close_Button_Pushed__Signal(void *context);
static void Usr_CurtainAdjustPage_Open_Button_Down__Signal(void *context);
static void Usr_CurtainAdjustPage_Open_Button_Up__Signal(void *context);
static void Usr_CurtainAdjustPage_Open_Button_Pushed__Signal(void *context);

void Usr_CurtainAdjustPage__Curtain_Timer__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_Timer *object = (Ft_Esd_Timer *)&context->Curtain_Timer;
	Ft_Esd_Timer__Initializer(object);
	object->Owner = (void *)context;
	object->TimeoutMs = 200L;
	object->Repeat = 1;
	object->Fired = Usr_CurtainAdjustPage_Curtain_Timer_Fired__Signal;
}

void Usr_CurtainAdjustPage__LongTap_Timer__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_Timer *object = (Ft_Esd_Timer *)&context->LongTap_Timer;
	Ft_Esd_Timer__Initializer(object);
	object->Owner = (void *)context;
	object->TimeoutMs = 2000L;
	object->Fired = Usr_CurtainAdjustPage_LongTap_Timer_Fired__Signal;
}

void Usr_CurtainAdjustPage__Touch_Area__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_TouchArea *object = (Ft_Esd_TouchArea *)&context->Touch_Area;
	Ft_Esd_TouchArea__Initializer(object);
	object->Owner = (void *)context;
	object->Width = Usr_CurtainAdjustPage_Touch_Area_Width__Property;
	object->Height = Usr_CurtainAdjustPage_Touch_Area_Height__Property;
	object->Up = Usr_CurtainAdjustPage_Touch_Area_Up__Signal;
	object->Down = Usr_CurtainAdjustPage_Touch_Area_Down__Signal;
}

void Usr_CurtainAdjustPage__ESD_Timer__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_Timer *object = (Ft_Esd_Timer *)&context->ESD_Timer;
	Ft_Esd_Timer__Initializer(object);
	object->Owner = (void *)context;
	object->TimeoutMs = 10L;
	object->Repeat = 1;
	object->Fired = Usr_CurtainAdjustPage_ESD_Timer_Fired__Signal;
}

void Usr_CurtainAdjustPage__ScreenSaver_Timeout__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_Timer *object = (Ft_Esd_Timer *)&context->ScreenSaver_Timeout;
	Ft_Esd_Timer__Initializer(object);
	object->Owner = (void *)context;
	object->TimeoutMs = 15000L;
	object->Fired = Usr_CurtainAdjustPage_ScreenSaver_Timeout_Fired__Signal;
}

void Usr_CurtainAdjustPage__Fixed_Position__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_CurtainAdjustPage__ESD_Label__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 184;
	object->Widget.LocalY = 45;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_CurtainAdjustPage_ESD_Label_Font__Property;
	object->Text = Usr_CurtainAdjustPage_ESD_Label_Text__Property;
	object->AlignX = Usr_CurtainAdjustPage_ESD_Label_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainAdjustPage__ESD_Image_Button__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 208;
	object->Widget.LocalY = 350;
	object->Widget.LocalWidth = 64;
	object->Widget.LocalHeight = 64;
	object->MinAlpha = Usr_CurtainAdjustPage_ESD_Image_Button_MinAlpha__Property;
	object->BitmapNormal = Usr_CurtainAdjustPage_ESD_Image_Button_BitmapNormal__Property;
	object->Pushed = Usr_CurtainAdjustPage_ESD_Image_Button_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainAdjustPage__Line_Widget__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_Line *object = (Ft_Esd_Line *)&context->Line_Widget;
	Ft_Esd_Line__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 107;
	object->Widget.LocalY = 152;
	object->Widget.LocalWidth = 266;
	object->Widget.LocalHeight = 1;
	object->linewidth = Usr_CurtainAdjustPage_Line_Widget_linewidth__Property;
	object->color = Usr_CurtainAdjustPage_Line_Widget_color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainAdjustPage__ESD_Gradient_Widget_2__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_Gradient *object = (Ft_Esd_Gradient *)&context->ESD_Gradient_Widget_2;
	Ft_Esd_Gradient__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 358;
	object->Widget.LocalY = 155;
	object->Widget.LocalWidth = 122;
	object->Widget.LocalHeight = 160;
	object->color1 = Usr_CurtainAdjustPage_ESD_Gradient_Widget_2_color1__Property;
	object->color2 = Usr_CurtainAdjustPage_ESD_Gradient_Widget_2_color2__Property;
	object->Manual = Usr_CurtainAdjustPage_ESD_Gradient_Widget_2_Manual__Property;
	object->Point_1_X = 360L;
	object->Point_1_Y = 240L;
	object->Point_2_X = 480L;
	object->Point_2_Y = 240L;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainAdjustPage__RightCurtain__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->RightCurtain;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 240;
	object->Widget.LocalY = 157;
	object->Widget.LocalWidth = 116;
	object->Widget.LocalHeight = 157;
	object->Color = 0xff02a6ffUL;
	object->BitmapCell = Usr_CurtainAdjustPage_RightCurtain_BitmapCell__Property;
	object->Scaling = ESD_SCALING_STRETCH;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainAdjustPage__Close_Button__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_TransparentRectButton *object = (Ft_Esd_TransparentRectButton *)&context->Close_Button;
	Ft_Esd_TransparentRectButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 296;
	object->Widget.LocalY = 350;
	object->Widget.LocalWidth = 90;
	object->Widget.LocalHeight = 66;
	object->PrimaryAlpha = Usr_CurtainAdjustPage_Close_Button_PrimaryAlpha__Property;
	object->Alpha = Usr_CurtainAdjustPage_Close_Button_Alpha__Property;
	object->Down = Usr_CurtainAdjustPage_Close_Button_Down__Signal;
	object->Up = Usr_CurtainAdjustPage_Close_Button_Up__Signal;
	object->Pushed = Usr_CurtainAdjustPage_Close_Button_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainAdjustPage__Percent_Label__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Percent_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 150;
	object->Widget.LocalY = 102;
	object->Widget.LocalWidth = 180;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_CurtainAdjustPage_Percent_Label_Font__Property;
	object->Text = Usr_CurtainAdjustPage_Percent_Label_Text__Property;
	object->AlignX = Usr_CurtainAdjustPage_Percent_Label_AlignX__Property;
	object->AlignY = Usr_CurtainAdjustPage_Percent_Label_AlignY__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainAdjustPage__Open_Button__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_TransparentRectButton *object = (Ft_Esd_TransparentRectButton *)&context->Open_Button;
	Ft_Esd_TransparentRectButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 96;
	object->Widget.LocalY = 350;
	object->Widget.LocalWidth = 94;
	object->Widget.LocalHeight = 67;
	object->PrimaryAlpha = Usr_CurtainAdjustPage_Open_Button_PrimaryAlpha__Property;
	object->Alpha = Usr_CurtainAdjustPage_Open_Button_Alpha__Property;
	object->Down = Usr_CurtainAdjustPage_Open_Button_Down__Signal;
	object->Up = Usr_CurtainAdjustPage_Open_Button_Up__Signal;
	object->Pushed = Usr_CurtainAdjustPage_Open_Button_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainAdjustPage__Curtain_Close__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->Curtain_Close;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 296;
	object->Widget.LocalY = 350;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->Color = 0xffffffffUL;
	object->BitmapCell = Usr_CurtainAdjustPage_Curtain_Close_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainAdjustPage__Curtain_Open__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->Curtain_Open;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 96;
	object->Widget.LocalY = 350;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->Color = 0xffffffffUL;
	object->BitmapCell = Usr_CurtainAdjustPage_Curtain_Open_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainAdjustPage__newImageScale__Initializer(Usr_CurtainAdjustPage *context)
{
	newImageScale *object = (newImageScale *)&context->newImageScale;
	newImageScale__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 124;
	object->Widget.LocalY = 157;
	object->Widget.LocalWidth = 116;
	object->Widget.LocalHeight = 157;
	object->BitmapCell = Usr_CurtainAdjustPage_newImageScale_BitmapCell__Property;
	object->XScale = Usr_CurtainAdjustPage_newImageScale_XScale__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainAdjustPage__ESD_Rectangle_Widget_1__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget_1;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 124;
	object->Widget.LocalY = 157;
	object->Widget.LocalWidth = 116;
	object->Widget.LocalHeight = 157;
	object->Color = Usr_CurtainAdjustPage_ESD_Rectangle_Widget_1_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainAdjustPage__ESD_Rectangle_Widget__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 240;
	object->Widget.LocalY = 157;
	object->Widget.LocalWidth = 116;
	object->Widget.LocalHeight = 157;
	object->Color = Usr_CurtainAdjustPage_ESD_Rectangle_Widget_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainAdjustPage__ESD_Image__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 127;
	object->Widget.LocalY = 162;
	object->Widget.LocalWidth = 227;
	object->Widget.LocalHeight = 137;
	object->BitmapCell = Usr_CurtainAdjustPage_ESD_Image_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainAdjustPage__ESD_Gradient_Widget__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_Gradient *object = (Ft_Esd_Gradient *)&context->ESD_Gradient_Widget;
	Ft_Esd_Gradient__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 480;
	object->Widget.LocalHeight = 480;
	object->color1 = Usr_CurtainAdjustPage_ESD_Gradient_Widget_color1__Property;
	object->color2 = Usr_CurtainAdjustPage_ESD_Gradient_Widget_color2__Property;
	object->Manual = Usr_CurtainAdjustPage_ESD_Gradient_Widget_Manual__Property;
	object->Point_1_X = 0L;
	object->Point_1_Y = 240L;
	object->Point_2_X = 480L;
	object->Point_2_Y = 240L;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainAdjustPage__ESD_Rectangle_Widget_4__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget_4;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 121;
	object->Widget.LocalY = 36;
	object->Widget.LocalWidth = 248;
	object->Widget.LocalHeight = 48;
	object->Radius = Usr_CurtainAdjustPage_ESD_Rectangle_Widget_4_Radius__Property;
	object->Color = Usr_CurtainAdjustPage_ESD_Rectangle_Widget_4_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainAdjustPage__ESD_Rectangle_Widget_2__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget_2;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 0;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 480;
	object->Widget.LocalHeight = 480;
	object->Color = Usr_CurtainAdjustPage_ESD_Rectangle_Widget_2_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_CurtainAdjustPage__Initializer(Usr_CurtainAdjustPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_CurtainAdjustPage_CLASSID;
	context->Widget.Slots = &s_Usr_CurtainAdjustPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->PercentageClosed = 100L;
	context->Open_Color = 0xffffffffUL;
	context->Delta = 0L;
	context->isLongTap = 0;
	context->Control_Color = 0xffffffffUL;
	context->Close_Color = 0xffffffffUL;
	context->Timeout = Esd_Noop;
	context->UserTouch = Esd_Noop;
	context->X = 80L;
	context->Angle = 0L;
	context->BackPushed = Esd_Noop;
	context->Radius = 0L;
	Usr_CurtainAdjustPage__Curtain_Timer__Initializer(context);
	Usr_CurtainAdjustPage__LongTap_Timer__Initializer(context);
	Usr_CurtainAdjustPage__Touch_Area__Initializer(context);
	Usr_CurtainAdjustPage__ESD_Timer__Initializer(context);
	Usr_CurtainAdjustPage__ScreenSaver_Timeout__Initializer(context);
	Usr_CurtainAdjustPage__Fixed_Position__Initializer(context);
	Usr_CurtainAdjustPage__ESD_Label__Initializer(context);
	Usr_CurtainAdjustPage__ESD_Image_Button__Initializer(context);
	Usr_CurtainAdjustPage__Line_Widget__Initializer(context);
	Usr_CurtainAdjustPage__ESD_Gradient_Widget_2__Initializer(context);
	Usr_CurtainAdjustPage__RightCurtain__Initializer(context);
	Usr_CurtainAdjustPage__Close_Button__Initializer(context);
	Usr_CurtainAdjustPage__Percent_Label__Initializer(context);
	Usr_CurtainAdjustPage__Open_Button__Initializer(context);
	Usr_CurtainAdjustPage__Curtain_Close__Initializer(context);
	Usr_CurtainAdjustPage__Curtain_Open__Initializer(context);
	Usr_CurtainAdjustPage__newImageScale__Initializer(context);
	Usr_CurtainAdjustPage__ESD_Rectangle_Widget_1__Initializer(context);
	Usr_CurtainAdjustPage__ESD_Rectangle_Widget__Initializer(context);
	Usr_CurtainAdjustPage__ESD_Image__Initializer(context);
	Usr_CurtainAdjustPage__ESD_Gradient_Widget__Initializer(context);
	Usr_CurtainAdjustPage__ESD_Rectangle_Widget_4__Initializer(context);
	Usr_CurtainAdjustPage__ESD_Rectangle_Widget_2__Initializer(context);
}

static int Usr_CurtainAdjustPage_GetPercentage__return(Usr_CurtainAdjustPage *context);

extern int g_CurtainOpenPercentage;

void UpdatePercentage(Usr_CurtainAdjustPage *context);
void LongTap_Detected(Usr_CurtainAdjustPage *context);
int GetPercentage();
char *GetTextDisplay(int);
void Usr_CurtainAdjustPage_SetPercemtage_Signal(Usr_CurtainAdjustPage *context);
void Usr_CurtainAdjustPage_Update_Signal(Usr_CurtainAdjustPage *context);

void Usr_CurtainAdjustPage_Update__Builtin(Usr_CurtainAdjustPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Timer_Update(&context->Curtain_Timer);
	Ft_Esd_Timer_Update(&context->LongTap_Timer);
	Ft_Esd_Timer_Update(&context->ESD_Timer);
	Ft_Esd_Timer_Update(&context->ScreenSaver_Timeout);
	int left = 356L;
	ft_int32_f16_t left_1 = (116L * (1L << 16) + 0x0L);
	int left_2 = Usr_CurtainAdjustPage_GetPercentage__return(context);
	ft_int32_f16_t right_2 = (100L * (1L << 16) + 0x0L);
	ft_int32_f16_t right_1 = (ft_int32_f16_t)((((int64_t)left_2) << 32) / ((int64_t)right_2));
	ft_int32_f16_t right = (ft_int32_f16_t)(((int64_t)left_1) * ((int64_t)right_1) >> 16);
	int update_variable = left - (right >> 16);
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->RightCurtain, update_variable);
	int left_3 = Usr_CurtainAdjustPage_GetPercentage__return(context);
	ft_int32_f16_t right_3 = (100L * (1L << 16) + 0x0L);
	ft_int32_f16_t update_variable_1 = (ft_int32_f16_t)((((int64_t)left_3) << 32) / ((int64_t)right_3));
	context->RightCurtain.ScaleX = update_variable_1;
	ft_argb32_t update_variable_2 = context->Close_Color;
	context->Curtain_Close.Color = update_variable_2;
	ft_argb32_t update_variable_3 = context->Open_Color;
	context->Curtain_Open.Color = update_variable_3;
	ft_int32_f16_t left_5 = (116L * (1L << 16) + 0x0L);
	int left_6 = Usr_CurtainAdjustPage_GetPercentage__return(context);
	ft_int32_f16_t right_5 = (100L * (1L << 16) + 0x0L);
	ft_int32_f16_t right_4 = (ft_int32_f16_t)((((int64_t)left_6) << 32) / ((int64_t)right_5));
	ft_int32_f16_t left_4 = (ft_int32_f16_t)(((int64_t)left_5) * ((int64_t)right_4) >> 16);
	int right_6 = 0L;
	int update_variable_4 = (left_4 >> 16) - right_6;
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget_1, update_variable_4);
	ft_int16_t update_variable_5 = context->RightCurtain.Widget.LocalX;
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget, update_variable_5);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Usr_CurtainAdjustPage_End(Usr_CurtainAdjustPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Timer_End(&context->Curtain_Timer);
	Ft_Esd_Timer_End(&context->LongTap_Timer);
	Ft_Esd_Timer_End(&context->ESD_Timer);
	Ft_Esd_Timer_End(&context->ScreenSaver_Timeout);
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Line_Widget); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Gradient_Widget_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->RightCurtain); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Close_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Percent_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Open_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Curtain_Close); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Curtain_Open); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->newImageScale); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Gradient_Widget); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget_2); 
}

void Usr_CurtainAdjustPage_Right(Usr_CurtainAdjustPage *context)
{
	void *owner = context->Owner;
	ft_bool_t if_1 = context->isLongTap;
	if (if_1)
	{
		Ft_Esd_Timer_Halt(&context->Curtain_Timer);
		Ft_Esd_Timer_Halt(&context->LongTap_Timer);
		int reset_delta = 0L;
		context->Delta = reset_delta;
		ft_bool_t reset_longtap = 0;
		context->isLongTap = reset_longtap;
		Ft_Esd_Timer_Halt(&context->ESD_Timer);
		int disable_busy_state = 0L;
		context->Radius = disable_busy_state;
	}
	else
	{
		int set_variable = -1L;
		context->Delta = set_variable;
		Ft_Esd_Timer_Run(&context->Curtain_Timer);
		int left_9 = Usr_CurtainAdjustPage_GetPercentage__return(context);
		int right_7 = 0L;
		int left_8 = left_9 > right_7;
		int left_10 = context->Delta;
		int right_9 = -1L;
		int right_8 = left_10 == right_9;
		int left_7 = left_8 && right_8;
		int left_12 = context->Delta;
		int right_11 = 1L;
		int left_11 = left_12 == right_11;
		int left_13 = Usr_CurtainAdjustPage_GetPercentage__return(context);
		int right_13 = 100L;
		int right_12 = left_13 < right_13;
		int right_10 = left_11 && right_12;
		int if_2 = left_7 || right_10;
		if (if_2)
		{
			UpdatePercentage(context);
			int set_variable_3 = Usr_CurtainAdjustPage_GetPercentage__return(context);
			g_CurtainOpenPercentage = set_variable_3;
			Ft_Esd_Timer_Run(&context->ScreenSaver_Timeout);
		}
		else
		{
			ft_argb32_t set_open_color_white = 0xffffffffUL;
			context->Open_Color = set_open_color_white;
			int reset_delta_1 = 0L;
			context->Delta = reset_delta_1;
			ft_bool_t reset_longtap_1 = 0;
			context->isLongTap = reset_longtap_1;
			Ft_Esd_Timer_Halt(&context->ESD_Timer);
			int disable_busy_state_1 = 0L;
			context->Radius = disable_busy_state_1;
			ft_argb32_t set_close_white = 0xffffffffUL;
			context->Close_Color = set_close_white;
		}
		Ft_Esd_Timer_Run(&context->LongTap_Timer);
		ft_bool_t set_long_tap = 1;
		context->isLongTap = set_long_tap;
		LongTap_Detected(context);
		Ft_Esd_Timer_Run(&context->ESD_Timer);
		int enable_busy_state = 70L;
		context->Radius = enable_busy_state;
		ft_bool_t set_long_tap_1 = 1;
		context->isLongTap = set_long_tap_1;
		LongTap_Detected(context);
		Ft_Esd_Timer_Run(&context->ESD_Timer);
		int enable_busy_state_1 = 70L;
		context->Radius = enable_busy_state_1;
	}
}

void Usr_CurtainAdjustPage_Left(Usr_CurtainAdjustPage *context)
{
	void *owner = context->Owner;
	ft_bool_t if_3 = context->isLongTap;
	if (if_3)
	{
		Ft_Esd_Timer_Halt(&context->Curtain_Timer);
		Ft_Esd_Timer_Halt(&context->LongTap_Timer);
		int reset_delta_2 = 0L;
		context->Delta = reset_delta_2;
		ft_bool_t reset_longtap_2 = 0;
		context->isLongTap = reset_longtap_2;
		Ft_Esd_Timer_Halt(&context->ESD_Timer);
		int disable_busy_state_2 = 0L;
		context->Radius = disable_busy_state_2;
	}
	else
	{
		int set_variable_1 = 1L;
		context->Delta = set_variable_1;
		Ft_Esd_Timer_Run(&context->Curtain_Timer);
		int left_16 = Usr_CurtainAdjustPage_GetPercentage__return(context);
		int right_14 = 0L;
		int left_15 = left_16 > right_14;
		int left_17 = context->Delta;
		int right_16 = -1L;
		int right_15 = left_17 == right_16;
		int left_14 = left_15 && right_15;
		int left_19 = context->Delta;
		int right_18 = 1L;
		int left_18 = left_19 == right_18;
		int left_20 = Usr_CurtainAdjustPage_GetPercentage__return(context);
		int right_20 = 100L;
		int right_19 = left_20 < right_20;
		int right_17 = left_18 && right_19;
		int if_4 = left_14 || right_17;
		if (if_4)
		{
			UpdatePercentage(context);
			int set_variable_3_1 = Usr_CurtainAdjustPage_GetPercentage__return(context);
			g_CurtainOpenPercentage = set_variable_3_1;
			Ft_Esd_Timer_Run(&context->ScreenSaver_Timeout);
		}
		else
		{
			ft_argb32_t set_open_color_white_1 = 0xffffffffUL;
			context->Open_Color = set_open_color_white_1;
			int reset_delta_3 = 0L;
			context->Delta = reset_delta_3;
			ft_bool_t reset_longtap_3 = 0;
			context->isLongTap = reset_longtap_3;
			Ft_Esd_Timer_Halt(&context->ESD_Timer);
			int disable_busy_state_3 = 0L;
			context->Radius = disable_busy_state_3;
			ft_argb32_t set_close_white_1 = 0xffffffffUL;
			context->Close_Color = set_close_white_1;
		}
		Ft_Esd_Timer_Run(&context->LongTap_Timer);
		ft_bool_t set_long_tap_2 = 1;
		context->isLongTap = set_long_tap_2;
		LongTap_Detected(context);
		Ft_Esd_Timer_Run(&context->ESD_Timer);
		int enable_busy_state_2 = 70L;
		context->Radius = enable_busy_state_2;
	}
}

int Usr_CurtainAdjustPage_GetPercentage__return(Usr_CurtainAdjustPage *context)
{
	void *owner = context->Owner;
	return GetPercentage();
}

void Usr_CurtainAdjustPage_SetPercemtage(Usr_CurtainAdjustPage *context)
{
	void *owner = context->Owner;
	Usr_CurtainAdjustPage_SetPercemtage_Signal(context);
}

void Usr_CurtainAdjustPage_Start(Usr_CurtainAdjustPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context); 
	int set_variable_2 = g_CurtainOpenPercentage;
	context->PercentageClosed = set_variable_2;
	Ft_Esd_Timer_Run(&context->ScreenSaver_Timeout);
}

void Usr_CurtainAdjustPage_Update(Usr_CurtainAdjustPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchArea_Update(&context->Touch_Area);
	Usr_CurtainAdjustPage_Update_Signal(context);
	Usr_CurtainAdjustPage_Update__Builtin(context);
}

void Usr_CurtainAdjustPage_Curtain_Timer_Fired__Signal(void *c)
{
	Usr_CurtainAdjustPage *context = (Usr_CurtainAdjustPage *)c;
	void *owner = context->Owner;
	int left_23 = Usr_CurtainAdjustPage_GetPercentage__return(context);
	int right_21 = 0L;
	int left_22 = left_23 > right_21;
	int left_24 = context->Delta;
	int right_23 = -1L;
	int right_22 = left_24 == right_23;
	int left_21 = left_22 && right_22;
	int left_26 = context->Delta;
	int right_25 = 1L;
	int left_25 = left_26 == right_25;
	int left_27 = Usr_CurtainAdjustPage_GetPercentage__return(context);
	int right_27 = 100L;
	int right_26 = left_27 < right_27;
	int right_24 = left_25 && right_26;
	int if_5 = left_21 || right_24;
	if (if_5)
	{
		UpdatePercentage(context);
		int set_variable_3_2 = Usr_CurtainAdjustPage_GetPercentage__return(context);
		g_CurtainOpenPercentage = set_variable_3_2;
		Ft_Esd_Timer_Run(&context->ScreenSaver_Timeout);
	}
	else
	{
		ft_argb32_t set_open_color_white_2 = 0xffffffffUL;
		context->Open_Color = set_open_color_white_2;
		int reset_delta_4 = 0L;
		context->Delta = reset_delta_4;
		ft_bool_t reset_longtap_4 = 0;
		context->isLongTap = reset_longtap_4;
		Ft_Esd_Timer_Halt(&context->ESD_Timer);
		int disable_busy_state_4 = 0L;
		context->Radius = disable_busy_state_4;
		ft_argb32_t set_close_white_2 = 0xffffffffUL;
		context->Close_Color = set_close_white_2;
	}
}

void Usr_CurtainAdjustPage_LongTap_Timer_Fired__Signal(void *c)
{
	Usr_CurtainAdjustPage *context = (Usr_CurtainAdjustPage *)c;
	void *owner = context->Owner;
	ft_bool_t set_long_tap_3 = 1;
	context->isLongTap = set_long_tap_3;
	LongTap_Detected(context);
	Ft_Esd_Timer_Run(&context->ESD_Timer);
	int enable_busy_state_3 = 70L;
	context->Radius = enable_busy_state_3;
}

void Usr_CurtainAdjustPage_Touch_Area_Up__Signal(void *c)
{
	Usr_CurtainAdjustPage *context = (Usr_CurtainAdjustPage *)c;
	void *owner = context->Owner;
	Ft_Esd_Timer_Run(&context->ScreenSaver_Timeout);
}

void Usr_CurtainAdjustPage_Touch_Area_Down__Signal(void *c)
{
	Usr_CurtainAdjustPage *context = (Usr_CurtainAdjustPage *)c;
	void *owner = context->Owner;
	Ft_Esd_Timer_Halt(&context->ScreenSaver_Timeout);
	int left_28 = context->ScreenSaver_Timeout.RemainingMs;
	int right_28 = 0L;
	int if_6 = left_28 == right_28;
	if (if_6)
	{
		Ft_Esd_Timer_Run(&context->ScreenSaver_Timeout);
		context->UserTouch(owner);
	}
	else
	{
	}
}

void Usr_CurtainAdjustPage_ESD_Timer_Fired__Signal(void *c)
{
	Usr_CurtainAdjustPage *context = (Usr_CurtainAdjustPage *)c;
	void *owner = context->Owner;
	int left_29 = context->Angle;
	int right_29 = 400L;
	int update_angle = left_29 + right_29;
	context->Angle = update_angle;
}

void Usr_CurtainAdjustPage_ScreenSaver_Timeout_Fired__Signal(void *c)
{
	Usr_CurtainAdjustPage *context = (Usr_CurtainAdjustPage *)c;
	void *owner = context->Owner;
	context->Timeout(owner);
}

void Usr_CurtainAdjustPage_ESD_Image_Button_Pushed__Signal(void *c)
{
	Usr_CurtainAdjustPage *context = (Usr_CurtainAdjustPage *)c;
	void *owner = context->Owner;
	context->BackPushed(owner);
}

void Usr_CurtainAdjustPage_Close_Button_Down__Signal(void *c)
{
	Usr_CurtainAdjustPage *context = (Usr_CurtainAdjustPage *)c;
	void *owner = context->Owner;
	int left_30 = Usr_CurtainAdjustPage_GetPercentage__return(context);
	int right_30 = 100L;
	int if_7 = left_30 < right_30;
	if (if_7)
	{
		int set_delta_increase = 1L;
		context->Delta = set_delta_increase;
		ft_argb32_t set_open_color_white_3 = 0xffffffffUL;
		context->Open_Color = set_open_color_white_3;
		Ft_Esd_Timer_Run(&context->Curtain_Timer);
		int left_33 = Usr_CurtainAdjustPage_GetPercentage__return(context);
		int right_31 = 0L;
		int left_32 = left_33 > right_31;
		int left_34 = context->Delta;
		int right_33 = -1L;
		int right_32 = left_34 == right_33;
		int left_31 = left_32 && right_32;
		int left_36 = context->Delta;
		int right_35 = 1L;
		int left_35 = left_36 == right_35;
		int left_37 = Usr_CurtainAdjustPage_GetPercentage__return(context);
		int right_37 = 100L;
		int right_36 = left_37 < right_37;
		int right_34 = left_35 && right_36;
		int if_8 = left_31 || right_34;
		if (if_8)
		{
			UpdatePercentage(context);
			int set_variable_3_3 = Usr_CurtainAdjustPage_GetPercentage__return(context);
			g_CurtainOpenPercentage = set_variable_3_3;
			Ft_Esd_Timer_Run(&context->ScreenSaver_Timeout);
		}
		else
		{
			ft_argb32_t set_open_color_white_4 = 0xffffffffUL;
			context->Open_Color = set_open_color_white_4;
			int reset_delta_5 = 0L;
			context->Delta = reset_delta_5;
			ft_bool_t reset_longtap_5 = 0;
			context->isLongTap = reset_longtap_5;
			Ft_Esd_Timer_Halt(&context->ESD_Timer);
			int disable_busy_state_5 = 0L;
			context->Radius = disable_busy_state_5;
			ft_argb32_t set_close_white_3 = 0xffffffffUL;
			context->Close_Color = set_close_white_3;
		}
		Ft_Esd_Timer_Run(&context->LongTap_Timer);
		ft_bool_t reset_longtap_6 = 0;
		context->isLongTap = reset_longtap_6;
		Ft_Esd_Timer_Halt(&context->ESD_Timer);
		int disable_busy_state_6 = 0L;
		context->Radius = disable_busy_state_6;
		ft_argb32_t set_close_blue = 0xff0000ffUL;
		context->Close_Color = set_close_blue;
		int set_close_x = 240L;
		context->X = set_close_x;
	}
	else
	{
		int reset_delta_6 = 0L;
		context->Delta = reset_delta_6;
		ft_bool_t reset_longtap_7 = 0;
		context->isLongTap = reset_longtap_7;
		Ft_Esd_Timer_Halt(&context->ESD_Timer);
		int disable_busy_state_7 = 0L;
		context->Radius = disable_busy_state_7;
		ft_argb32_t set_close_red = 0xffff0000UL;
		context->Close_Color = set_close_red;
	}
}

void Usr_CurtainAdjustPage_Close_Button_Up__Signal(void *c)
{
	Usr_CurtainAdjustPage *context = (Usr_CurtainAdjustPage *)c;
	void *owner = context->Owner;
	ft_bool_t if_9 = context->isLongTap;
	if (if_9)
	{
	}
	else
	{
		Ft_Esd_Timer_Halt(&context->Curtain_Timer);
		Ft_Esd_Timer_Halt(&context->LongTap_Timer);
		ft_argb32_t set_close_white_4 = 0xffffffffUL;
		context->Close_Color = set_close_white_4;
	}
}

void Usr_CurtainAdjustPage_Close_Button_Pushed__Signal(void *c)
{
	Usr_CurtainAdjustPage *context = (Usr_CurtainAdjustPage *)c;
	void *owner = context->Owner;
	Ft_Esd_Timer_Run(&context->ScreenSaver_Timeout);
}

const char * Usr_CurtainAdjustPage_Percent_Label_Text__Property(void *c)
{
	Usr_CurtainAdjustPage *context = (Usr_CurtainAdjustPage *)c;
	void *owner = context->Owner;
	int percentage = Usr_CurtainAdjustPage_GetPercentage__return(context);
	return GetTextDisplay(percentage);
}

void Usr_CurtainAdjustPage_Open_Button_Down__Signal(void *c)
{
	Usr_CurtainAdjustPage *context = (Usr_CurtainAdjustPage *)c;
	void *owner = context->Owner;
	int left_38 = Usr_CurtainAdjustPage_GetPercentage__return(context);
	int right_38 = 0L;
	int if_10 = left_38 > right_38;
	if (if_10)
	{
		int set_delta_decrease = -1L;
		context->Delta = set_delta_decrease;
		ft_argb32_t set_open_color_blue = 0xff0000ffUL;
		context->Open_Color = set_open_color_blue;
		Ft_Esd_Timer_Run(&context->Curtain_Timer);
		int left_41 = Usr_CurtainAdjustPage_GetPercentage__return(context);
		int right_39 = 0L;
		int left_40 = left_41 > right_39;
		int left_42 = context->Delta;
		int right_41 = -1L;
		int right_40 = left_42 == right_41;
		int left_39 = left_40 && right_40;
		int left_44 = context->Delta;
		int right_43 = 1L;
		int left_43 = left_44 == right_43;
		int left_45 = Usr_CurtainAdjustPage_GetPercentage__return(context);
		int right_45 = 100L;
		int right_44 = left_45 < right_45;
		int right_42 = left_43 && right_44;
		int if_11 = left_39 || right_42;
		if (if_11)
		{
			UpdatePercentage(context);
			int set_variable_3_4 = Usr_CurtainAdjustPage_GetPercentage__return(context);
			g_CurtainOpenPercentage = set_variable_3_4;
			Ft_Esd_Timer_Run(&context->ScreenSaver_Timeout);
		}
		else
		{
			ft_argb32_t set_open_color_white_5 = 0xffffffffUL;
			context->Open_Color = set_open_color_white_5;
			int reset_delta_7 = 0L;
			context->Delta = reset_delta_7;
			ft_bool_t reset_longtap_8 = 0;
			context->isLongTap = reset_longtap_8;
			Ft_Esd_Timer_Halt(&context->ESD_Timer);
			int disable_busy_state_8 = 0L;
			context->Radius = disable_busy_state_8;
			ft_argb32_t set_close_white_5 = 0xffffffffUL;
			context->Close_Color = set_close_white_5;
		}
		Ft_Esd_Timer_Run(&context->LongTap_Timer);
		ft_bool_t reset_longtap_9 = 0;
		context->isLongTap = reset_longtap_9;
		Ft_Esd_Timer_Halt(&context->ESD_Timer);
		int disable_busy_state_9 = 0L;
		context->Radius = disable_busy_state_9;
		ft_argb32_t set_close_white_6 = 0xffffffffUL;
		context->Close_Color = set_close_white_6;
		int set_open_x = 80L;
		context->X = set_open_x;
	}
	else
	{
		ft_argb32_t set_open_color_red = 0xffff0000UL;
		context->Open_Color = set_open_color_red;
		int reset_delta_8 = 0L;
		context->Delta = reset_delta_8;
		ft_bool_t reset_longtap_10 = 0;
		context->isLongTap = reset_longtap_10;
		Ft_Esd_Timer_Halt(&context->ESD_Timer);
		int disable_busy_state_10 = 0L;
		context->Radius = disable_busy_state_10;
	}
}

void Usr_CurtainAdjustPage_Open_Button_Up__Signal(void *c)
{
	Usr_CurtainAdjustPage *context = (Usr_CurtainAdjustPage *)c;
	void *owner = context->Owner;
	ft_bool_t if_12 = context->isLongTap;
	if (if_12)
	{
	}
	else
	{
		ft_argb32_t set_open_color_white_6 = 0xffffffffUL;
		context->Open_Color = set_open_color_white_6;
		Ft_Esd_Timer_Halt(&context->Curtain_Timer);
		Ft_Esd_Timer_Halt(&context->LongTap_Timer);
	}
}

void Usr_CurtainAdjustPage_Open_Button_Pushed__Signal(void *c)
{
	Usr_CurtainAdjustPage *context = (Usr_CurtainAdjustPage *)c;
	void *owner = context->Owner;
	Ft_Esd_Timer_Run(&context->ScreenSaver_Timeout);
}

ft_int32_f16_t Usr_CurtainAdjustPage_newImageScale_XScale__Property(void *c)
{
	Usr_CurtainAdjustPage *context = (Usr_CurtainAdjustPage *)c;
	void *owner = context->Owner;
	int left_49 = Usr_CurtainAdjustPage_GetPercentage__return(context);
	ft_int32_f16_t right_46 = (100L * (1L << 16) + 0x0L);
	ft_int32_f16_t left_48 = (ft_int32_f16_t)((((int64_t)left_49) << 32) / ((int64_t)right_46));
	ft_int32_f16_t right_47 = (14L * (1L << 16) + 0x8000L);
	ft_int32_f16_t left_47 = (ft_int32_f16_t)(((int64_t)left_48) * ((int64_t)right_47) >> 16);
	ft_int32_f16_t right_48 = (10L * (1L << 16) + 0x0L);
	ft_int32_f16_t left_46 = (ft_int32_f16_t)((((int64_t)left_47) << 16) / ((int64_t)right_48));
	ft_int32_f16_t right_49 = (0L * (1L << 16) + 0x28fL);
	return left_46 + right_49;
}


/* end of file */
