/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_Vertical_ScrollText
C Source
*/

#include "Usr_Vertical_ScrollText.h"

#include "Esd_Context.h"
#include "EVE_Hal.h"
#include "Esd_BitmapHandle.h"
#include "Ft_Esd_BitmapHandle.h"
#include "Ft_Esd_CoCmd.h"
#include "Ft_Esd_Dl.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
ft_uint8_t Usr_Vertical_ScrollText_Alpha__Default(void *context) { return 255; }
Ft_Esd_Theme * Usr_Vertical_ScrollText_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
uint8_t Usr_Vertical_ScrollText_Font__Default(void *context) { return 27; }
Esd_FontInfo * Usr_Vertical_ScrollText_FontResource__Default(void *context) { return 0; }


static Ft_Esd_WidgetSlots s_Usr_Vertical_ScrollText__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Usr_Vertical_ScrollText_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Usr_Vertical_ScrollText_Update,
	(void(*)(void *))Usr_Vertical_ScrollText_Render,
	(void(*)(void *))Usr_Vertical_ScrollText_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_Vertical_ScrollText_End,
};

static void Usr_Vertical_ScrollText_ESD_Timer_Fired__Signal(void *context);

void Usr_Vertical_ScrollText__ESD_Timer__Initializer(Usr_Vertical_ScrollText *context)
{
	Ft_Esd_Timer *object = (Ft_Esd_Timer *)&context->ESD_Timer;
	Ft_Esd_Timer__Initializer(object);
	object->Owner = (void *)context;
	object->TimeoutMs = 5L;
	object->Repeat = 1;
	object->Fired = Usr_Vertical_ScrollText_ESD_Timer_Fired__Signal;
}

void Usr_Vertical_ScrollText__Fixed_Positioning__Initializer(Usr_Vertical_ScrollText *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Positioning;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 139;
	object->Widget.LocalY = 201;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_Vertical_ScrollText__Initializer(Usr_Vertical_ScrollText *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_Vertical_ScrollText_CLASSID;
	context->Widget.Slots = &s_Usr_Vertical_ScrollText__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 8;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Alpha = Usr_Vertical_ScrollText_Alpha__Default;
	context->Theme = Usr_Vertical_ScrollText_Theme__Default;
	context->Value = 0L;
	context->nextValue = 200L;
	context->currentValue = 100L;
	context->baseLine = 0U;
	context->capsHeight = 0U;
	context->Font = Usr_Vertical_ScrollText_Font__Default;
	context->FontResource = Usr_Vertical_ScrollText_FontResource__Default;
	context->xOffset = 0U;
	context->myFont = 0U;
	Usr_Vertical_ScrollText__ESD_Timer__Initializer(context);
	Usr_Vertical_ScrollText__Fixed_Positioning__Initializer(context);
}

static uint8_t Usr_Vertical_ScrollText_Setup_Font__return(Usr_Vertical_ScrollText *context);

void Usr_Vertical_ScrollText_Start_Signal(Usr_Vertical_ScrollText *context);
void Usr_Vertical_ScrollText_ESD_Timer_Fired(Usr_Vertical_ScrollText *context);
void Usr_Vertical_ScrollText_Render_Signal(Usr_Vertical_ScrollText *context);
ESD_CORE_EXPORT uint16_t Esd_GetFontBaseLine(Esd_FontInfo *);
ESD_CORE_EXPORT Esd_FontInfo *Esd_GetRomFont(uint8_t);
ESD_CORE_EXPORT uint16_t Esd_GetFontCapsHeight(Esd_FontInfo *);
ESD_CORE_EXPORT uint16_t Esd_GetFontXOffset(Esd_FontInfo *);

static ft_rgb32_t Usr_Vertical_ScrollText_Local_Method(Usr_Vertical_ScrollText *context, ft_argb32_t x);

void Usr_Vertical_ScrollText_Update__Builtin(Usr_Vertical_ScrollText *context)
{
	void *owner = context->Owner;
	uint16_t left = context->capsHeight;
	int right = 2L;
	int update_variable = left + right;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)context, update_variable);
	Esd_FontInfo * if_1 = context->FontResource(owner);
	Esd_FontInfo *fontInfo;
	if (if_1)
	{
		fontInfo = context->FontResource(owner);
	}
	else
	{
		uint8_t i = context->Font(owner);
		fontInfo = Esd_GetRomFont(i);
	}
	uint16_t update_variable_1 = Esd_GetFontBaseLine(fontInfo);
	context->baseLine = update_variable_1;
	Esd_FontInfo * if_2 = context->FontResource(owner);
	Esd_FontInfo *fontInfo_1;
	if (if_2)
	{
		fontInfo_1 = context->FontResource(owner);
	}
	else
	{
		uint8_t i_1 = context->Font(owner);
		fontInfo_1 = Esd_GetRomFont(i_1);
	}
	uint16_t update_variable_2 = Esd_GetFontCapsHeight(fontInfo_1);
	context->capsHeight = update_variable_2;
	Esd_FontInfo * if_3 = context->FontResource(owner);
	Esd_FontInfo *fontInfo_2;
	if (if_3)
	{
		fontInfo_2 = context->FontResource(owner);
	}
	else
	{
		uint8_t i_2 = context->Font(owner);
		fontInfo_2 = Esd_GetRomFont(i_2);
	}
	uint16_t update_variable_3 = Esd_GetFontXOffset(fontInfo_2);
	context->xOffset = update_variable_3;
	uint8_t update_variable_4 = Usr_Vertical_ScrollText_Setup_Font__return(context);
	context->myFont = update_variable_4;
	Ft_Esd_Timer_Update(&context->ESD_Timer);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Usr_Vertical_ScrollText_End__Builtin(Usr_Vertical_ScrollText *context)
{
	void *owner = context->Owner;
	Ft_Esd_Timer_End(&context->ESD_Timer);
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Positioning); 
}

static ft_rgb32_t Usr_Vertical_ScrollText_Local_Method(Usr_Vertical_ScrollText *context, ft_argb32_t x)
{
	void *owner = context->Owner;
	x &=0xffffff;
	return x;
}

void Usr_Vertical_ScrollText_Start(Usr_Vertical_ScrollText *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context); 
	Usr_Vertical_ScrollText_Start_Signal(context);
	Ft_Esd_Timer_Run(&context->ESD_Timer);
}

void Usr_Vertical_ScrollText_Update(Usr_Vertical_ScrollText *context)
{
	void *owner = context->Owner;
	Usr_Vertical_ScrollText_Update__Builtin(context);
}

void Usr_Vertical_ScrollText_Render(Usr_Vertical_ScrollText *context)
{
	void *owner = context->Owner;
	ft_uint8_t alpha = context->Alpha(owner);
	Ft_Esd_Dl_COLOR_A(alpha);
	Ft_Esd_Theme * theme = context->Theme(owner);
	ft_argb32_t x = Ft_Esd_Theme_GetTextColor(theme);
	ft_rgb32_t c_1 = Usr_Vertical_ScrollText_Local_Method(context, x);
	Ft_Esd_Dl_COLOR_RGB(c_1);
	EVE_HalContext * phost = Ft_Esd_GetHost();
	ft_int16_t x_1 = 0;
	ft_int16_t y = 0;
	uint8_t font = Usr_Vertical_ScrollText_Setup_Font__return(context);
	uint16_t options = 0;
	ft_bool_t bottom = 0;
	ft_int16_t baseLine_1 = 0;
	ft_int16_t capsHeight_1 = 0;
	ft_int16_t xOffset_1 = 0;
	const ft_char8_t * s = "";
	Ft_Gpu_CoCmd_Text_Ex(phost, x_1, y, font, options, bottom, baseLine_1, capsHeight_1, xOffset_1, s);
	Usr_Vertical_ScrollText_Render_Signal(context);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

void Usr_Vertical_ScrollText_Idle(Usr_Vertical_ScrollText *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Idle((Ft_Esd_Widget *)context); 
}

void Usr_Vertical_ScrollText_End(Usr_Vertical_ScrollText *context)
{
	void *owner = context->Owner;
	Usr_Vertical_ScrollText_End__Builtin(context);
}

uint8_t Usr_Vertical_ScrollText_Setup_Font__return(Usr_Vertical_ScrollText *context)
{
	void *owner = context->Owner;
	Esd_FontInfo * if_4 = context->FontResource(owner);
	Esd_FontInfo *fontInfo_3;
	if (if_4)
	{
		fontInfo_3 = context->FontResource(owner);
	}
	else
	{
		uint8_t i_3 = context->Font(owner);
		fontInfo_3 = Esd_GetRomFont(i_3);
	}
	return Ft_Esd_Dl_Font_Setup(fontInfo_3);
}

void Usr_Vertical_ScrollText_ESD_Timer_Fired__Signal(void *c)
{
	Usr_Vertical_ScrollText *context = (Usr_Vertical_ScrollText *)c;
	void *owner = context->Owner;
	Usr_Vertical_ScrollText_ESD_Timer_Fired(context);
}


/* end of file */
