/*
This file is automatically generated
Usr_Toogle_Theme
Header
*/

#ifndef Usr_Toogle_Theme__H
#define Usr_Toogle_Theme__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_Theme.h"

ESD_FUNCTION(Usr_Toogle_Theme, Type = Ft_Esd_Theme *, Include = "Usr_Toogle_Theme.h", Category = _GroupUserResources, Icon = ":/icons/palette.png")
Ft_Esd_Theme *Usr_Toogle_Theme();

#endif /* Usr_Toogle_Theme__H */

/* end of file */
