/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_Time_Actor
C Source
*/

#include "Usr_Time_Actor.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);


static void Usr_Time_Actor_ESD_Timer_Fired__Signal(void *context);

void Usr_Time_Actor__ESD_Timer__Initializer(Usr_Time_Actor *context)
{
	Ft_Esd_Timer *object = (Ft_Esd_Timer *)&context->ESD_Timer;
	Ft_Esd_Timer__Initializer(object);
	object->Owner = (void *)context;
	object->Repeat = 1;
	object->Fired = Usr_Time_Actor_ESD_Timer_Fired__Signal;
}

void Usr_Time_Actor__Initializer(Usr_Time_Actor *context)
{
	context->Owner = 0;
	context->totalSeconds = 29730L;
	Usr_Time_Actor__ESD_Timer__Initializer(context);
}

void Usr_Time_Actor_Update(Usr_Time_Actor *context)
{
	void *owner = context->Owner;
	Ft_Esd_Timer_Update(&context->ESD_Timer);
}

void Usr_Time_Actor_End(Usr_Time_Actor *context)
{
	void *owner = context->Owner;
	Ft_Esd_Timer_End(&context->ESD_Timer);
}

void Usr_Time_Actor_Start(Usr_Time_Actor *context)
{
	void *owner = context->Owner;
	Ft_Esd_Timer_Run(&context->ESD_Timer);
}

int Usr_Time_Actor_Hour(Usr_Time_Actor *context)
{
	void *owner = context->Owner;
	int left = context->totalSeconds;
	int right = 3600L;
	return left / right;
}

int Usr_Time_Actor_Minute(Usr_Time_Actor *context)
{
	void *owner = context->Owner;
	int left_2 = context->totalSeconds;
	int right_1 = 3600L;
	int left_1 = left_2 % right_1;
	int right_2 = 60L;
	return left_1 / right_2;
}

int Usr_Time_Actor_Second(Usr_Time_Actor *context)
{
	void *owner = context->Owner;
	int left_3 = context->totalSeconds;
	int right_3 = 60L;
	return left_3 % right_3;
}

void Usr_Time_Actor_ESD_Timer_Fired__Signal(void *c)
{
	Usr_Time_Actor *context = (Usr_Time_Actor *)c;
	void *owner = context->Owner;
	int left_4 = context->totalSeconds;
	int right_4 = 86400L;
	int if_1 = left_4 >= right_4;
	if (if_1)
	{
		int set_variable_2 = 1L;
		context->totalSeconds = set_variable_2;
	}
	else
	{
		int left_5 = context->totalSeconds;
		int right_5 = 1L;
		int set_variable_2_1 = left_5 + right_5;
		context->totalSeconds = set_variable_2_1;
	}
}


/* end of file */
