/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_PowerPage
Header
*/

#ifndef Usr_PowerPage__H
#define Usr_PowerPage__H

#include "Esd_Base.h"
#include "Esd_Core.h"
#include "Esd_FontInfo.h"
#include "FloorHeatOn.h"
#include "Ft_Esd.h"
#include "Ft_Esd_BitmapInfo.h"
#include "Ft_Esd_Image.h"
#include "Ft_Esd_ImageButton.h"
#include "Ft_Esd_Label.h"
#include "Ft_Esd_Layout_Fixed.h"
#include "Ft_Esd_NumericLabel.h"
#include "Ft_Esd_RangeSlider.h"
#include "Ft_Esd_Rectangle.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_Theme_DarkOrange.h"
#include "Ft_Esd_Widget.h"
#include "return_circle_64.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Usr_PowerPage_CLASSID 0x67C3979A
ESD_SYMBOL(Usr_PowerPage_CLASSID, Type = esd_classid_t)

ESD_WIDGET(Usr_PowerPage, Include = "Usr_PowerPage.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_VARIABLE(SliderValue, Type = int, Default = 255, Private)
	int SliderValue;
	ESD_SIGNAL(BackPushed)
	void(* BackPushed)(void *context);
	Ft_Esd_Layout_Fixed Fixed_Position;
	Ft_Esd_Label ESD_Label_3_1;
	Ft_Esd_Label ESD_Label_3;
	Ft_Esd_NumericLabel ESD_Numeric_Label_1;
	Ft_Esd_NumericLabel ESD_Numeric_Label;
	Ft_Esd_Label ESD_Label_2_1;
	Ft_Esd_Label ESD_Label_2;
	Ft_Esd_RangeSlider ESD_RangeSlider;
	Ft_Esd_Label ESD_Label;
	Ft_Esd_ImageButton ESD_Image_Button;
	Ft_Esd_Image ESD_Image_2;
	Ft_Esd_Rectangle ESD_Rectangle_Widget_4;
} Usr_PowerPage;

void Usr_PowerPage__Initializer(Usr_PowerPage *context);

ESD_SLOT(Update)
void Usr_PowerPage_Update(Usr_PowerPage *context);

ESD_SLOT(End)
void Usr_PowerPage_End(Usr_PowerPage *context);

ESD_SLOT(Start)
void Usr_PowerPage_Start(Usr_PowerPage *context);

ESD_SLOT(Right)
void Usr_PowerPage_Right(Usr_PowerPage *context);

ESD_SLOT(Left)
void Usr_PowerPage_Left(Usr_PowerPage *context);

#endif /* Usr_PowerPage__H */

/* end of file */
