/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_LivingroomLightPage
C Source
*/

#include "Usr_LivingroomLightPage.h"

#include "Esd_Context.h"
#include "Usr_GlobalVariables.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);

static int Usr_LivingroomLightPage_ESD_Line_Widget_2_linewidth__Property(void *context) { return 14L; }
static ft_argb32_t Usr_LivingroomLightPage_ESD_Line_Widget_2_color__Property(void *context) { return 0xff5b5b5bUL; }
static Ft_Esd_Theme * Usr_LivingroomLightPage_ESD_RangeSlider_Theme__Property(void *context) { return Ft_Esd_Theme_DarkOrange(); }
static ft_int16_t Usr_LivingroomLightPage_ESD_RangeSlider_Min__Property(void *context) { return 75; }
static ft_int16_t Usr_LivingroomLightPage_ESD_RangeSlider_Max__Property(void *context) { return 255; }
static ft_int16_t Usr_LivingroomLightPage_ESD_RangeSlider_Step__Property(void *context) { return 10; }
static ft_int16_t Usr_LivingroomLightPage_ESD_RangeSlider_Value__Property(void *context);
static uint8_t Usr_LivingroomLightPage_ESD_Label_Font__Property(void *context) { return 29; }
static const char * Usr_LivingroomLightPage_ESD_Label_Text__Property(void *context) { return "Livingroom Light"; }
static ft_uint16_t Usr_LivingroomLightPage_ESD_Label_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_uint8_t Usr_LivingroomLightPage_ESD_Image_Button_2_MinAlpha__Property(void *context) { return 0; }
static Ft_Esd_BitmapCell Usr_LivingroomLightPage_ESD_Image_Button_2_BitmapNormal__Property(void *context) { return power_circle_64_0(); }
static ft_uint8_t Usr_LivingroomLightPage_ESD_Image_Button_MinAlpha__Property(void *context) { return 0; }
static Ft_Esd_BitmapCell Usr_LivingroomLightPage_ESD_Image_Button_BitmapNormal__Property(void *context) { return return_circle_64_0(); }
static Ft_Esd_BitmapCell Usr_LivingroomLightPage_ESD_Image_2_BitmapCell__Property(void *context) { return livingroom_light_case_0(); }
static int Usr_LivingroomLightPage_ESD_Line_Widget_linewidth__Property(void *context) { return 11L; }
static ft_argb32_t Usr_LivingroomLightPage_ESD_Line_Widget_color__Property(void *context) { return 0xff5b5b5bUL; }
static ft_int32_t Usr_LivingroomLightPage_ESD_Rectangle_Widget_4_Radius__Property(void *context) { return 24L; }
static ft_argb32_t Usr_LivingroomLightPage_ESD_Rectangle_Widget_4_Color__Property(void *context) { return 0x59000000UL; }
static ft_argb32_t Usr_LivingroomLightPage_ESD_Gradient_Widget_color1__Property(void *context) { return 0xff414141UL; }
static ft_argb32_t Usr_LivingroomLightPage_ESD_Gradient_Widget_color2__Property(void *context) { return 0xff010101UL; }
static bool Usr_LivingroomLightPage_ESD_Gradient_Widget_Manual__Property(void *context) { return 1; }

static Ft_Esd_WidgetSlots s_Usr_LivingroomLightPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Usr_LivingroomLightPage_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Usr_LivingroomLightPage_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_LivingroomLightPage_End,
};

static void Usr_LivingroomLightPage_ESD_Image_Button_2_Pushed__Signal(void *context);
static void Usr_LivingroomLightPage_ESD_Image_Button_Pushed__Signal(void *context);

void Usr_LivingroomLightPage__Fixed_Position__Initializer(Usr_LivingroomLightPage *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_LivingroomLightPage__ESD_Line_Widget_2__Initializer(Usr_LivingroomLightPage *context)
{
	Ft_Esd_Line *object = (Ft_Esd_Line *)&context->ESD_Line_Widget_2;
	Ft_Esd_Line__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 158;
	object->Widget.LocalY = 181;
	object->Widget.LocalWidth = 164;
	object->Widget.LocalHeight = 0;
	object->linewidth = Usr_LivingroomLightPage_ESD_Line_Widget_2_linewidth__Property;
	object->color = Usr_LivingroomLightPage_ESD_Line_Widget_2_color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LivingroomLightPage__ESD_RangeSlider__Initializer(Usr_LivingroomLightPage *context)
{
	Ft_Esd_RangeSlider *object = (Ft_Esd_RangeSlider *)&context->ESD_RangeSlider;
	Ft_Esd_RangeSlider__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 132;
	object->Widget.LocalY = 238;
	object->Widget.LocalWidth = 220;
	object->Widget.LocalHeight = 39;
	object->Theme = Usr_LivingroomLightPage_ESD_RangeSlider_Theme__Property;
	object->Min = Usr_LivingroomLightPage_ESD_RangeSlider_Min__Property;
	object->Max = Usr_LivingroomLightPage_ESD_RangeSlider_Max__Property;
	object->Step = Usr_LivingroomLightPage_ESD_RangeSlider_Step__Property;
	object->Value = Usr_LivingroomLightPage_ESD_RangeSlider_Value__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LivingroomLightPage__ESD_Label__Initializer(Usr_LivingroomLightPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 152;
	object->Widget.LocalY = 404;
	object->Widget.LocalWidth = 180;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_LivingroomLightPage_ESD_Label_Font__Property;
	object->Text = Usr_LivingroomLightPage_ESD_Label_Text__Property;
	object->AlignX = Usr_LivingroomLightPage_ESD_Label_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LivingroomLightPage__ESD_Image_Button_2__Initializer(Usr_LivingroomLightPage *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button_2;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 124;
	object->Widget.LocalY = 310;
	object->Widget.LocalWidth = 64;
	object->Widget.LocalHeight = 64;
	object->MinAlpha = Usr_LivingroomLightPage_ESD_Image_Button_2_MinAlpha__Property;
	object->BitmapNormal = Usr_LivingroomLightPage_ESD_Image_Button_2_BitmapNormal__Property;
	object->Pushed = Usr_LivingroomLightPage_ESD_Image_Button_2_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LivingroomLightPage__ESD_Image_Button__Initializer(Usr_LivingroomLightPage *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 296;
	object->Widget.LocalY = 310;
	object->Widget.LocalWidth = 64;
	object->Widget.LocalHeight = 64;
	object->MinAlpha = Usr_LivingroomLightPage_ESD_Image_Button_MinAlpha__Property;
	object->BitmapNormal = Usr_LivingroomLightPage_ESD_Image_Button_BitmapNormal__Property;
	object->Pushed = Usr_LivingroomLightPage_ESD_Image_Button_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LivingroomLightPage__ESD_Image_2__Initializer(Usr_LivingroomLightPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_2;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 158;
	object->Widget.LocalY = 70;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->BitmapCell = Usr_LivingroomLightPage_ESD_Image_2_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LivingroomLightPage__ESD_Circle___Initializer(Usr_LivingroomLightPage *context)
{
	Ft_Esd_Circle *object = (Ft_Esd_Circle *)&context->ESD_Circle_;
	Ft_Esd_Circle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 202;
	object->Widget.LocalY = 148;
	object->Widget.LocalWidth = 76;
	object->Widget.LocalHeight = 76;
	object->Color = 0xffffce29UL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LivingroomLightPage__ESD_Line_Widget__Initializer(Usr_LivingroomLightPage *context)
{
	Ft_Esd_Line *object = (Ft_Esd_Line *)&context->ESD_Line_Widget;
	Ft_Esd_Line__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 241;
	object->Widget.LocalY = 48;
	object->Widget.LocalWidth = 0;
	object->Widget.LocalHeight = 20;
	object->linewidth = Usr_LivingroomLightPage_ESD_Line_Widget_linewidth__Property;
	object->color = Usr_LivingroomLightPage_ESD_Line_Widget_color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LivingroomLightPage__ESD_Rectangle_Widget_4__Initializer(Usr_LivingroomLightPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget_4;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 119;
	object->Widget.LocalY = 394;
	object->Widget.LocalWidth = 238;
	object->Widget.LocalHeight = 48;
	object->Radius = Usr_LivingroomLightPage_ESD_Rectangle_Widget_4_Radius__Property;
	object->Color = Usr_LivingroomLightPage_ESD_Rectangle_Widget_4_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LivingroomLightPage__ESD_Gradient_Widget__Initializer(Usr_LivingroomLightPage *context)
{
	Ft_Esd_Gradient *object = (Ft_Esd_Gradient *)&context->ESD_Gradient_Widget;
	Ft_Esd_Gradient__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 480;
	object->Widget.LocalHeight = 480;
	object->color1 = Usr_LivingroomLightPage_ESD_Gradient_Widget_color1__Property;
	object->color2 = Usr_LivingroomLightPage_ESD_Gradient_Widget_color2__Property;
	object->Manual = Usr_LivingroomLightPage_ESD_Gradient_Widget_Manual__Property;
	object->Point_1_X = 0L;
	object->Point_1_Y = 240L;
	object->Point_2_X = 480L;
	object->Point_2_Y = 240L;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_LivingroomLightPage__Initializer(Usr_LivingroomLightPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_LivingroomLightPage_CLASSID;
	context->Widget.Slots = &s_Usr_LivingroomLightPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->SliderValue_1 = 255L;
	context->LampColor = 0xffffaa00UL;
	context->On = 1;
	context->BackPushed = Esd_Noop;
	Usr_LivingroomLightPage__Fixed_Position__Initializer(context);
	Usr_LivingroomLightPage__ESD_Line_Widget_2__Initializer(context);
	Usr_LivingroomLightPage__ESD_RangeSlider__Initializer(context);
	Usr_LivingroomLightPage__ESD_Label__Initializer(context);
	Usr_LivingroomLightPage__ESD_Image_Button_2__Initializer(context);
	Usr_LivingroomLightPage__ESD_Image_Button__Initializer(context);
	Usr_LivingroomLightPage__ESD_Image_2__Initializer(context);
	Usr_LivingroomLightPage__ESD_Circle___Initializer(context);
	Usr_LivingroomLightPage__ESD_Line_Widget__Initializer(context);
	Usr_LivingroomLightPage__ESD_Rectangle_Widget_4__Initializer(context);
	Usr_LivingroomLightPage__ESD_Gradient_Widget__Initializer(context);
}

extern int g_LivingRoomLightValue;
extern int g_LivingRoomLightIsOn;


void Usr_LivingroomLightPage_Update(Usr_LivingroomLightPage *context)
{
	void *owner = context->Owner;
	int update_variable = Ft_Esd_RangeSlider_Output(&context->ESD_RangeSlider);
	g_LivingRoomLightValue = update_variable;
	bool if_1 = context->On;
	esd_argb32_t update_variable_1;
	if (if_1)
	{
		update_variable_1 = 0xff5bce65UL;
	}
	else
	{
		update_variable_1 = 0xffffffffUL;
	}
	context->ESD_Image_Button_2.Color = update_variable_1;
	esd_argb32_t rgb = context->LampColor;
	int a = g_LivingRoomLightValue;
	esd_argb32_t update_variable_2 = ESD_COMPOSE_RGB_ALPHA(rgb, a);
	context->ESD_Circle_.Color = update_variable_2;
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Usr_LivingroomLightPage_End(Usr_LivingroomLightPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Line_Widget_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_RangeSlider); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Circle_); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Line_Widget); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Gradient_Widget); 
}

void Usr_LivingroomLightPage_Start(Usr_LivingroomLightPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context); 
	int set_variable_2_2 = g_LivingRoomLightValue;
	context->SliderValue_1 = set_variable_2_2;
	int set_variable_3 = g_LivingRoomLightIsOn;
	context->On = (int)set_variable_3;
	bool if_2 = context->On;
	if (if_2)
	{
		esd_argb32_t set_variable_5 = 0xffffaa00UL;
		context->LampColor = set_variable_5;
	}
	else
	{
		esd_argb32_t set_variable_5_1 = 0xff969696UL;
		context->LampColor = set_variable_5_1;
	}
}

void Usr_LivingroomLightPage_Right(Usr_LivingroomLightPage *context)
{
	void *owner = context->Owner;
	int left = Ft_Esd_RangeSlider_Output(&context->ESD_RangeSlider);
	int right = 10L;
	int set_variable_2_1 = left + right;
	context->SliderValue_1 = set_variable_2_1;
}

void Usr_LivingroomLightPage_Left(Usr_LivingroomLightPage *context)
{
	void *owner = context->Owner;
	int left_1 = Ft_Esd_RangeSlider_Output(&context->ESD_RangeSlider);
	int right_1 = 10L;
	int set_variable_3_1_1 = left_1 - right_1;
	context->SliderValue_1 = set_variable_3_1_1;
}

ft_int16_t Usr_LivingroomLightPage_ESD_RangeSlider_Value__Property(void *c)
{
	Usr_LivingroomLightPage *context = (Usr_LivingroomLightPage *)c;
	void *owner = context->Owner;
	return context->SliderValue_1;
}

void Usr_LivingroomLightPage_ESD_Image_Button_2_Pushed__Signal(void *c)
{
	Usr_LivingroomLightPage *context = (Usr_LivingroomLightPage *)c;
	void *owner = context->Owner;
	bool value = context->On;
	int set_variable = !value;
	context->On = (int)set_variable;
	g_LivingRoomLightIsOn = set_variable;
	bool if_3 = context->On;
	if (if_3)
	{
		esd_argb32_t set_variable_5_2 = 0xffffaa00UL;
		context->LampColor = set_variable_5_2;
	}
	else
	{
		esd_argb32_t set_variable_5_1_1 = 0xff969696UL;
		context->LampColor = set_variable_5_1_1;
	}
}

void Usr_LivingroomLightPage_ESD_Image_Button_Pushed__Signal(void *c)
{
	Usr_LivingroomLightPage *context = (Usr_LivingroomLightPage *)c;
	void *owner = context->Owner;
	context->BackPushed(owner);
}


/* end of file */
