/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_AirConWidget
Header
*/

#ifndef Usr_AirConWidget__H
#define Usr_AirConWidget__H

#include "Esd_Base.h"
#include "Ft_Esd.h"
#include "Ft_Esd_Circle.h"
#include "Ft_Esd_Layout_Fixed.h"
#include "Ft_Esd_Line.h"
#include "Ft_Esd_Math.h"
#include "Ft_Esd_Rectangle.h"
#include "Ft_Esd_Widget.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Usr_AirConWidget_CLASSID 0x52AD052E
ESD_SYMBOL(Usr_AirConWidget_CLASSID, Type = esd_classid_t)

ESD_WIDGET(Usr_AirConWidget, Include = "Usr_AirConWidget.h", Callback, X = 0, Y = 1, Width = 107, Height = 84)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_VARIABLE(On, Type = bool, Default = true, Public)
	bool On;
	Ft_Esd_Layout_Fixed Fixed_Positioning;
	Ft_Esd_Line ESD_Line_Widget_1_2;
	Ft_Esd_Line ESD_Line_Widget_1_1;
	Ft_Esd_Line ESD_Line_Widget_1;
	Ft_Esd_Line ESD_Line_Widget;
	Ft_Esd_Rectangle ESD_Rectangle_Widget_2;
	Ft_Esd_Circle ESD_Circle__1;
	Ft_Esd_Circle ESD_Circle_;
	Ft_Esd_Rectangle AirConCase;
} Usr_AirConWidget;

void Usr_AirConWidget__Initializer(Usr_AirConWidget *context);

ESD_SLOT(Update)
void Usr_AirConWidget_Update(Usr_AirConWidget *context);

ESD_SLOT(End)
void Usr_AirConWidget_End(Usr_AirConWidget *context);

#endif /* Usr_AirConWidget__H */

/* end of file */
