/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_Spin_Image
C Source
*/

#include "Usr_Spin_Image.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);

static Ft_Esd_BitmapCell Usr_Spin_Image_ESD_Image_Rotate_BitmapCell__Property(void *context);

static Ft_Esd_WidgetSlots s_Usr_Spin_Image__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Usr_Spin_Image_Update,
	(void(*)(void *))Usr_Spin_Image_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_Spin_Image_End,
};


void Usr_Spin_Image__ESD_Image_Rotate__Initializer(Usr_Spin_Image *context)
{
	Ft_Esd_Image_Rotate *object = (Ft_Esd_Image_Rotate *)&context->ESD_Image_Rotate;
	Ft_Esd_Image_Rotate__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 130;
	object->Widget.LocalY = 44;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	object->BitmapCell = Usr_Spin_Image_ESD_Image_Rotate_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_Spin_Image__Initializer(Usr_Spin_Image *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_Spin_Image_CLASSID;
	context->Widget.Slots = &s_Usr_Spin_Image__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->BitmapCell = (Esd_BitmapCell){ 0 };
	context->Angle = 0L;
	context->Speed = 0L;
	Usr_Spin_Image__ESD_Image_Rotate__Initializer(context);
}

void Usr_Spin_Image_Render_Signal(Usr_Spin_Image *context);

void Usr_Spin_Image_Update(Usr_Spin_Image *context)
{
	void *owner = context->Owner;
	ft_int16_t update_variable = context->Widget.GlobalX;
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ESD_Image_Rotate, update_variable);
	ft_int16_t update_variable_1 = context->Widget.GlobalY;
	Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->ESD_Image_Rotate, update_variable_1);
	ft_int16_t update_variable_2 = context->Widget.GlobalWidth;
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->ESD_Image_Rotate, update_variable_2);
	ft_int16_t update_variable_3 = context->Widget.GlobalHeight;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->ESD_Image_Rotate, update_variable_3);
	int update_variable_4 = context->Angle;
	context->ESD_Image_Rotate.RotateAngle = update_variable_4;
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Usr_Spin_Image_End(Usr_Spin_Image *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Rotate); 
}

void Usr_Spin_Image_Render(Usr_Spin_Image *context)
{
	void *owner = context->Owner;
	Usr_Spin_Image_Render_Signal(context);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

Ft_Esd_BitmapCell Usr_Spin_Image_ESD_Image_Rotate_BitmapCell__Property(void *c)
{
	Usr_Spin_Image *context = (Usr_Spin_Image *)c;
	void *owner = context->Owner;
	return context->BitmapCell;
}


/* end of file */
