/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_AirConPage
C Source
*/

#include "Usr_AirConPage.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);

static ft_argb32_t Usr_AirConPage_ESD_Touch_Panel_3_Color__Property(void *context) { return 0x181818UL; }
static ft_argb32_t Usr_AirConPage_ESD_Touch_Panel_2_Color__Property(void *context) { return 0x181818UL; }
static ft_argb32_t Usr_AirConPage_ESD_Touch_Panel_1_Color__Property(void *context) { return 0x181818UL; }
static ft_argb32_t Usr_AirConPage_ESD_Touch_Panel_Color__Property(void *context) { return 0x181818UL; }
static Ft_Esd_BitmapCell Usr_AirConPage_ESD_Image_1_1_1_BitmapCell__Property(void *context) { return humid_icon_0(); }
static Ft_Esd_BitmapCell Usr_AirConPage_ESD_Image_1_1_BitmapCell__Property(void *context) { return fan_icon_0(); }
static Ft_Esd_BitmapCell Usr_AirConPage_ESD_Image_1_BitmapCell__Property(void *context) { return heat_icon_0(); }
static Ft_Esd_BitmapCell Usr_AirConPage_ESD_Image_BitmapCell__Property(void *context) { return snow_icon_0(); }
static const char * Usr_AirConPage_ESD_Label_2_1_1_1_Text__Property(void *context) { return "Fan"; }
static ft_uint16_t Usr_AirConPage_ESD_Label_2_1_1_1_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static const char * Usr_AirConPage_ESD_Label_2_1_1_Text__Property(void *context) { return "Heat"; }
static ft_uint16_t Usr_AirConPage_ESD_Label_2_1_1_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static const char * Usr_AirConPage_ESD_Label_2_1_Text__Property(void *context) { return "Cool"; }
static ft_uint16_t Usr_AirConPage_ESD_Label_2_1_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static const char * Usr_AirConPage_ESD_Label_2_Text__Property(void *context) { return "Humid"; }
static ft_uint16_t Usr_AirConPage_ESD_Label_2_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static Ft_Esd_Theme * Usr_AirConPage_Humid_Button_Theme__Property(void *context) { return Ft_Esd_Theme_LightBlue(); }
static const char * Usr_AirConPage_Humid_Button_Text__Property(void *context) { return ""; }
static Ft_Esd_Theme * Usr_AirConPage_Fan_Button_Theme__Property(void *context) { return Ft_Esd_Theme_LightBlue(); }
static const char * Usr_AirConPage_Fan_Button_Text__Property(void *context) { return ""; }
static Ft_Esd_Theme * Usr_AirConPage_Heat_Button_Theme__Property(void *context) { return Ft_Esd_Theme_LightBlue(); }
static const char * Usr_AirConPage_Heat_Button_Text__Property(void *context) { return ""; }
static Ft_Esd_Theme * Usr_AirConPage_Cool_Button_Theme__Property(void *context) { return Ft_Esd_Theme_LightBlue(); }
static const char * Usr_AirConPage_Cool_Button_Text__Property(void *context) { return ""; }
static uint8_t Usr_AirConPage_ESD_Label_Font__Property(void *context) { return 30; }
static const char * Usr_AirConPage_ESD_Label_Text__Property(void *context) { return "Air conditioner"; }
static ft_int32_t Usr_AirConPage_ESD_Rectangle_Widget_4_Radius__Property(void *context) { return 24L; }
static ft_argb32_t Usr_AirConPage_ESD_Rectangle_Widget_4_Color__Property(void *context) { return 0x59000000UL; }

static Ft_Esd_WidgetSlots s_Usr_AirConPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_AirConPage_End,
};

static void Usr_AirConPage_ESD_Touch_Panel_3_Tap__Signal(void *context);
static void Usr_AirConPage_ESD_Touch_Panel_2_Tap__Signal(void *context);
static void Usr_AirConPage_ESD_Touch_Panel_1_Tap__Signal(void *context);
static void Usr_AirConPage_ESD_Touch_Panel_Tap__Signal(void *context);

void Usr_AirConPage__Fixed_Position__Initializer(Usr_AirConPage *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_AirConPage__ESD_Touch_Panel_3__Initializer(Usr_AirConPage *context)
{
	Ft_Esd_TouchPanel *object = (Ft_Esd_TouchPanel *)&context->ESD_Touch_Panel_3;
	Ft_Esd_TouchPanel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 325;
	object->Widget.LocalY = 278;
	object->Widget.LocalWidth = 78;
	object->Widget.LocalHeight = 98;
	object->Color = Usr_AirConPage_ESD_Touch_Panel_3_Color__Property;
	object->Tap = Usr_AirConPage_ESD_Touch_Panel_3_Tap__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_AirConPage__ESD_Touch_Panel_2__Initializer(Usr_AirConPage *context)
{
	Ft_Esd_TouchPanel *object = (Ft_Esd_TouchPanel *)&context->ESD_Touch_Panel_2;
	Ft_Esd_TouchPanel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 242;
	object->Widget.LocalY = 278;
	object->Widget.LocalWidth = 78;
	object->Widget.LocalHeight = 98;
	object->Color = Usr_AirConPage_ESD_Touch_Panel_2_Color__Property;
	object->Tap = Usr_AirConPage_ESD_Touch_Panel_2_Tap__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_AirConPage__ESD_Touch_Panel_1__Initializer(Usr_AirConPage *context)
{
	Ft_Esd_TouchPanel *object = (Ft_Esd_TouchPanel *)&context->ESD_Touch_Panel_1;
	Ft_Esd_TouchPanel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 76;
	object->Widget.LocalY = 278;
	object->Widget.LocalWidth = 78;
	object->Widget.LocalHeight = 98;
	object->Color = Usr_AirConPage_ESD_Touch_Panel_1_Color__Property;
	object->Tap = Usr_AirConPage_ESD_Touch_Panel_1_Tap__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_AirConPage__ESD_Touch_Panel__Initializer(Usr_AirConPage *context)
{
	Ft_Esd_TouchPanel *object = (Ft_Esd_TouchPanel *)&context->ESD_Touch_Panel;
	Ft_Esd_TouchPanel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 159;
	object->Widget.LocalY = 278;
	object->Widget.LocalWidth = 78;
	object->Widget.LocalHeight = 98;
	object->Color = Usr_AirConPage_ESD_Touch_Panel_Color__Property;
	object->Tap = Usr_AirConPage_ESD_Touch_Panel_Tap__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_AirConPage__ESD_Image_1_1_1__Initializer(Usr_AirConPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_1_1_1;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 347;
	object->Widget.LocalY = 292;
	object->Widget.LocalWidth = 41;
	object->Widget.LocalHeight = 39;
	object->Color = 0xff0044ffUL;
	object->BitmapCell = Usr_AirConPage_ESD_Image_1_1_1_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_AirConPage__ESD_Image_1_1__Initializer(Usr_AirConPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_1_1;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 262;
	object->Widget.LocalY = 295;
	object->Widget.LocalWidth = 41;
	object->Widget.LocalHeight = 39;
	object->BitmapCell = Usr_AirConPage_ESD_Image_1_1_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_AirConPage__ESD_Image_1__Initializer(Usr_AirConPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_1;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 171;
	object->Widget.LocalY = 290;
	object->Widget.LocalWidth = 41;
	object->Widget.LocalHeight = 39;
	object->Color = 0xfff06e00UL;
	object->BitmapCell = Usr_AirConPage_ESD_Image_1_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_AirConPage__ESD_Image__Initializer(Usr_AirConPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 93;
	object->Widget.LocalY = 292;
	object->Widget.LocalWidth = 41;
	object->Widget.LocalHeight = 39;
	object->BitmapCell = Usr_AirConPage_ESD_Image_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_AirConPage__ESD_Label_2_1_1_1__Initializer(Usr_AirConPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2_1_1_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 242;
	object->Widget.LocalY = 350;
	object->Widget.LocalWidth = 78;
	object->Widget.LocalHeight = 36;
	object->Text = Usr_AirConPage_ESD_Label_2_1_1_1_Text__Property;
	object->AlignX = Usr_AirConPage_ESD_Label_2_1_1_1_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_AirConPage__ESD_Label_2_1_1__Initializer(Usr_AirConPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2_1_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 159;
	object->Widget.LocalY = 350;
	object->Widget.LocalWidth = 78;
	object->Widget.LocalHeight = 36;
	object->Text = Usr_AirConPage_ESD_Label_2_1_1_Text__Property;
	object->AlignX = Usr_AirConPage_ESD_Label_2_1_1_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_AirConPage__ESD_Label_2_1__Initializer(Usr_AirConPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 76;
	object->Widget.LocalY = 350;
	object->Widget.LocalWidth = 78;
	object->Widget.LocalHeight = 36;
	object->Text = Usr_AirConPage_ESD_Label_2_1_Text__Property;
	object->AlignX = Usr_AirConPage_ESD_Label_2_1_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_AirConPage__ESD_Label_2__Initializer(Usr_AirConPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 325;
	object->Widget.LocalY = 350;
	object->Widget.LocalWidth = 78;
	object->Widget.LocalHeight = 36;
	object->Text = Usr_AirConPage_ESD_Label_2_Text__Property;
	object->AlignX = Usr_AirConPage_ESD_Label_2_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_AirConPage__Humid_Button__Initializer(Usr_AirConPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Humid_Button;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 325;
	object->Widget.LocalY = 278;
	object->Widget.LocalWidth = 78;
	object->Widget.LocalHeight = 98;
	object->Theme = Usr_AirConPage_Humid_Button_Theme__Property;
	object->Text = Usr_AirConPage_Humid_Button_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_AirConPage__Fan_Button__Initializer(Usr_AirConPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Fan_Button;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 242;
	object->Widget.LocalY = 278;
	object->Widget.LocalWidth = 78;
	object->Widget.LocalHeight = 98;
	object->Theme = Usr_AirConPage_Fan_Button_Theme__Property;
	object->Text = Usr_AirConPage_Fan_Button_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_AirConPage__Heat_Button__Initializer(Usr_AirConPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Heat_Button;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 159;
	object->Widget.LocalY = 278;
	object->Widget.LocalWidth = 78;
	object->Widget.LocalHeight = 98;
	object->Theme = Usr_AirConPage_Heat_Button_Theme__Property;
	object->Text = Usr_AirConPage_Heat_Button_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_AirConPage__Cool_Button__Initializer(Usr_AirConPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->Cool_Button;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 76;
	object->Widget.LocalY = 278;
	object->Widget.LocalWidth = 78;
	object->Widget.LocalHeight = 98;
	object->Theme = Usr_AirConPage_Cool_Button_Theme__Property;
	object->Text = Usr_AirConPage_Cool_Button_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_AirConPage__Usr_AirConWidget__Initializer(Usr_AirConPage *context)
{
	Usr_AirConWidget *object = (Usr_AirConWidget *)&context->Usr_AirConWidget;
	Usr_AirConWidget__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 118;
	object->Widget.LocalY = 118;
	object->Widget.LocalWidth = 244;
	object->Widget.LocalHeight = 94;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_AirConPage__ESD_Label__Initializer(Usr_AirConPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 142;
	object->Widget.LocalY = 48;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_AirConPage_ESD_Label_Font__Property;
	object->Text = Usr_AirConPage_ESD_Label_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_AirConPage__ESD_Rectangle_Widget_4__Initializer(Usr_AirConPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget_4;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 112;
	object->Widget.LocalY = 45;
	object->Widget.LocalWidth = 256;
	object->Widget.LocalHeight = 48;
	object->Radius = Usr_AirConPage_ESD_Rectangle_Widget_4_Radius__Property;
	object->Color = Usr_AirConPage_ESD_Rectangle_Widget_4_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_AirConPage__Initializer(Usr_AirConPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_AirConPage_CLASSID;
	context->Widget.Slots = &s_Usr_AirConPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->ButtonPushed = Esd_Noop;
	context->SubPage = 0L;
	Usr_AirConPage__Fixed_Position__Initializer(context);
	Usr_AirConPage__ESD_Touch_Panel_3__Initializer(context);
	Usr_AirConPage__ESD_Touch_Panel_2__Initializer(context);
	Usr_AirConPage__ESD_Touch_Panel_1__Initializer(context);
	Usr_AirConPage__ESD_Touch_Panel__Initializer(context);
	Usr_AirConPage__ESD_Image_1_1_1__Initializer(context);
	Usr_AirConPage__ESD_Image_1_1__Initializer(context);
	Usr_AirConPage__ESD_Image_1__Initializer(context);
	Usr_AirConPage__ESD_Image__Initializer(context);
	Usr_AirConPage__ESD_Label_2_1_1_1__Initializer(context);
	Usr_AirConPage__ESD_Label_2_1_1__Initializer(context);
	Usr_AirConPage__ESD_Label_2_1__Initializer(context);
	Usr_AirConPage__ESD_Label_2__Initializer(context);
	Usr_AirConPage__Humid_Button__Initializer(context);
	Usr_AirConPage__Fan_Button__Initializer(context);
	Usr_AirConPage__Heat_Button__Initializer(context);
	Usr_AirConPage__Cool_Button__Initializer(context);
	Usr_AirConPage__Usr_AirConWidget__Initializer(context);
	Usr_AirConPage__ESD_Label__Initializer(context);
	Usr_AirConPage__ESD_Rectangle_Widget_4__Initializer(context);
}

void Usr_AirConPage_End(Usr_AirConPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Touch_Panel_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Touch_Panel_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Touch_Panel_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Touch_Panel); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_1_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2_1_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Humid_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fan_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Heat_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Cool_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Usr_AirConWidget); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget_4); 
}

int Usr_AirConPage_CurrentPage(Usr_AirConPage *context)
{
	void *owner = context->Owner;
	return context->SubPage;
}

void Usr_AirConPage_ESD_Touch_Panel_3_Tap__Signal(void *c)
{
	Usr_AirConPage *context = (Usr_AirConPage *)c;
	void *owner = context->Owner;
	int set_variable_1_1_1 = 24L;
	context->SubPage = set_variable_1_1_1;
	context->ButtonPushed(owner);
}

void Usr_AirConPage_ESD_Touch_Panel_2_Tap__Signal(void *c)
{
	Usr_AirConPage *context = (Usr_AirConPage *)c;
	void *owner = context->Owner;
	int set_variable_1_1 = 23L;
	context->SubPage = set_variable_1_1;
	context->ButtonPushed(owner);
}

void Usr_AirConPage_ESD_Touch_Panel_1_Tap__Signal(void *c)
{
	Usr_AirConPage *context = (Usr_AirConPage *)c;
	void *owner = context->Owner;
	int set_variable = 21L;
	context->SubPage = set_variable;
	context->ButtonPushed(owner);
}

void Usr_AirConPage_ESD_Touch_Panel_Tap__Signal(void *c)
{
	Usr_AirConPage *context = (Usr_AirConPage *)c;
	void *owner = context->Owner;
	int set_variable_1 = 22L;
	context->SubPage = set_variable_1;
	context->ButtonPushed(owner);
}


/* end of file */
