/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_PowerPage
C Source
*/

#include "Usr_PowerPage.h"

#include "Esd_Context.h"
#include "Usr_GlobalVariables.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);

static uint8_t Usr_PowerPage_ESD_Label_3_1_Font__Property(void *context) { return 29; }
static const char * Usr_PowerPage_ESD_Label_3_1_Text__Property(void *context) { return "Power"; }
static uint8_t Usr_PowerPage_ESD_Label_3_Font__Property(void *context) { return 29; }
static const char * Usr_PowerPage_ESD_Label_3_Text__Property(void *context) { return "Consumption"; }
static uint8_t Usr_PowerPage_ESD_Numeric_Label_1_Font__Property(void *context) { return 29; }
static ft_int32_t Usr_PowerPage_ESD_Numeric_Label_1_Value__Property(void *context);
static ft_int32_t Usr_PowerPage_ESD_Numeric_Label_1_NoOfDigits__Property(void *context) { return 6L; }
static uint8_t Usr_PowerPage_ESD_Numeric_Label_Font__Property(void *context) { return 29; }
static ft_int32_t Usr_PowerPage_ESD_Numeric_Label_Value__Property(void *context) { return 237L; }
static ft_int32_t Usr_PowerPage_ESD_Numeric_Label_NoOfDigits__Property(void *context) { return 6L; }
static uint8_t Usr_PowerPage_ESD_Label_2_1_Font__Property(void *context) { return 29; }
static const char * Usr_PowerPage_ESD_Label_2_1_Text__Property(void *context) { return "kW.h"; }
static uint8_t Usr_PowerPage_ESD_Label_2_Font__Property(void *context) { return 29; }
static const char * Usr_PowerPage_ESD_Label_2_Text__Property(void *context) { return "kW"; }
static Ft_Esd_Theme * Usr_PowerPage_ESD_RangeSlider_Theme__Property(void *context) { return Ft_Esd_Theme_DarkOrange(); }
static ft_int16_t Usr_PowerPage_ESD_RangeSlider_Min__Property(void *context) { return 125; }
static ft_int16_t Usr_PowerPage_ESD_RangeSlider_Max__Property(void *context) { return 255; }
static ft_int16_t Usr_PowerPage_ESD_RangeSlider_Value__Property(void *context);
static uint8_t Usr_PowerPage_ESD_Label_Font__Property(void *context) { return 29; }
static const char * Usr_PowerPage_ESD_Label_Text__Property(void *context) { return "Power"; }
static ft_uint16_t Usr_PowerPage_ESD_Label_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_uint8_t Usr_PowerPage_ESD_Image_Button_MinAlpha__Property(void *context) { return 0; }
static Ft_Esd_BitmapCell Usr_PowerPage_ESD_Image_Button_BitmapNormal__Property(void *context) { return return_circle_64_0(); }
static Ft_Esd_BitmapCell Usr_PowerPage_ESD_Image_2_BitmapCell__Property(void *context) { return FloorHeatOn_0(); }
static ft_int32_t Usr_PowerPage_ESD_Rectangle_Widget_4_Radius__Property(void *context) { return 24L; }
static ft_argb32_t Usr_PowerPage_ESD_Rectangle_Widget_4_Color__Property(void *context) { return 0x59000000UL; }

static Ft_Esd_WidgetSlots s_Usr_PowerPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Usr_PowerPage_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Usr_PowerPage_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_PowerPage_End,
};

static void Usr_PowerPage_ESD_Image_Button_Pushed__Signal(void *context);

void Usr_PowerPage__Fixed_Position__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_PowerPage__ESD_Label_3_1__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_3_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 139;
	object->Widget.LocalY = 287;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_ESD_Label_3_1_Font__Property;
	object->Text = Usr_PowerPage_ESD_Label_3_1_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Label_3__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_3;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 84;
	object->Widget.LocalY = 320;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_ESD_Label_3_Font__Property;
	object->Text = Usr_PowerPage_ESD_Label_3_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Numeric_Label_1__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_NumericLabel *object = (Ft_Esd_NumericLabel *)&context->ESD_Numeric_Label_1;
	Ft_Esd_NumericLabel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 235;
	object->Widget.LocalY = 287;
	object->Widget.LocalWidth = 49;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_ESD_Numeric_Label_1_Font__Property;
	object->Value = Usr_PowerPage_ESD_Numeric_Label_1_Value__Property;
	object->NoOfDigits = Usr_PowerPage_ESD_Numeric_Label_1_NoOfDigits__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Numeric_Label__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_NumericLabel *object = (Ft_Esd_NumericLabel *)&context->ESD_Numeric_Label;
	Ft_Esd_NumericLabel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 260;
	object->Widget.LocalY = 320;
	object->Widget.LocalWidth = 49;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_ESD_Numeric_Label_Font__Property;
	object->Value = Usr_PowerPage_ESD_Numeric_Label_Value__Property;
	object->NoOfDigits = Usr_PowerPage_ESD_Numeric_Label_NoOfDigits__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Label_2_1__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 290;
	object->Widget.LocalY = 287;
	object->Widget.LocalWidth = 47;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_ESD_Label_2_1_Font__Property;
	object->Text = Usr_PowerPage_ESD_Label_2_1_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Label_2__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 324;
	object->Widget.LocalY = 320;
	object->Widget.LocalWidth = 47;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_ESD_Label_2_Font__Property;
	object->Text = Usr_PowerPage_ESD_Label_2_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_RangeSlider__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_RangeSlider *object = (Ft_Esd_RangeSlider *)&context->ESD_RangeSlider;
	Ft_Esd_RangeSlider__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 125;
	object->Widget.LocalY = 232;
	object->Widget.LocalWidth = 220;
	object->Widget.LocalHeight = 39;
	object->Theme = Usr_PowerPage_ESD_RangeSlider_Theme__Property;
	object->Min = Usr_PowerPage_ESD_RangeSlider_Min__Property;
	object->Max = Usr_PowerPage_ESD_RangeSlider_Max__Property;
	object->Value = Usr_PowerPage_ESD_RangeSlider_Value__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Label__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 142;
	object->Widget.LocalY = 39;
	object->Widget.LocalWidth = 180;
	object->Widget.LocalHeight = 36;
	object->Font = Usr_PowerPage_ESD_Label_Font__Property;
	object->Text = Usr_PowerPage_ESD_Label_Text__Property;
	object->AlignX = Usr_PowerPage_ESD_Label_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Image_Button__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 208;
	object->Widget.LocalY = 367;
	object->Widget.LocalWidth = 64;
	object->Widget.LocalHeight = 64;
	object->MinAlpha = Usr_PowerPage_ESD_Image_Button_MinAlpha__Property;
	object->BitmapNormal = Usr_PowerPage_ESD_Image_Button_BitmapNormal__Property;
	object->Pushed = Usr_PowerPage_ESD_Image_Button_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Image_2__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_2;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 132;
	object->Widget.LocalY = 93;
	object->Widget.LocalWidth = 207;
	object->Widget.LocalHeight = 113;
	object->BitmapCell = Usr_PowerPage_ESD_Image_2_BitmapCell__Property;
	object->Scaling = ESD_SCALING_STRETCH;
	object->AutoResize = ESD_AUTORESIZE_NONE;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__ESD_Rectangle_Widget_4__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget_4;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 152;
	object->Widget.LocalY = 31;
	object->Widget.LocalWidth = 161;
	object->Widget.LocalHeight = 48;
	object->Radius = Usr_PowerPage_ESD_Rectangle_Widget_4_Radius__Property;
	object->Color = Usr_PowerPage_ESD_Rectangle_Widget_4_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_PowerPage__Initializer(Usr_PowerPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_PowerPage_CLASSID;
	context->Widget.Slots = &s_Usr_PowerPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->SliderValue = 255L;
	context->BackPushed = Esd_Noop;
	Usr_PowerPage__Fixed_Position__Initializer(context);
	Usr_PowerPage__ESD_Label_3_1__Initializer(context);
	Usr_PowerPage__ESD_Label_3__Initializer(context);
	Usr_PowerPage__ESD_Numeric_Label_1__Initializer(context);
	Usr_PowerPage__ESD_Numeric_Label__Initializer(context);
	Usr_PowerPage__ESD_Label_2_1__Initializer(context);
	Usr_PowerPage__ESD_Label_2__Initializer(context);
	Usr_PowerPage__ESD_RangeSlider__Initializer(context);
	Usr_PowerPage__ESD_Label__Initializer(context);
	Usr_PowerPage__ESD_Image_Button__Initializer(context);
	Usr_PowerPage__ESD_Image_2__Initializer(context);
	Usr_PowerPage__ESD_Rectangle_Widget_4__Initializer(context);
}

extern int g_FloorHeatingPowerValue;


void Usr_PowerPage_Update(Usr_PowerPage *context)
{
	void *owner = context->Owner;
	int update_variable = Ft_Esd_RangeSlider_Output(&context->ESD_RangeSlider);
	g_FloorHeatingPowerValue = update_variable;
	ft_int16_t update_variable_1 = context->ESD_RangeSlider.Value(context->ESD_RangeSlider.Owner);
	context->SliderValue = update_variable_1;
	esd_rgb32_t rgb = 0xffffffUL;
	int a = g_FloorHeatingPowerValue;
	esd_argb32_t update_variable_2 = ESD_COMPOSE_RGB_ALPHA(rgb, a);
	context->ESD_Image_2.Color = update_variable_2;
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Usr_PowerPage_End(Usr_PowerPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_3_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Numeric_Label_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Numeric_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_RangeSlider); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget_4); 
}

void Usr_PowerPage_Start(Usr_PowerPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context); 
	int set_variable = g_FloorHeatingPowerValue;
	context->SliderValue = set_variable;
}

void Usr_PowerPage_Right(Usr_PowerPage *context)
{
	void *owner = context->Owner;
	int left = Ft_Esd_RangeSlider_Output(&context->ESD_RangeSlider);
	int right = 5L;
	int set_variable_2_1 = left + right;
	context->SliderValue = set_variable_2_1;
}

void Usr_PowerPage_Left(Usr_PowerPage *context)
{
	void *owner = context->Owner;
	int left_1 = Ft_Esd_RangeSlider_Output(&context->ESD_RangeSlider);
	int right_1 = 5L;
	int set_variable_3_1 = left_1 - right_1;
	context->SliderValue = set_variable_3_1;
}

ft_int32_t Usr_PowerPage_ESD_Numeric_Label_1_Value__Property(void *c)
{
	Usr_PowerPage *context = (Usr_PowerPage *)c;
	void *owner = context->Owner;
	return g_FloorHeatingPowerValue;
}

ft_int16_t Usr_PowerPage_ESD_RangeSlider_Value__Property(void *c)
{
	Usr_PowerPage *context = (Usr_PowerPage *)c;
	void *owner = context->Owner;
	return context->SliderValue;
}

void Usr_PowerPage_ESD_Image_Button_Pushed__Signal(void *c)
{
	Usr_PowerPage *context = (Usr_PowerPage *)c;
	void *owner = context->Owner;
	context->BackPushed(owner);
}


/* end of file */
