/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_Fan_Page
C Source
*/

#include "Usr_Fan_Page.h"

#include "Esd_Context.h"
#include "Usr_GlobalVariables.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);

static uint8_t Usr_Fan_Page_ESD_Label_Button_1_Font__Property(void *context) { return 31; }
static const char * Usr_Fan_Page_ESD_Label_Button_1_Text__Property(void *context) { return "-"; }
static ft_uint16_t Usr_Fan_Page_ESD_Label_Button_1_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static uint8_t Usr_Fan_Page_ESD_Label_Button_Font__Property(void *context) { return 31; }
static const char * Usr_Fan_Page_ESD_Label_Button_Text__Property(void *context) { return "+"; }
static ft_uint16_t Usr_Fan_Page_ESD_Label_Button_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static Ft_Esd_BitmapCell Usr_Fan_Page_Usr_CircleImageButton_3_1_1_BitmapNormal__Property(void *context) { return back_white_icon_0(); }
static Ft_Esd_BitmapCell Usr_Fan_Page_Usr_CircleImageButton_3_1_BitmapNormal__Property(void *context) { return fan_white_icon_0(); }
static int Usr_Fan_Page_Usr_CircullarSlider_RingWidth__Property(void *context) { return 1L; }
static int Usr_Fan_Page_Usr_CircullarSlider_InnerBorder__Property(void *context) { return 0L; }
static int Usr_Fan_Page_Usr_CircullarSlider_OuterBorder__Property(void *context) { return 0L; }
static ft_argb32_t Usr_Fan_Page_Usr_CircullarSlider_BorderColor__Property(void *context) { return 0xff171916UL; }
static ft_argb32_t Usr_Fan_Page_Usr_CircullarSlider_SelectionColor__Property(void *context) { return 0xff171916UL; }
static ft_argb32_t Usr_Fan_Page_Usr_CircullarSlider_BackgroundColor__Property(void *context) { return 0xff171916UL; }
static ft_argb32_t Usr_Fan_Page_Usr_CircullarSlider_ValueColor__Property(void *context) { return 0xff171916UL; }
static uint8_t Usr_Fan_Page_Mode_Selected_Label_Font__Property(void *context) { return 30; }
static const char * Usr_Fan_Page_Mode_Selected_Label_Text__Property(void *context);
static ft_uint16_t Usr_Fan_Page_Mode_Selected_Label_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static uint8_t Usr_Fan_Page_Fan_Label_Font__Property(void *context) { return 31; }
static const char * Usr_Fan_Page_Fan_Label_Text__Property(void *context) { return "Fan"; }
static ft_uint16_t Usr_Fan_Page_Fan_Label_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_argb32_t Usr_Fan_Page_ESD_Rectangle_Widget_Color__Property(void *context) { return 0xff171916UL; }

static Ft_Esd_WidgetSlots s_Usr_Fan_Page__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Usr_Fan_Page_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_Fan_Page_End,
};

static void Usr_Fan_Page_ESD_Label_Button_1_Pushed__Signal(void *context);
static void Usr_Fan_Page_ESD_Label_Button_Pushed__Signal(void *context);
static void Usr_Fan_Page_Usr_CircleImageButton_3_1_1_Pushed__Signal(void *context);
static void Usr_Fan_Page_Usr_CircleImageButton_3_1_Pushed__Signal(void *context);
static void Usr_Fan_Page_Usr_CircullarSlider_Up__Signal(void *context);
static void Usr_Fan_Page_Usr_CircullarSlider_ValueChanged__Signal(void *context);

void Usr_Fan_Page__Fixed_Position__Initializer(Usr_Fan_Page *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_Fan_Page__ESD_Label_Button_1__Initializer(Usr_Fan_Page *context)
{
	Ft_Esd_LabelButton *object = (Ft_Esd_LabelButton *)&context->ESD_Label_Button_1;
	Ft_Esd_LabelButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 102;
	object->Widget.LocalY = 215;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Font = Usr_Fan_Page_ESD_Label_Button_1_Font__Property;
	object->Text = Usr_Fan_Page_ESD_Label_Button_1_Text__Property;
	object->AlignX = Usr_Fan_Page_ESD_Label_Button_1_AlignX__Property;
	object->Pushed = Usr_Fan_Page_ESD_Label_Button_1_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_Fan_Page__ESD_Label_Button__Initializer(Usr_Fan_Page *context)
{
	Ft_Esd_LabelButton *object = (Ft_Esd_LabelButton *)&context->ESD_Label_Button;
	Ft_Esd_LabelButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 328;
	object->Widget.LocalY = 215;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Font = Usr_Fan_Page_ESD_Label_Button_Font__Property;
	object->Text = Usr_Fan_Page_ESD_Label_Button_Text__Property;
	object->AlignX = Usr_Fan_Page_ESD_Label_Button_AlignX__Property;
	object->Pushed = Usr_Fan_Page_ESD_Label_Button_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_Fan_Page__Usr_CircleImageButton_3_1_1__Initializer(Usr_Fan_Page *context)
{
	Usr_CircleImageButton *object = (Usr_CircleImageButton *)&context->Usr_CircleImageButton_3_1_1;
	Usr_CircleImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 312;
	object->Widget.LocalY = 361;
	object->Widget.LocalWidth = 72;
	object->Widget.LocalHeight = 72;
	object->BitmapNormal = Usr_Fan_Page_Usr_CircleImageButton_3_1_1_BitmapNormal__Property;
	object->BackgroundColor = 0xff171916UL;
	object->Align = ESD_ALIGN_CENTERCENTER;
	object->Pushed = Usr_Fan_Page_Usr_CircleImageButton_3_1_1_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_Fan_Page__Usr_CircleImageButton_3_1__Initializer(Usr_Fan_Page *context)
{
	Usr_CircleImageButton *object = (Usr_CircleImageButton *)&context->Usr_CircleImageButton_3_1;
	Usr_CircleImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 96;
	object->Widget.LocalY = 361;
	object->Widget.LocalWidth = 72;
	object->Widget.LocalHeight = 72;
	object->BitmapNormal = Usr_Fan_Page_Usr_CircleImageButton_3_1_BitmapNormal__Property;
	object->BackgroundColor = 0xff171916UL;
	object->Align = ESD_ALIGN_CENTERCENTER;
	object->Pushed = Usr_Fan_Page_Usr_CircleImageButton_3_1_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_Fan_Page__Usr_CircullarSlider__Initializer(Usr_Fan_Page *context)
{
	Usr_CircullarSlider *object = (Usr_CircullarSlider *)&context->Usr_CircullarSlider;
	Usr_CircullarSlider__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 1;
	object->Widget.LocalWidth = 480;
	object->Widget.LocalHeight = 480;
	object->RingWidth = Usr_Fan_Page_Usr_CircullarSlider_RingWidth__Property;
	object->InnerBorder = Usr_Fan_Page_Usr_CircullarSlider_InnerBorder__Property;
	object->OuterBorder = Usr_Fan_Page_Usr_CircullarSlider_OuterBorder__Property;
	object->BorderColor = Usr_Fan_Page_Usr_CircullarSlider_BorderColor__Property;
	object->SelectionColor = Usr_Fan_Page_Usr_CircullarSlider_SelectionColor__Property;
	object->BackgroundColor = Usr_Fan_Page_Usr_CircullarSlider_BackgroundColor__Property;
	object->ValueColor = Usr_Fan_Page_Usr_CircullarSlider_ValueColor__Property;
	object->Value = 5;
	object->UnitCircle = 10;
	object->MaxValue = 10;
	object->Up = Usr_Fan_Page_Usr_CircullarSlider_Up__Signal;
	object->ValueChanged = Usr_Fan_Page_Usr_CircullarSlider_ValueChanged__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_Fan_Page__Usr_Spin_Image__Initializer(Usr_Fan_Page *context)
{
	Usr_Spin_Image *object = (Usr_Spin_Image *)&context->Usr_Spin_Image;
	Usr_Spin_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 176;
	object->Widget.LocalY = 176;
	object->Widget.LocalWidth = 128;
	object->Widget.LocalHeight = 128;
	object->BitmapCell = fan4_0();
	object->Speed = 4000L;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_Fan_Page__Mode_Selected_Label__Initializer(Usr_Fan_Page *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Mode_Selected_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 140;
	object->Widget.LocalY = 319;
	object->Widget.LocalWidth = 200;
	object->Widget.LocalHeight = 62;
	object->Font = Usr_Fan_Page_Mode_Selected_Label_Font__Property;
	object->Text = Usr_Fan_Page_Mode_Selected_Label_Text__Property;
	object->AlignX = Usr_Fan_Page_Mode_Selected_Label_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_Fan_Page__Fan_Label__Initializer(Usr_Fan_Page *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Fan_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 180;
	object->Widget.LocalY = 43;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 76;
	object->Font = Usr_Fan_Page_Fan_Label_Font__Property;
	object->Text = Usr_Fan_Page_Fan_Label_Text__Property;
	object->AlignX = Usr_Fan_Page_Fan_Label_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_Fan_Page__FanBG_Circle___Initializer(Usr_Fan_Page *context)
{
	Ft_Esd_Circle *object = (Ft_Esd_Circle *)&context->FanBG_Circle_;
	Ft_Esd_Circle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 98;
	object->Widget.LocalY = 98;
	object->Widget.LocalWidth = 284;
	object->Widget.LocalHeight = 284;
	object->Color = 0xff142937UL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_Fan_Page__ESD_Rectangle_Widget__Initializer(Usr_Fan_Page *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 480;
	object->Widget.LocalHeight = 480;
	object->Color = Usr_Fan_Page_ESD_Rectangle_Widget_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void Usr_Fan_Page__Initializer(Usr_Fan_Page *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_Fan_Page_CLASSID;
	context->Widget.Slots = &s_Usr_Fan_Page__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->BackPushed = Esd_Noop;
	context->Local_Method__Value = 0;
	context->NewValue = 0L;
	context->PrevSpeed = 2L;
	context->Local_Method_2__Value = 0;
	Usr_Fan_Page__Fixed_Position__Initializer(context);
	Usr_Fan_Page__ESD_Label_Button_1__Initializer(context);
	Usr_Fan_Page__ESD_Label_Button__Initializer(context);
	Usr_Fan_Page__Usr_CircleImageButton_3_1_1__Initializer(context);
	Usr_Fan_Page__Usr_CircleImageButton_3_1__Initializer(context);
	Usr_Fan_Page__Usr_CircullarSlider__Initializer(context);
	Usr_Fan_Page__Usr_Spin_Image__Initializer(context);
	Usr_Fan_Page__Mode_Selected_Label__Initializer(context);
	Usr_Fan_Page__Fan_Label__Initializer(context);
	Usr_Fan_Page__FanBG_Circle___Initializer(context);
	Usr_Fan_Page__ESD_Rectangle_Widget__Initializer(context);
}

extern int g_FanValue;

static int Usr_Fan_Page_Local_Method(Usr_Fan_Page *context, int value);
static void Usr_Fan_Page_Local_Method__Internal(Usr_Fan_Page *context);
static int Usr_Fan_Page_Local_Method_2(Usr_Fan_Page *context, int value, int prevSpeed);

void Usr_Fan_Page_Update(Usr_Fan_Page *context)
{
	void *owner = context->Owner;
	int if_1 = g_FanValue;
	esd_argb32_t update_variable;
	if (if_1)
	{
		update_variable = 0xff4f9c6aUL;
	}
	else
	{
		update_variable = 0xff969696UL;
	}
	context->Usr_CircleImageButton_3_1.Color = update_variable;
	int value = g_FanValue;
	int update_variable_1;
	switch (value)
	{
		case 0L:
		{
			update_variable_1 = 0L;
			break;
		}
		case 1L:
		{
			update_variable_1 = 2000L;
			break;
		}
		case 2L:
		{
			update_variable_1 = 4000L;
			break;
		}
		case 3L:
		{
			update_variable_1 = 8000L;
			break;
		}
		default:
		{
			update_variable_1 = 1000L;
			break;
		}
	}
	context->Usr_Spin_Image.Speed = update_variable_1;
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Usr_Fan_Page_End(Usr_Fan_Page *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_Button_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Usr_CircleImageButton_3_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Usr_CircleImageButton_3_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Usr_CircullarSlider); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Usr_Spin_Image); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Mode_Selected_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fan_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->FanBG_Circle_); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget); 
}

static int Usr_Fan_Page_Local_Method(Usr_Fan_Page *context, int value)
{
	void *owner = context->Owner;
	if(value < 0) return 0;
	else if (value > 3) return 3;
	else return value;
}

static void Usr_Fan_Page_Local_Method__Internal(Usr_Fan_Page *context)
{
	void *owner = context->Owner;
	int value_1 = context->NewValue;
	context->Local_Method__Value = Usr_Fan_Page_Local_Method(context, value_1);
}

int Usr_Fan_Page_FanOnOff(Usr_Fan_Page *context)
{
	void *owner = context->Owner;
	return g_FanValue;
}

void Usr_Fan_Page_Right(Usr_Fan_Page *context)
{
	void *owner = context->Owner;
	int left = g_FanValue;
	int right = 1L;
	int set_variable_2_1_1 = left + right;
	context->NewValue = set_variable_2_1_1;
	Usr_Fan_Page_Local_Method__Internal(context);
	int set_variable_1 = context->Local_Method__Value;
	g_FanValue = set_variable_1;
}

static int Usr_Fan_Page_Local_Method_2(Usr_Fan_Page *context, int value, int prevSpeed)
{
	void *owner = context->Owner;
	if(value > 0)
	return 0;
	else
	return prevSpeed;
}

void Usr_Fan_Page_Left(Usr_Fan_Page *context)
{
	void *owner = context->Owner;
	int left_1 = g_FanValue;
	int right_1 = 1L;
	int set_variable_3_1 = left_1 - right_1;
	context->NewValue = set_variable_3_1;
	Usr_Fan_Page_Local_Method__Internal(context);
	int set_variable_1_1 = context->Local_Method__Value;
	g_FanValue = set_variable_1_1;
}

void Usr_Fan_Page_ESD_Label_Button_1_Pushed__Signal(void *c)
{
	Usr_Fan_Page *context = (Usr_Fan_Page *)c;
	void *owner = context->Owner;
	int left_2 = g_FanValue;
	int right_2 = 1L;
	int set_variable_3_1_1 = left_2 - right_2;
	context->NewValue = set_variable_3_1_1;
	Usr_Fan_Page_Local_Method__Internal(context);
	int set_variable_1_2 = context->Local_Method__Value;
	g_FanValue = set_variable_1_2;
}

void Usr_Fan_Page_ESD_Label_Button_Pushed__Signal(void *c)
{
	Usr_Fan_Page *context = (Usr_Fan_Page *)c;
	void *owner = context->Owner;
	int left_3 = g_FanValue;
	int right_3 = 1L;
	int set_variable_2_1_1_1 = left_3 + right_3;
	context->NewValue = set_variable_2_1_1_1;
	Usr_Fan_Page_Local_Method__Internal(context);
	int set_variable_1_3 = context->Local_Method__Value;
	g_FanValue = set_variable_1_3;
}

void Usr_Fan_Page_Usr_CircleImageButton_3_1_1_Pushed__Signal(void *c)
{
	Usr_Fan_Page *context = (Usr_Fan_Page *)c;
	void *owner = context->Owner;
	context->BackPushed(owner);
}

void Usr_Fan_Page_Usr_CircleImageButton_3_1_Pushed__Signal(void *c)
{
	Usr_Fan_Page *context = (Usr_Fan_Page *)c;
	void *owner = context->Owner;
	int left_4 = g_FanValue;
	int right_4 = 0L;
	int if_2 = left_4 != right_4;
	if (if_2)
	{
		int set_variable = g_FanValue;
		context->PrevSpeed = set_variable;
	}
	else
	{
	}
	int value_2 = g_FanValue;
	int prevSpeed = context->PrevSpeed;
	context->Local_Method_2__Value = Usr_Fan_Page_Local_Method_2(context, value_2, prevSpeed);
	int set_variable_2 = context->Local_Method_2__Value;
	g_FanValue = set_variable_2;
}

void Usr_Fan_Page_Usr_CircullarSlider_Up__Signal(void *c)
{
	Usr_Fan_Page *context = (Usr_Fan_Page *)c;
	void *owner = context->Owner;
	int set_variable_4 = 5L;
	context->Usr_CircullarSlider.Value = (int)set_variable_4;
}

void Usr_Fan_Page_Usr_CircullarSlider_ValueChanged__Signal(void *c)
{
	Usr_Fan_Page *context = (Usr_Fan_Page *)c;
	void *owner = context->Owner;
	int left_5 = g_FanValue;
	int right_5 = Usr_CircullarSlider_DeltaValue(&context->Usr_CircullarSlider);
	int set_variable_5 = left_5 + right_5;
	context->NewValue = set_variable_5;
	Usr_Fan_Page_Local_Method__Internal(context);
	int set_variable_1_4 = context->Local_Method__Value;
	g_FanValue = set_variable_1_4;
}

const char * Usr_Fan_Page_Mode_Selected_Label_Text__Property(void *c)
{
	Usr_Fan_Page *context = (Usr_Fan_Page *)c;
	void *owner = context->Owner;
	int value_3 = g_FanValue;
	switch (value_3)
	{
		case 0L:
		{
			return "OFF";
		}
		case 1L:
		{
			return "Slow";
		}
		case 2L:
		{
			return "Medium";
		}
		case 3L:
		{
			return "Fast";
		}
		default:
		{
			return "Medium";
		}
	}
}


/* end of file */
