/*
This file is automatically generated
Usr_GrayTextTheme
Header
*/

#ifndef Usr_GrayTextTheme__H
#define Usr_GrayTextTheme__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_Theme.h"

ESD_FUNCTION(Usr_GrayTextTheme, Type = Ft_Esd_Theme *, Include = "Usr_GrayTextTheme.h", Category = _GroupUserResources, Icon = ":/icons/palette.png")
Ft_Esd_Theme *Usr_GrayTextTheme();

#endif /* Usr_GrayTextTheme__H */

/* end of file */
