/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_FloorHeatingPage
Header
*/

#ifndef Usr_FloorHeatingPage__H
#define Usr_FloorHeatingPage__H

#include "Esd_Base.h"
#include "Esd_Core.h"
#include "Esd_FontInfo.h"
#include "FloorHeatOff.h"
#include "FloorHeatOn.h"
#include "Ft_Esd.h"
#include "Ft_Esd_BitmapInfo.h"
#include "Ft_Esd_ImageButton.h"
#include "Ft_Esd_Label.h"
#include "Ft_Esd_Layout_Fixed.h"
#include "Ft_Esd_Rectangle.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_TouchPanel.h"
#include "Ft_Esd_Widget.h"
#include "power.h"
#include "setting.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Usr_FloorHeatingPage_CLASSID 0x9E97BFD8
ESD_SYMBOL(Usr_FloorHeatingPage_CLASSID, Type = esd_classid_t)

ESD_WIDGET(Usr_FloorHeatingPage, Include = "Usr_FloorHeatingPage.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_SIGNAL(ButtonPushed)
	void(* ButtonPushed)(void *context);
	ESD_VARIABLE(SubPage, Type = int, Private)
	int SubPage;
	Ft_Esd_Layout_Fixed Fixed_Position;
	Ft_Esd_TouchPanel ESD_Touch_Panel_1_1_2;
	Ft_Esd_TouchPanel ESD_Touch_Panel_1_1_1;
	Ft_Esd_TouchPanel ESD_Touch_Panel_1_1;
	Ft_Esd_TouchPanel ESD_Touch_Panel_1;
	Ft_Esd_ImageButton ESD_Image_Button_4;
	Ft_Esd_ImageButton ESD_Image_Button_3;
	Ft_Esd_ImageButton ESD_Image_Button_2;
	Ft_Esd_ImageButton ESD_Image_Button;
	Ft_Esd_Rectangle ESD_Rectangle_Widget_3_1;
	Ft_Esd_Rectangle ESD_Rectangle_Widget_3;
	Ft_Esd_Label Label_Light_1_1_1;
	Ft_Esd_Label Label_Light_1_1;
	Ft_Esd_Label Label_Light_1;
	Ft_Esd_Label Label_Light;
	Ft_Esd_Rectangle Rectangle_Heating;
	Ft_Esd_Rectangle Rectangle_Curtain;
	Ft_Esd_Rectangle Rectangle_Air_Con;
	Ft_Esd_Rectangle Rectangle_Light;
	Ft_Esd_Label ESD_Label;
	Ft_Esd_Rectangle ESD_Rectangle_Widget_4;
} Usr_FloorHeatingPage;

void Usr_FloorHeatingPage__Initializer(Usr_FloorHeatingPage *context);

ESD_SLOT(End)
void Usr_FloorHeatingPage_End(Usr_FloorHeatingPage *context);

ESD_OUTPUT(CurrentPage, Type = int)
int Usr_FloorHeatingPage_CurrentPage(Usr_FloorHeatingPage *context);

#endif /* Usr_FloorHeatingPage__H */

/* end of file */
