/*
This file is automatically generated
window4
Header
*/

#ifndef window4__H
#define window4__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell window4(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo window4__Info;

ESD_FUNCTION(window4_0, Type = Ft_Esd_BitmapCell, DisplayName = "window4", Include = "window4.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define window4_0() ((Ft_Esd_BitmapCell){ .Info = &window4__Info, .Cell = 0 })

#endif /* window4__H */

/* end of file */
