/*
This file is automatically generated
Esd_Render__h
Simulation wrapper
*/

/* Simulation wrapper for 'Esd_Render_Bitmap' */


/* Simulation wrapper for 'Esd_Render_Bitmap_Scaled' */


/* Simulation wrapper for 'Esd_Render_Line' */


/* Simulation wrapper for 'Esd_Render_LineF' */


/* Simulation wrapper for 'Esd_Render_MultiGradient' */


/* Simulation wrapper for 'Esd_Render_MultiGradient_Rounded' */


/* Simulation wrapper for 'Esd_Render_Rect' */


/* Simulation wrapper for 'Esd_Render_RectF' */


/* end of file */
